### PR TITLE
Localize Form Emails

### LINKED ISSUE #2386: Mail templates do not use the current locale
## Bug Description

Forms use a Blueprint to define its fields. Unfortunately, field Display names in Blueprints are not localizable. 

Being able to localize the display name of a form field is useful when you want to send an email notification to the sender of the form. For example, if a form is submitted on a German page, you would want a German email to be sent to the sender.

**Since we are unable to localize Blueprint field values**, a workaround is to create a `{locale}.json` file which contains the localized translation for the current locale, and use a `/resources/lang/{locale}/strings.php` file for the named translations. Now we can do this in the email template:

```
{{ trans:strings.form_mail_title }}

{{ fields }}
    {{ trans key="{display}" }}: {{ value }}
{{ /fields }}
```

**However, this does not seem to work.** If I submit a form on the German page of a multi-site, I expect the generated email to be in German but it remains in English.

## Extra Detail

**This is the contact form Blueprint:**

image

**This is the contact form displayed on the German page (the strings here are translated correctly):** 

image

**This is the content of the `/resources/lang/de.json` file:**

```json
{
    "Country": "Land",
    "E-mail address": "E-Mail-Adresse",
    "First Name": "Vorname",
    "Last Name": "Nachname",
    "Message": "Nachricht",
    "Occupation": "Beruf",
    "Telephone number": "Telefonnummer"
}
```

**This is the content of the `/resources/lang/de/strings.php` file:**

```php
return [
    // Contact form
    'form_honeypot'                     => 'Fax',
    'form_mail_body_owner'              => 'Neues Formular einreichen',
    'form_mail_body_sender'             => 'Vielen Dank für Ihre Nachricht, wir werden Sie so schnell wie möglich kontaktieren.',
    'form_mail_closing'                 => 'Mit freundlichen Grüßen',
    'form_mail_from'                    => config('app.name'),
    'form_mail_greeting'                => 'Hallo',
    'form_mail_logo'                    => config('app.url').'/images/mark.png',
    'form_mail_submitted'               => 'Eingereicht',
    'form_mail_title'                   => 'Kontakt Formular',
    'form_mail_url'                     => config('app.url'),
    'form_send'                         => 'Nachricht senden',
    'form_success'                      => 'Vielen Dank, wir haben Ihre Nachricht erhalten und werden Sie so schnell wie möglich kontaktieren.',
];
```

**This is the content of the plaintext email template that is send to the sender of the form:** 

```
{{ trans:strings.form_mail_greeting }} {{ first_name or name }},

{{ trans:strings.form_mail_body_sender }}

{{ trans:strings.form_mail_closing }},
{{ trans:strings.form_mail_from }}

-
{{ fields }}
    {{ trans key="{display}" }}: {{ value }}
{{ /fields }}

-
{{ trans:strings.form_mail_submitted }} {{ now | timezone | format:r }}
{{ trans:strings.form_mail_from }}

```

**And finally, here is the email (html version) of the email that is sent that _should_ be in German:**

image

## Environment

- Statamic 3.0.6 Pro
- Laravel 7.27.0
- PHP 7.4.8
- aryehraber/statamic-impersonator 2.0.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### PR DESCRIPTION
**Pull request by jasonvarga**
This PR passes along the site where the form was submitted into the mailable.

The translator will use the appropriate locale.
Any globals will be localized to the appropriate site.

Fixes #2386

### CODE REVIEW

**Comment by robdekort** [comment]
Hi @jasonvarga, is the subject line also localized? That's the only thing that seems like it isn't yet. I use `{{ trans:strings.form_subject }}` as a subject line.

**Comment by piljac1** [comment]
@robdekort Have you found a workaround for the subject line ? It also isn't getting localized on my end.

**Comment by robdekort** [comment]
Nope, nothing other then picking a word that works in most languages.

**Comment by jasonvarga** [comment]
Please open an issue for the subject line.

**Comment by robdekort** [comment]
https://github.com/statamic/cms/issues/2511

**Comment by jasonvarga** [comment]
That issue is just for the labels.

**Comment by robdekort** [comment]
https://github.com/statamic/cms/issues/2994

**Pull request merged**
