### PR TITLE
Register core permissions after Localize middleware

### LINKED ISSUE #3467: [i18n] CP not always displayed in the user's locale (app.php locale "races" user's preference)
## Bug Description
Related or same as #2041 

In some parts of the CP, there is a race condition between the locale defined in app.php and the locale defined in your user's yaml file

## How to Reproduce
Set the locale to ```en``` in ```config/app.php``` and set the locale to another language in your user yaml file.
Login to the CP. It's apparently fully translated in your user's locale
Create a new set of Permissions
Look as most settings are still displayed in English

Then, change the locale to your user's language in ```config/app.php```and navigate to the same set of permissions
Look as ALL settings are now displayed in your user's locale.

## Extra Detail

Capture d’écran 2021-04-02 à 22 23 40

Capture d’écran 2021-04-02 à 22 24 03

Capture d’écran 2021-04-02 à 22 24 18

## Environment

**Statamic version:** 3.1.3 Pro

**PHP version:** 7.4.2 via MAMP

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### PR DESCRIPTION
**Pull request by arthurperton**
Fixes #3467.

The `CorePermissions::boot()` method registers and translates the permissions. The locale is set in the `Localize` middleware, using the user's locale and falling back the app locale. The `CorePermissions::boot()` should run after the `Localize` middleware to use the right locale for its translations. That is what this PR does.

Issue #2041 is similar, but it is not solved by this PR.

### CODE REVIEW

**Comment by jelleroorda** [comment]
Maybe [#3127](https://github.com/statamic/cms/issues/3127) could also be related? Seems the same kind of error to me. If you can confirm this, we'd probably need to update [this part of the docs to](https://statamic.dev/extending/utilities#creating-a-utility) to tell people to register utilities after the app is booted, [like with permissions](https://statamic.dev/extending/lifecycle#auth-service-provider-boots)?

**Comment by arthurperton** [comment]
Ah thanks Jelle, I didn't know the docs said that!

I'm starting to think that it would be better to set the locale earlier, instead of trying to register permissions and utilities later. But the current user (who's preferred locale we want to know) currently seems to be only known after the `StartSession` middleware is run, and that is too late...

@jasonvarga Any ideas?

**Comment by jasonvarga** [comment]
We need the request to be able to get the current user. The earliest you can do that is in a middleware.

I think we might need to work out how to defer the permission logic until it's actually used within `Permissions@all` or `@tree`, etc.

I started writing a long explanation here but thought it would be easier to just do it than to explain it.

i.e. We should register closures rather than actual permission objects. When Statamic tries to gather all the permissions, it would execute the closures.

It needs to be done in a backwards compatible way though. I don't want people to have to change their code. (Only if they need to fix translation usage)

Feel free to close this one down as I have most of this working locally.

**Comment by arthurperton** [comment]
@jasonvarga Cool!

**Comment by ebeauchamps** [comment]
@jasonvarga Hello! Any chance what you had working locally in April could be now integrated into the Core?

**Comment by mmodler** [comment]
Yust came here via #3127 - we have our cp nav partly in english when unsing an addon with `Utility:make()` (aryehraber/statamic-impersonator)

Any news on this?

**Pull request closed without merging**
