### PR TITLE
[4.x] Updated dutch translations

### PR DESCRIPTION
**Pull request by jeroenpeters1986**
This PR contains the new translated strings in the nl.json and php language files

### CODE REVIEW

**Comment by jasonvarga** [comment]
Thank you.

In the future, run `php translator generate nl` and it will add the appropriate items to the file without mixing up the positions of existing ones. I'm not sure why a bunch of your translation keys were moved around.

**Comment by jeroenpeters1986** [comment]
Thank you @jasonvarga, I will submit a change for the translations page in the docs, as I was not aware of this. This might be useful for others too

**Comment by jeroenpeters1986** [comment]
@jasonvarga these were probably changed because I did some "artisan" labour on this piece and then sorted the file afterwards. I did test it though and it seemed fine on my installation. I will also translate the other messages and update the PR

**Comment by jeroenpeters1986** [comment]
I also added the php files now, so my work on this PR is done

**Comment by jasonvarga** [comment]
Bedankt

**Pull request merged**
