### PR TITLE
Add Global Data to form emails

### LINKED ISSUE #2390: Unable to use "globals" in email templates
## Bug Description
I have created a custom email template to be used in a form. In the footer of this template I would add some company info (like name, phone, ...) using **globals**.

I have added the tag `{{ company:phone }}` (**company** is the Global Set handle) but doesn't output anything in the email.

The same tag in home page works correctly.

## How to Reproduce
1. Create a Global Set (with a handle like `settings`) with a text field (with a name like `foo`)
2. Create an email template: `resources/views/vendor/mail/custom-email.antlers.html`
3. Put this string inside the template: `The Foo value is: {{ settings:foo }}`
4. Create a new Form and set this template as HTML view
5. Send an email from this form and check the mail content (it should be `The Foo value is: `)

## Environment

**Statamic version:** 3.0.7
**PHP version:** 7.4.9

No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### PR DESCRIPTION
**Pull request by damcclean**
This pull request contains a small improvement to the emails that forms sent when they are submitted. It would allow developers to use data from Global Sets inside their email templates.

One use case for this could be that a developer wants to include an email or social media link in the 'Thank you' email after submitting a contact form.

This pull request lets developers use globals in the same way they can if it was a page on their site where the data comes from the Cascade. 

```
Thank you for your submission! We will respond soon. In the mean time, checkout our Facebook profile: {{ social:facebook }}
```

I've tested this and it seems to work well. I copied the code from the `hydrateGlobals` method on the Cascade. The only thing I didn't copy was the 'main global' part. I've never seen it before and wasn't sure on how to grab it. Let me know if you wish to add this as well.

This pull request closes #2390.

### CODE REVIEW

**Comment by jackmcdade** [comment]
What happens now when you have ‘automatic’ enabled? Will it send all that data in the email too?

**Comment by damcclean** [comment]
That's a good question. My guess is that it'll work fine but I'll double check tomorrow.

**Comment by damcclean** [comment]
@jackmcdade Alrighty. Just double checked, the data is not sent when 'automagic' is enabled which obviously makes sense.

**Comment by jasonvarga** [comment]
> The only thing I didn't copy was the 'main global' part. I've never seen it before and wasn't sure on how to grab it.

This is where the variables inside the global set named `global.yaml` get exposed without a prefix. We'll need this. However, this PR is fine, I'll merge it and just add that part myself. Thanks again!

**Pull request merged**
