### PR TITLE
Changes for view overrides

### PR DESCRIPTION
**Pull request by dimitri-koenig**
Hi guys

I'd like to override the View class render method to implement some special custom caching stuff. But since the View class is called via "new View" in DataResponse and some important methods in the View class are private, this is not possible with a clean Laravel binding override approach. This would make that possible.

### CODE REVIEW

**Comment by jasonvarga** [comment]
This is probably fine, but out of curiosity, can you provide an example of what you're planning to do?

**Comment by dimitri-koenig** [comment]
I have a first rough version working fine on production:

```php
    public function render(): string
    {
        $cascade = $this->gatherData();

        $contents = view($this->templateViewName(), $cascade);

        if ($this->shouldUseLayout()) {
            if (Str::endsWith($this->layoutViewPath(), Engine::EXTENSIONS)) {
                $contents = $contents->withoutExtractions();
            }

            $cacheTag = 'v1' . \Str::slug(parse_url(request()->getRequestUri(), PHP_URL_PATH));
            $templateContent = \Cache::get($cacheTag);

            if (!$templateContent) {
                $templateContent = $contents->render();

                if (!blink('no-cache')) {
                    \Cache::tags(['views', 'entry:' . $cascade['id']])->put($cacheTag, $templateContent, 60 * 60);
                }
            }

            $data = array_merge($cascade, [
                'template_content' => $templateContent,
            ]);

            $contents = view($this->layoutViewName(), $data);
        }

        ViewRendered::dispatch($this);

        return $contents->render();
    }
`

That way I can:
* Cache the main content even if due to layout changes some information is only for logged in users visible, but main content stays the same
* If some content should not be cached, i can set a 'no-cache' flag
* If an entry is changed, via event notification and some cache clearing logic, the cache for that entry is cleared too.

With that logic i could reduce load time for all pages by about 150-200%, even if the user is logged in, or the surrounding stuff in the layout file changes.

**Review by jasonvarga — CHANGES_REQUESTED** [review]
There are also instances of `new View` in `FrontendController` and `NotFoundHttpException` which you should replace with container bindings.

**Comment by dimitri-koenig** [comment]
> There are also instances of `new View` in `FrontendController` and `NotFoundHttpException` which you should replace with container bindings.

Thx. Done.

**Comment by dimitri-koenig** [comment]
Sorry, my bad, please check again.

**Comment by dimitri-koenig** [comment]
Perfect, thx

**Pull request merged**
