### PR TITLE
Runtime: fix asset single variable

### PR DESCRIPTION
**Pull request by JohnathonKoster**
This PR adds a special case to allow `Asset` objects to disable tag behavior, making this `{{ asset }} {{ path }} {{ /asset }}` work as expected.

### CODE REVIEW

**Comment by JohnathonKoster** [comment]
Did not create an issue -- just from a discussion within Discord

**Comment by jasonvarga** [comment]
Putting this exception for an Asset in the condition feels odd.

There's probably other instances where this sort of thing would happen.

Like `{{ collection }} ... {{ /collection }}`, for one. What's the differentiator here? 🤔

**Comment by jasonvarga** [comment]
Putting this exception for an Asset in the condition feels odd.

There's probably other instances where this sort of thing would happen.

Like `{{ collection }} ... {{ /collection }}`, for one. What's the differentiator here? 🤔

**Comment by jasonvarga** [comment]
Oh I see it. The collection tag has handling for when it's called without any parameters, emulating a variable.

https://github.com/statamic/cms/blob/e1154d89c10355b32e8a3366f274f6a365d8b582/src/Tags/Collection/Collection.php#L30-L34

I'd rather do a similar thing on the `assets` tag than mess with the parser here.

**Comment by JohnathonKoster** [comment]
> Oh I see it. The collection tag has handling for when it's called without any parameters, emulating a variable.
> 
> https://github.com/statamic/cms/blob/e1154d89c10355b32e8a3366f274f6a365d8b582/src/Tags/Collection/Collection.php#L30-L34
> 
> I'd rather do a similar thing on the `asset` tag than mess with the parser here.

Done!

**Comment by jasonvarga** [comment]
Replacing with #5799

**Pull request closed without merging**
