### PR TITLE
Preserve/Link Section Tabs

### PR DESCRIPTION
**Pull request by jackmcdade**
This pushes a hash of the current #tab to the URL so you can link to a specific tab or refresh the page and stay where you are. Resolves statamic/ideas#102.

### CODE REVIEW

**Comment by jasonvarga** [comment]
Haven't tested it but I'm curious how it would work if you're editing another entry in a stack.

**Comment by jackmcdade** [comment]
Ah good point – it starts push the stack's hash to the URL, and then when you come back it doesn't work properly anymore. 🤔

**Review by jasonvarga — CHANGES_REQUESTED** [review]
Doesn't seem to work. 😢  It adds the hash to the URL but refreshing the page puts me on the first tab.

**Comment by jackmcdade** [comment]
@jasonvarga Found the issue and banished it. Feel free to merge blindly (like a noob) or test again (like a champ). 💪

**Comment by jasonvarga** [comment]
I went the champ route, tested it, and it appears you have fixed it, like a champ.

**Comment by jackmcdade** [comment]
🔥 🕺 🔥

**Comment by robdekort** [comment]
This is very welcomed! Thanks!

**Pull request merged**
