### PR TITLE
🌐 Fix All Spanish Translations

### PR DESCRIPTION
**Pull request by jsbls**
Many fixes for the Spanish translation. Replaced various words and concepts that were technically well translated but weren't the right ones, context-wise.

### CODE REVIEW

**Comment by jackmcdade** [comment]
Thank you so much! Can you adjust the indentation to match so we can have a cleaner diff?

**Comment by jsbls** [comment]
Sure thing! I’ll send a PR later today.

**Comment by jackmcdade** [comment]
This is awesome. Gracias!

**Comment by jsbls** [comment]
My pleasure amigo!

**Pull request merged**
