### PR TITLE
Add asset selector to Bard link toolbar

### LINKED ISSUE #2199: Bard: "Add link to file" is missing
## Bug Description
1. "Add Link" does not show a search field for existing items – currently you need to paste any link by hand.

2. The ability to link to a file is missing: e.g. if the user wants to link one specific word inside a paragraph, he has to manually copy and paste the link from elsewhere.

## How to Reproduce
1. Add a bard field and try to link a word to an existing item, e.g. a page.

2. Add a bard field and try to link a word to a file.

## Extra Detail
Statamic 2
Bildschirmfoto 2020-08-10 um 10 45 45

Statamic 3
Bildschirmfoto 2020-08-10 um 10 55 10

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.4

**Install method (choose one):**
- composer

### PR DESCRIPTION
**Pull request by arthurperton**
I started adding an Asset selector to the Bard link toolbar. This will fix #2199.

Still very much wip, added here as a draft.

My plans for the link toolbar are roughly this:

Screenshot 2021-04-26 at 13 31 57

Feel free to share any thoughts.

### CODE REVIEW

**Comment by jackmcdade** [comment]
I like where you're headed from a UI perspective. I'd certainly fine-tune some things but I like the context switching radio buttons. I'll leave the code side to @jasonvarga.

**Comment by arthurperton** [comment]
Allright, I think it's all there now! 😅 

I am happy with the result. There is a lot of new code, so this definitely needs some testing and maybe some UI tweaks. Enjoy 😃

**Review by jackmcdade — APPROVED** [review]
Made a few tweaks. Nice work!

**Comment by arthurperton** [comment]
Thanks! Curious about the tweaks, looking forward to 3.1.12 👀

**Comment by jackmcdade** [comment]
Just a UI few things and fixed the thumbnail preview.

image

**Comment by arthurperton** [comment]
Nice, I like the text buttons!

**Comment by jackmcdade** [comment]
Thanks! I tend to prefer text over icons if there's only space to pick one. No need to learn what things do, it just tells you :)

**Comment by arthurperton** [comment]
> No need to learn what things do, it just tells you :)

Yep, that's it! I'll remember that.

**Comment by jonatanalvarsson** [comment]
This is a great UX improvement! Thanks! 🙏

**Pull request merged**
