### PR TITLE
Cache properties to speed up nav tag

### PR DESCRIPTION
**Pull request by FrittenKeeZ**
Optimized state variables of Stucture/Nav tag loop - related to statamic/ideas#543

### CODE REVIEW

**Comment by FrittenKeeZ** [comment]
@jasonvarga along with the blueprint fields optimization, this one also has a great impact on performance.

**Comment by FrittenKeeZ** [comment]
@jasonvarga I'll fix the conflicts in regards to #5068 and measure if this addition gives a noticeable performance gain.

**Comment by FrittenKeeZ** [comment]
@jasonvarga I'm seeing a performance increase with these changes for the Nav/Structure tag of roughly 30% having about 1.000 pages.

Times measured in ms taken from debug bar.
```
                 | Run #1 | Run #2 | Run #3 |  Avg |
Tag #1 (3.2.31)  |   1610 |   1610 |   1640 | 1620 |
Tag #1 (changes) |   1150 |   1150 |   1170 | 1157 |
Tag #1 render time decrease: ~28.58%

Tag #2 (3.2.31)  |    331 |    314 |    327 |  324 |
Tag #2 (changes) |    207 |    216 |    230 |  218 |
Tag #2 render time decrease: ~32.72%
```

**Comment by jasonvarga** [comment]
Thank you!

**Pull request merged**
