### PR TITLE
Querybuilder: add whereBetween() and whereNotBetween()

### PR DESCRIPTION
**Pull request by ryanmitchell**
This change allows you to do queries for values that are inside a range, e.g.:

```
Entry::query()
    ->whereBetween('numeric_field', [1, 10])
    ->get();
```
and

```
Entry::query()
    ->whereNotBetween('numeric_field', [1, 10])
    ->get();
```

### CODE REVIEW

**Comment by ryanmitchell** [comment]
I've added the tests and search builder code on this one @jasonvarga

**Comment by ryanmitchell** [comment]
Merge conflicts on this one are resolved too

**Comment by ryanmitchell** [comment]
Yeah the merges are a headache, sorry for giving you work to do.
No problem on the sort - consistency with Laravel is definitely better.

**Comment by jasonvarga** [comment]
No worries it was just a couple of things. 👍 Thanks for the feature!

**Pull request merged**
