### PR TITLE
Fix 404 error when URLs have both ending slash and query parameters

### LINKED ISSUE #3469: Trailing slash and query string returns 404
## Bug Description
It appears that appending urls with a trailing slash and a query string produces a 404 error.

## How to Reproduce

- Visit `/slug/?foo=bar`
- See 404 page error

## Environment

Statamic 3.0.49 Pro
Laravel 7.28.3
PHP 7.4.14
aryehraber/statamic-font-awesome 2.0.0
doublethreedigital/duplicator 1.1.0
rias/statamic-color-swatches 2.0.5
rias/statamic-redirect 1.2.0
statamic/seo-pro 2.0.14

### PR DESCRIPTION
**Pull request by duncanmcclean**
This PR fixes #3469, where you visiting a page with a URL like this would simply 404, `/about/?ref=smth`.

### CODE REVIEW

**Comment by jasonvarga** [comment]
I guess this is fine, and was about to commit this myself earlier, but it bugs me that we do basically the same thing a few lines earlier.

**Comment by duncanmcclean** [comment]
> I guess this is fine, and was about to commit this myself earlier, but it bugs me that we do basically the same thing a few lines earlier.

Huh, that is true. I wonder if it can be refactored... 🤔

**Comment by duncanmcclean** [comment]
> I guess this is fine, and was about to commit this myself earlier, but it bugs me that we do basically the same thing a few lines earlier.

Huh, that's a good point. Just pushed up a change to get rid of my new code and just update what's already there.

**Comment by duncanmcclean** [comment]
> > I guess this is fine, and was about to commit this myself earlier, but it bugs me that we do basically the same thing a few lines earlier.
> 
> Huh, that's a good point. Just pushed up a change to get rid of my new code and just update what's already there.

Nevermind, that seemed to break things, both on my test site and on GH Actions.

**Comment by jasonvarga** [comment]
I'm working on this now so you don't need to do anything, but just an FYI, the test you added already passed before any changes were made.

**Comment by jasonvarga** [comment]
Sorry I take that back. It failed on earlier versions of Laravel. 👍 

Don't mind me. 🤐

**Review by jasonvarga — APPROVED** [review]
I added tests that cover the original reason that str_finish line and condition were added (other code has been added since then in other spots that makes it work now) and cleaned it up a bit.

**Pull request merged**
