### PR TITLE
[5.x] Fix dark mode for Set Picker

### PR DESCRIPTION
**Pull request by martyf**
The current Set Picker is not great in Dark Mode:
image

This PR improves Set Picker dark mode:
image

Resolves https://github.com/statamic/cms/issues/10125

### CODE REVIEW

**Comment by peimn** [comment]
Please refer to the sample and select the appropriate dark shades.

**Comment by jackmcdade** [comment]
> Please refer to the sample and select the appropriate dark shades.

What sample are you referring to? This looks pretty solid to me. Maybe a shade lighter on the search input bg? Maybe not tho...

**Comment by peimn** [comment]
I mean other similar components... However, it is alright if you believe it is correct.

**Comment by jackmcdade** [comment]
You're not banned – you just previously pushed PRs for stuff we already finished.

**Comment by peimn** [comment]
https://github.com/statamic/cms/pull/10150#issuecomment-2123335459

**Comment by jackmcdade** [comment]
Fair enough – i was just trying to save you effort because i was just working on dark mode stuff full time. i'm back off now as i already pushed everything i could find – so feel free to PR again! <3

**Comment by peimn** [comment]
I feel that I've contributed adequately to this update. If there are any additional changes that others may have missed, I'll be sure to push them. I'm planning to focus on other updates.

**Comment by peimn** [comment]
You're welcome!

**Pull request merged**
