### PR TITLE
Add button group translation

### PR DESCRIPTION
**Pull request by jonassiewertsen**
This small PR does add translations for the button group and will close https://github.com/statamic/cms/issues/1662

### CODE REVIEW

**Review by ebeauchamps — CHANGES_REQUESTED** [review]
"Buttons" cannot be deleted from the French file

**Comment by jasonvarga** [comment]
He already fixed that 👍

**Comment by jonassiewertsen** [comment]
@ebeauchamps Is the french grammar correct?

**Comment by ebeauchamps** [comment]
Testing...

**Comment by ebeauchamps** [comment]
This is correcting the Fieldtype title, which I don't want (as I prefer to keep English titles, see #2034 ), but it does not correct the "button_group" labels

Capture d’écran 2020-09-15 à 22 32 20

**Comment by jonassiewertsen** [comment]
That's the same for all Fieldsets for now and can't be changed with this PR.

But the grammar is correct?

**Comment by jasonvarga** [comment]
That's happening because it is using the handle and just uppercasing the first letter. This is not a translation issue, it's an issue with how the form is generating default values.

Like @ebeauchamps said, we should not translate fieldtype titles.

The same thing will happen for other multi-word fieldtypes, like "User Roles".

Thank you for the PR, @jonassiewertsen but I don't think it's necessary here.

**Comment by jonassiewertsen** [comment]
I just wanted to help getting the issue closed 🙃

**Comment by ebeauchamps** [comment]
Thanks @jonassiewertsen but I also should have check more thoroughly the other fieldtypesz. So I am now OK to close the initial issue as you corrected "TARGET BLANK". Thanks to both of you!!

**Pull request closed without merging**
