### PR TITLE
Avoid missing fieldset import to break cp forms

### PR DESCRIPTION
**Pull request by juliawarnke**
The problem: 
When a user changes the slug of a an imported fieldset cp forms will break.

The suggested solution:
Instead of returning null and thereby throw an exception when the fieldset could not be found, we return a section fieldtype with a message, that the imported fieldset does not exist.

The question is if people would prefer a section fieldtype to display the error message or if a new fieldtype should be created for it?

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Hey! Does this pull request cover any existing issues?

**Comment by juliawarnke** [comment]
I think this one might be the same issue. It's the same behaviour:
https://github.com/statamic/cms/issues/3061

**Comment by jonassiewertsen** [comment]
@duncanmcclean I did look myself for existing issues, but couldn't find related ones. 

_I can confirm this behavior though._

It might be important to mention, that this PR will fix an ugly bug. I would call it ugly, because by renaming a Fieldset it's easy to break the cp and to throw a 500 error. An error easily to reproduce by only using the control panel, but an error that can't be fixed using the control panel. 

**Background**
Julia and I are working on a projekt for a bigger client. By simply making adjustments in the control panel, we need to jump in to fix 500 errors once or twice a day, by simply working with fieldsets.

**Comment by duncanmcclean** [comment]
> @duncanmcclean I did look myself for existing issues, but couldn't find related ones.
> 
> _I can confirm this behavior though._
> 
> It might be important to mention, that this PR will fix an ugly bug. I would call it ugly, because by renaming a Fieldset it's easy to break the cp and to throw a 500 error. An error easily to reproduce by only using the control panel, but an error that can't be fixed using the control panel.
> 
> **Background**
> Julia and I are working on a projekt for a bigger client. By simply making adjustments in the control panel, we need to jump in to fix 500 errors once or twice a day, by simply working with fieldsets.

Cool, just wanted to check, in case this pull requests fixes an open issue.

**Comment by juliawarnke** [comment]
The pull request is still a draft because we would like to know if people prefer a new fieldtype to show the error message or if the section fieldtype would be enough for now?

**Comment by jasonvarga** [comment]
Interesting solution. We'll think about it! 🤔 

I wonder if a more natural solution would be to just make _nothing_ appear.

**Comment by jonassiewertsen** [comment]
We talked about it as well, but thought that it's a much cleaner solution from the UX perspective to give direct feedback. 

In case a fieldset is not found, I do think that it's a problem in most cases. If this is the case, we can just show a solution to the user. 

Personally I would prefer to always return a fieldtype, but would think it might be even better to return a `importNotFound` fieldset. This might contain information and might be collapsed by default or other funny UX things Jack might like :-)

**Comment by jasonvarga** [comment]
Fair point! Some feedback:

(There's a lot, so I don't expect you to do it all. These could just be notes for us when we are able to address it ourselves)

**Blueprint builder**

I agree that it would be nice to get some visual feedback on the blueprint builder that a fieldset is invalid. This PR doesn't do that yet, though. It still just looks valid.

image


**FieldsetRepository::find**

Making the `find` method return a fake fieldset doesn't quite feel right.
I would expect that if you called `find`, you either get one or you don't.

The logic for the fake fieldset creation could be moved into where where it's actually imported.
That's here: https://github.com/statamic/cms/blob/4df11ff6d2526a81111d9a33b869c4ed2abaaffb/src/Fields/Fields.php#L204


**Field references**

Fixing imports of a whole fieldset is nice, but there's also the issue where if you're a single field and you rename the fieldset, you get different errors. I think that's probably what #3061 is actually running into. Same problem though.

If we want to apply the same "fieldset is missing" UX to a missing single field (and we should), we'll need to handle that too.


**Using a section fieldtype**

Finally, using a `section` to display the message was a clever idea. I think I'd rather a `html` fieldtype with some red text on it instead. If you are importing a single field and using widths, the section would look odd.

image

image

**Review by jasonvarga — CHANGES_REQUESTED** [review]
☝️

**Comment by juliawarnke** [comment]
Thanks @jasonvarga for your feedback. @jonassiewertsen and i will take a look at it.

**Comment by jasonvarga** [comment]
Thanks again for the PR. Closing it for now but of course feel free to take another stab at it later (or we will when we can).

**Pull request closed without merging**
