### PR TITLE
Add ability to add a blueprint to user roles

### PR DESCRIPTION
**Pull request by ryanmitchell**
This PR adds the ability to modify the blueprint associated with a user roles by adding some new routes, controllers and borrowing from the work on the similar PR for user groups. This would allow developers to add new fields to the roles, such as images, descriptions or whatever they want.

I had to approach the Vue component slightly differently due to the desire to not affect how permissions work, hopefully how I've handled it is acceptable.

### CODE REVIEW

**Comment by ryanmitchell** [comment]
Oh its getting the same segmentation fault in the tests... hmm.

**Comment by jasonvarga** [comment]
Personally I'm not sure doing this on the role side of things makes too much sense. People already question the difference between groups and roles.

If you wanted to "add data" to a user grouping, I'd suggest sticking to groups. Leave roles to being just a permission feature. Having all this data and blueprint stuff be available to only user groups makes the distinction from roles just that much more clearer.

**Comment by ryanmitchell** [comment]
Yep that makes sense - happy for there to be a clean distinction. I'll close this off.

**Comment by jasonvarga** [comment]
Was this something you actually needed? Or were you just being thorough? 😄

**Comment by ryanmitchell** [comment]
We've done it both ways on membership sites (roles or groups)... if there was only data on one it would force us to use groups. Though I'd imagine folk will ask why its on one and not the other...

I was being thorough :)

**Comment by jasonvarga** [comment]
Okay well let's leave this closed if you don't mind. If it becomes a hot button issue we can always resurrect this PR.

Thanks for understanding!

**Pull request closed without merging**
