### PR TITLE
[4.x] Fix create entry button

### LINKED ISSUE #8488: Create Entry button gives "Page Not Found" error
### Bug description

Fresh new site (and my existing sites) that are running 4.13.1 (note 4.13.0 is OK).

Create new entry in collection where the view is set to List View (Tree View is OK) results in "Page Not Found" error in CP.

### How to reproduce

- Create new collection.
- On the default screen of a new collection - Create Entry - works OK.
- Click create entry button to add second entry - Page not found error 
- Change to Tree View - click Create Entry button - works OK.
- Change back to List View - click Create Entry button - Page not found error.

This also happens on the default Pages collection if in list view, but tree view is OK.

### Logs

```shell
No log created.
```

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.16.0
PHP Version: 8.2.1
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: collectiontest.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.13.1 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

My test repo https://github.com/mscruse/statamic-collection-create-entry

### PR DESCRIPTION
**Pull request by jasonvarga**
Fixes #8488. Introduced by #8487.

### CODE REVIEW

**Comment by jasonvarga** [comment]
Yup I noticed that too. Rather than spending time figuring out if those events are a problem (I don't think they are since everything else works fine), I'll just handle the case where it sets site to null.

**Comment by Dimchao** [comment]
@jasonvarga This is still an issue for me after having updated earlier tonight.

**Comment by jasonvarga** [comment]
@Dimchao What's happening for you?

**Comment by Dimchao** [comment]
@jasonvarga I updated a couple of nights ago, and then later noticed this issue. I tried updating for the fix you posted on the 26th, and it the issue persisted: displaying 404 Page Not Found. I ended up having to roll back to my pre-update save and proceeded from there. Wary of updating now since it took me several hours to find out this was a known bug.

**Comment by jasonvarga** [comment]
A couple of nights ago the bug was introduced and this PR was to fix it, yesterday. Are you sure the issue is still there in 4.13.2?

**Pull request merged**
