### PR TITLE
Pass ENV to SymfonyProcess via getenv() call.

### PR DESCRIPTION
**Pull request by michaelr0**
Aim's to fix issue with installing/updating Addons or Statamic via the Statamic Control Panel.

For those who get the error:

```
In Factory.php line 677:
                                                                               
  The HOME or COMPOSER_HOME environment variable must be set for composer to   
  run correctly   
```

As referenced in https://github.com/statamic/cms/issues/3383

Addon installation is currently now working.
However there are issues with the Statamic Core updates, which appear to remove the contents of vendor/statamic/cms

I'm not sure where to start in regards to the removal issue, so feel free to chime in.

Thanks.

### CODE REVIEW

**Comment by jasonvarga** [comment]
What do you mean it removes the contents?

**Comment by michaelr0** [comment]
> What do you mean it removes the contents?

My guess is that during the update process of statamic/cms, composer was removing the contents of the vendor/statamic/cms folder in preperation to replace it with requested version, but this caused the update process and php artisan/php please to malfunction due to the missing statamic/cms dependency.

However it appears that I'm now unable to replicate that issue, very odd.

I've tested on a M1 Mac Mini (PHP 8.0 via Homebrew) and a Laptop (Ubuntu 20.04, PHP 7.4) both using php artisan serve and the above change to push the ENV to SymfonyProcess has resolved the error below (for me)

```
In Factory.php line 677:
                                                                               
  The HOME or COMPOSER_HOME environment variable must be set for composer to   
  run correctly  
```

**Comment by michaelr0** [comment]
Thanks Jason, yes that's a solid point.
I actually wondered if it would be passing API keys etc from the .Env file, but had assumed that it would have normally been doing that anyway.

Agreed, it says it should automatically get it, but for whatever reason it isn't, I guess at the very least, manually passing ['HOME' => getenv('HOME')] might do the trick, we could add whatever additional ENV as needed?

**Comment by jasonvarga** [comment]
I saw that you suggested passing in an array with just HOME in it, but you removed it from your comment. Why? That sounds like a safer thing and I'd be happy to merge that right in.

**Comment by michaelr0** [comment]
> I saw that you suggested passing in an array with just HOME in it, but you removed it from your comment. Why? That sounds like a safer thing and I'd be happy to merge that right in.

Hi Jason, yeah sorry, I haven't had a chance to test that yet, I'm unsure at this stage if anything else is needed to be passed as well, I'll test it shortly and come back to you.

I had looked into the Symfony Process code as above and I wondered if it would normally have access to the contents of the .env file ? But it looks like composer doesn't use the .env file, but rather the contents are loaded outside of composer via Laravel https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Bootstrap/LoadEnvironmentVariables.php

**Comment by michaelr0** [comment]
Hi Jason,

I have changed it to 
```php
   ['HOME' => getenv('HOME')]
```

I have tested upgrading and downgrading Statamic and installing, upgrading, downgrading and uninstalling Addon's

All appears functional with php artisan serve.

Thanks.

**Review by jasonvarga — APPROVED** [review]
Thanks!

**Pull request merged**
