### PR TITLE
Use email template from form config

### PR DESCRIPTION
**Pull request by damcclean**
This pull request allows for a template to be used when sending form submission emails. [See the documentation on it here](https://statamic.dev/forms#emails).

Before this pull request you could add the `template` key to a form email configuration but it would be left un used.

This pull request gets the template defined inside the config and renders that template with the submission data.

Both Antlers and Blade views get rendered correctly in my testing.

### CODE REVIEW

**Comment by jasonvarga** [comment]
Thanks for the PR.

We've actually got rid of the text-and-html-in-one thing from v2.
Now you should set separate views for `text` and `html`. Just like a regular Laravel Mailable.

Functionally it's working, but looks like we need to:
- update the docs to show the new way
- remove the template field from the ui
- add separate text and html view fields to the ui
- mention the change in the upgrade guide

**Comment by damcclean** [comment]
> Thanks for the PR.
> 
> We've actually got rid of the text-and-html-in-one thing from v2.
> Now you should set separate views for `text` and `html`. Just like a regular Laravel Mailable.
> 
> Functionally it's working, but looks like we need to:
> 
> * update the docs to show the new way
> * remove the template field from the ui
> * add separate text and html view fields to the ui
> * mention the change in the upgrade guide

So instead of using a template, like in v2, Statamic will use a separate HTML template and a separate text template?

Does that mean that you would use the `html` and `text` fields instead to pick the templates used, or is my usage wrong?

```
email:
  -
    to: my@email.com
    subject: 'Contact Form'
    from: mail@email.com
    reply_to: "{{ email }}"
    html: emails.html.contact
    text: emails.text.contact
```

**Comment by jasonvarga** [comment]
That looks right

**Comment by damcclean** [comment]
Oh ok. It's not working though. Doing some source diving, looks like it gets stripped out somewhere before it hits the `addViews` method. I'll look a little more into it and create an issue.

**Comment by damcclean** [comment]
> Oh ok. It's not working though. Doing some source diving, looks like it gets stripped out somewhere before it hits the `addViews` method. I'll look a little more into it and create an issue.

Just made a quick fix to stop them from being stripped out 😄

**Pull request closed without merging**
