### PR TITLE
Add basic support for default preferences in `resources/preferences.yaml`

### PR DESCRIPTION
**Pull request by jesseleite**
While working on our customizable nav, we decided to add the ability to store default preferences for all users. This PR doesn't add any UX, it just implements basic default preferences at a PHP level.

- [x] Add `DataPreferences::save($preferences)` helper.
- [x] When getting preferences via `Preference::get()`, check user first, then role, then default preferences.
- [x] Add test coverage.

### CODE REVIEW

**Review by jasonvarga — CHANGES_REQUESTED** [review]
This is rad.

Although passing an array into `save` feels a little unusual to me. I don't think we really do that anywhere else. Also, whether it should update the entire preferences array or merge with the existing one is debatable.

How about we get rid of the debate and force you to do it explicitly?

```php
DefaultPreferences::set([..])->save();
DefaultPreferences::merge([..])->save();
```

Those could call `(new static)->setPreferences()` and `mergePreferences`.

What do you think?

**Comment by jesseleite** [comment]
I dig 👍

Also rather than going nuts with static methods, I added a helper to our existing `Preference` facade, so you can now chain off of `default()`...

```php
use Statamic\Facades\Preference;

Preference::default()->set([...])->save();
Preference::default()->merge([...])->save();
```

**Comment by jasonvarga** [comment]
Even better!

**Review by jasonvarga — APPROVED** [review]

**Comment by j3ll3yfi5h** [comment]
@jesseleite Thanks for this feature. Am I right, that `after_save: continue_editing` is currently not supported?

**Comment by jasonvarga** [comment]
It seems to work fine.

```yaml
collections:
  articles:
    after_save: continue_editing
```

**Comment by j3ll3yfi5h** [comment]
Ah💡 It does not need a `preferences:` on first line...

**Comment by duncanmcclean** [comment]
Where's the recommended place to put the `Preference::default()->set([...])->save();` code? In a service provider?

**Pull request merged**
