### PR TITLE
[3.1] Independent Auth Guard for Statamic

### PR DESCRIPTION
**Pull request by duncanmcclean**
This pull request implements #2391. Developers who want to use a different set of users for Statamic than they do the rest of their Laravel app should now be able to do so.

### CODE REVIEW

**Comment by jasonvarga** [comment]
This is a great start but I don't think it's quite right.

You've pushed that middleware straight onto the kernel, so it'll happen* on every request. It'll use the Statamic guard on non-Statamic routes and you'll end up with the same problem.

*I haven't tested, but I'm just guessing by looking at it.

**Comment by damcclean** [comment]
Ah, that's a fair point. I've updated this PR so the middleware is only pushed on Statamic CP routes and front-end routes managed by Statamic. Hopefully that's better.

**Comment by jasonvarga** [comment]
I gotta work out the right place to put this in the docs, but here's a rough draft.

## Independent Auth Guard

By default, Statamic comes configured to use the default auth guard.

This means that any users will be considered Statamic's users.

An example wanting to change this could be if your application's users would not be interacting with Statamic, and only one or a few users would be using the Control Panel. It would be possible to keep your Statamic users in yaml files, and your app's users in a database.

If you'd like Statamic to use its own guards, you can configure it that way in your config files.

```php
// config/statamic/users.php

'guards' => [
    'cp' => 'web', // the guard when using the cp
    'web' => 'web', // the guard when using Statamic frontend routes
],
```

Any non-Statamic routes (e.g. any routes you've manually added to `routes/web.php`) will be unaffected by the above config. They'll be using whatever your "default" guard is.

```php
// config/auth.php

'defaults' => [
  'guard' => 'web',
  'passwords' => 'users',
],

'guards' => [
    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],
    'statamic' => [
        'driver' => 'session',
        'provider' => 'statamic',
    ]
],

'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => \App\User::class,
    ],
    'statamic' => [
        'driver' => 'statamic',
    ],
],
```

**Comment by gausoft** [comment]
Using Statamic 3.3 but having the same issue

**Pull request merged**
