### PR TITLE
[FIX] Visual glitch with checkbox field #3183

### PR DESCRIPTION
**Pull request by berdjabrahamian**
This fixed issue #3183
See attached before and after

**BEFORE**
Before

**AFTER**
After

### CODE REVIEW

**Comment by jackmcdade** [comment]
What browser are you using? Everything looks perfect without changes to me...

**Comment by jasonvarga** [comment]
and what operating system?

**Comment by berdjabrahamian** [comment]
@jackmcdade @jasonvarga

Tested:

**Chrome 88 -> Mac Catalina**
browserstack-chrome-88-mac-catalina

**Firefox 85.0.1 (64-bit) -> Ubuntu 20.04**
firefox-85


Safari on Mac looks good
Firefox on Mac looks good
Need to still test other browsers, browser versions, and OS

Going to make a new commit, to fix the *click on label to select/deselect input"

**Comment by jackmcdade** [comment]
Fixed this a different way – thanks for the persistence to see it through!

**Comment by berdjabrahamian** [comment]
That's fine for you to update it via css, however, I just looked at the form fields templates that is used for the frontend render, and you follow the same design structure. As much as its semantically works. the best method is the way I had proposed originally as is far better semantically and accessibility. 

We can take it a step further and give it aria-labels as well. Its a small update/change, I dont mind doing it. It will make a difference.

**Pull request closed without merging**
