### PR TITLE
Add Chinese (Traditional, Taiwan) Translations

### PR DESCRIPTION
**Pull request by binotaliu**

### CODE REVIEW

**Review by ebeauchamps — COMMENTED** [review]
Hello, I am somehow surprised that in your language you cannot follow the same pattern as in English for keys that are separated with a pipe, such as:

     "1 update|:count updates": ":count 項更新",
     ":count item selected|:count items selected": "已選擇 :count 項",
     ":count row|:count rows": ":count 行",
     ":count selected|:count selected": "已選 :count",
     ":count set|:count sets": ":count 組",

But of course, perhaps the Chinese language doesn't need pluralisation forms? I definitely don't know about that, some please forgive me if I am mistaken.

Cheers.

**Comment by binotaliu** [comment]
We don't have plural form.

**Comment by binotaliu** [comment]
Oops... rebased to wrong branch. I'll fix that soon.

**Comment by jasonvarga** [comment]
謝謝!

**Pull request merged**
