### PR TITLE
[5.x] Sync datetime dark mode with control panel

### PR DESCRIPTION
**Pull request by peimn**
The V-Calendar component features a dark mode using shades of blue, but it isn't synchronized with the control panel.

Fixes https://github.com/statamic/cms/issues/10482.

### CODE REVIEW

**Comment by peimn** [comment]
This PR addresses #10482

**Review by jasonvarga — APPROVED** [review]
All the style was there, it wasn't necessary to add any more.

Instead, I've made a `Statamic.darkMode` reactive property which gets used in the component's prop. The way it was reading the preference before was not correct since it may have been `"auto"`.

**Comment by peimn** [comment]
@jasonvarga  yes, it did have a problem. However, the style of the date-time picker has a blue tint in dark mode. Please look at the screenshots below:
image
image

Is it not necessary to make them the same? cp and date picker.

**Comment by jasonvarga** [comment]
Ah sorry I see what you mean. I will leave it to @jackmcdade

**Pull request merged**
