### PR TITLE
Enable fixed toolbar on a Bard field inside a set

### LINKED ISSUE #3230: Bard Toolbar Not Fixed
## Bug Description
Bard's toolbar doesn't stay fixed on scroll when the Bard field is inside a Replicator set. 

## How to Reproduce
- Create a Replicator field
- Add a set that includes a Bard field
- Set the bard option `toolbar_mode: fixed`

## Environment
Statamic 3.0.42 Pro
Laravel 8.26.1
PHP 7.4.15
aerni/social-links 2.1.0
aerni/zipper 1.2.0
aryehraber/statamic-impersonator 2.1.0
jonassiewertsen/statamic-livewire 2.4.0
spatie/statamic-responsive-images 1.8.0
visuellverstehen/statamic-classify 2.0.1
withcandour/aardvark-seo 2.0.7

### PR DESCRIPTION
**Pull request by arthurperton**
Fixes #3230 and some other minor issues with the fixed Bard toolbar.

### CODE REVIEW

**Comment by jackmcdade** [comment]
👏  Thanks Arthur!

**Comment by sjclark** [comment]
This seems to have regressed at some point? Bards within Bards seem to work fine with fixed toolbars - but bards within replicators fail to have their toolbars fixed properly.

https://github.com/user-attachments/assets/58a2278d-9fb5-44cb-b76a-e80abe08f445

Note the bard in the replicator has the default fixed toolbar_mode set 👍

This was pointed out by community member `Brendyn` in the Discord

**Comment by jacksleight** [comment]
I think it was changed in v4 due to various edge case issues, see:

https://github.com/statamic/cms/pull/7922
https://github.com/statamic/cms/pull/8022

**Comment by sjclark** [comment]
> I think it was changed in v4 due to some edge case issues, see:
> 
> #7921 #7922 #8022

Cheers Jack, will reference https://github.com/statamic/cms/pull/7922#issuecomment-1510479207 in the discord 👍

**Pull request merged**
