### PR TITLE
Starter kit post-install hooks

### PR DESCRIPTION
**Pull request by jesseleite**
This is similar to @ryanmitchell's [awesome PR](https://github.com/statamic/cms/pull/6757), except that with this PR, you won't have to manually export or configure the hook in your `starter-kit.yaml` file...

```yaml
export_paths:
  - app/Hooks/SomeHook.php
after_install_hook: '\App\Hooks\SomeHook'
```

Instead of requiring the above yaml, it'll implicitly look for a `StarterKitPostInstall.php` class at the starter kit root, and run its `handle()` method...

```php
<?php

class StarterKitPostInstall
{
    public function handle($console)
    {
        //
    }
}
```

Also, since this approach isn't copying the script to user-land (it is being run directly from `vendor`), it doesn't need to be deleted/unlinked after.

### Todo

- [x] Implicitly run `StarterKitPostInstall@handle()` when running `starter-kit:install`.
- [x] Implicitly copy `StarterKitPostInstall.php` when running `starter-kit:install --with-config`.
- [x] Implicitly export `StarterKitPostInstall.php` when running `starter-kit:export`.
- [x] Add test coverage.

### CODE REVIEW

**Comment by ryanmitchell** [comment]
Yeah that’s much nicer, thank you.

**Comment by robdekort** [comment]
Screenshot 2022-09-27 at 10 04 03

**Review by jasonvarga — APPROVED** [review]
LGTM but will wait to see if the testbench failures resolve themselves before merging.

**Comment by jesseleite** [comment]
LGTM: "Less Github Tests Mess"?

**Comment by robdekort** [comment]
Lovely! Ready on this side. https://github.com/studio1902/statamic-peak/pull/260

**Pull request merged**
