### PR TITLE
Bye to FontAwesome, hello to new SVG icons and better Bard & Markdown toolbars

### PR DESCRIPTION
**Pull request by jackmcdade**
image

image

### CODE REVIEW

**Comment by jacksleight** [comment]
@jackmcdade I don't suppose you know what font that is?

Screenshot 2023-02-16 at 12 31 39

**Comment by jackmcdade** [comment]
The H1-H6 is Circe Rounded, but I'm not sure about Bold and Italic — they're icons from [Streamline](https://streamlineiq.com).

**Comment by jacksleight** [comment]
For some reason the H1 icon looks slightly different to the rest. Or is that just me?

Screenshot 2023-02-17 at 12 47 37
Screenshot 2023-02-17 at 12 47 54

**Comment by jackmcdade** [comment]
I had to squish 2-6 because they’re wider. I can squish 1 a bit too I suppose. On Feb 17, 2023, at 7:51 AM, Jack Sleight ***@***.***> wrote:﻿
For some reason the H1 icon looks slightly different to the rest. Or is that just me?

**Pull request merged**
