### PR TITLE
[5.x] Add select modifier

### PR DESCRIPTION
**Pull request by godismyjudge95**
Sometimes it is useful to do more than just pluck a single set of values from an array/collection of items.

Similar to [Laravel's](https://laravel.com/docs/11.x/helpers#method-array-only) `Arr::only` this PR adds an `only` modifier to handle those cases where you need more than one key.

### Example Data:
```php
$items = [
    ['title' => 'Bread', 'slug' => 'bread', 'price' => '2'],
    ['title' => 'LEGO Coffee', 'slug' => 'lego-coffee', 'price' => '37'],
];
```

### Example Template:
```antlers
{{ items | only('title', 'slug') | to_json }}
```

### Example Output:
```json
[{"title":"Bread","slug":"bread"},{"title":"LEGO Coffee","slug":"lego-coffee"}]
```

### CODE REVIEW

**Comment by jasonvarga** [comment]
Similar. Pluck grabs a single value and flattens the array. What he's proposing is to maintain the associative array but only specific keys in each.

**Review by jasonvarga — CHANGES_REQUESTED** [review]
I think this modifier should be called `select`. Copying Collection's `select` method:

https://laravel.com/docs/11.x/collections#method-select

Collection's `only` method works differently.

**Comment by jackmcdade** [comment]
Ahh, thanks for the clarification! Carry on 🤘

**Comment by godismyjudge95** [comment]
> I think this modifier should be called `select`. Copying Collection's `select` method:
> 
> [laravel.com/docs/11.x/collections#method-select](https://laravel.com/docs/11.x/collections#method-select)
> 
> Collection's `only` method works differently.

Ah yeah good catch.  Only is for filtering a single level array.

**Review by jasonvarga — CHANGES_REQUESTED** [review]
I think you can probably also use `->select()` on the collection now.

**Comment by godismyjudge95** [comment]
> I think you can probably also use `->select()` on the collection now.

I don't believe that works when the items don't implement `ArrayAccess`.
I just tried replacing the `->map()` call with:
```php
$items = $value->select($keys);
```
And a bunch of the tests fail.


I think that is why the `pluck` modifier does this:
```php
return method_exists($item, 'value') ? $item->value($key) : $item->get($key);
```

**Comment by jasonvarga** [comment]
Fair!

**Pull request merged**
