### PR TITLE
Data tables fix for screens less then 768px

### PR DESCRIPTION
**Pull request by brandonferens**
This PR address the issue raised in #2595.

The primary issue was with using `width: fit-content` and setting the data table to `display: block`. I was able to add a min-width of 100% while testing, but the child thead, tbody, etc. didn't respect the min width.

I removed the fit-content and moved the css for a data-table once it hits the medium screen to the base `.data-table` class.

There are a few concerns that I have with the data-table. I'm assuming that the fit-content was in hopes of having the table get wrapped in a div so that on smaller screens in could be scrolled horizontally, but none of the wrapping components, primarily the card class, have overflow-x set to auto, so it wouldn't scroll any way.

If you have thoughts, suggestions, whatever, let me know, and I can help address them. Thanks!

### CODE REVIEW

**Comment by brandonferens** [comment]
Now that I am thinking about it, the table itself was expected to be the horizontal scrolling container on smaller screens. Let me see what I can do about that...

**Comment by brandonferens** [comment]
I added a new `.data table-wrapper` class that manages the horizontal scrolling instead of relying on a display change for the table. I've updated the blade and vue components as well with the addition.

**Review by jasonvarga — CHANGES_REQUESTED** [review]
Are you able to undo the indentation of the tables? Just put your wrappers on the same level as the existing tables.

I know that's a bit counter intuitive but it'll be much easier for us to review the changes.

``` html
<div class="data-table-wrapper">
<table>
  ...
</table>
</div>
```

rather than

``` html
<div class="data-table-wrapper">
    <table>
      ...
    </table>
</div>
```
```

**Comment by brandonferens** [comment]
I can do that @jasonvarga

**Comment by brandonferens** [comment]
@jasonvarga I've made those changes.

**Comment by jackmcdade** [comment]
@brandonferens I really appreciate the effort for putting together this fix! It did cause a bit of it's own undesired effect though, where there was extra padding or space at the bottom of each table that caused its own scrollable overflow. I tried, but was unable to find a resolution to it.

So I went digging for the root cause and found that the problem was actually the popovers (namely the dropdown lists for each row, and the column control) were causing an overflow offset that wasn't resolved until a repaint. So I made a few tweaks to the config and simplified the `.data-table` css and it seems to be sorted out. I've got that over here: https://github.com/statamic/cms/pull/2811

Thank you for giving us the push to track this down. 😊

**Comment by brandonferens** [comment]
@jackmcdade I'm glad you found that fix. Something never did feel right about my attempt at fixing the issue. Glad you found a better way of getting it sorted out!

**Pull request closed without merging**
