### PR TITLE
[4.x] Avoid expensive file copy when using local source filesystem

### PR DESCRIPTION
**Pull request by FrittenKeeZ**

### CODE REVIEW

**Comment by jasonvarga** [comment]
This feels like an existing issue but I'm having trouble finding it. Do you know if there's a related issue?

**Comment by FrittenKeeZ** [comment]
@jasonvarga yeah, it's this one https://github.com/statamic/cms/issues/6495

**Comment by jasonvarga** [comment]
I just feel like this specifically was discussed before. Maybe it was in Discord. 🤷 

Do you have a good way to benchmark the before/after of this change?

**Comment by FrittenKeeZ** [comment]
@jasonvarga we're just in the end of our deadline for going live with a new project, but I'll have a look at it when I get some breathing space

**Comment by jasonvarga** [comment]
I did a naive benchmark. Put this in a template:

```antlers
{{ assets container="assets" }}
    <li>{{ path }}</li>
{{ /assets }}
```

Filled an asset directory with a whole bunch of assets, deleted the .meta directory, cleared the cache, then looked at how long the tag took to render using the Antlers profiler.

~870ms before, ~315ms after.

Not really sure what situation you were in that this was affecting you drastically though. This only gets run when generating the .meta files. Regardless, nice improvement. Thanks and sorry for the delay.

**Pull request merged**
