### PR TITLE
[5.x] Support rendering model attributes in Antlers

### PR DESCRIPTION
**Pull request by ryanmitchell**
This PR ensures Laravel model attributes can be rendered in antlers without having to add them to appends().

This allows you to do things like:

```php
class MyModel extends \Illuminate\Database\Eloquent\Model
{
    public function fooBar(): Attribute
    {
        return Attribute::make(
            get: fn() => 'FooBar',
        );
    }
}
```

```antlers
{{ my_model:foo_bar }}
```

I hope I did this right and @JohnathonKoster approves of the approach.

Closes https://github.com/statamic/cms/issues/7356

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Niiiice!

**Comment by jasonvarga** [comment]
I haven't tested, but just looking at the code it seems that this will only work if you use the new style of attributes. e.g. `getSomethingAttribute` and doing `model:something` won't work.

Do we need to be checking if the returned value of the method is an attribute?

If you do `{{ model:something }}` and we know it's a `Model`, why not always just do `$model->something`?

**Comment by ryanmitchell** [comment]
Yeah it’s set to only work with new attributes. Old style would still need added to appends so they appear in toarray. 

The runtime parser seems to get the array of data and then get from it so it wouldn’t know what the ‘something’ is. Unless I’m missing that.

**Comment by jasonvarga** [comment]
Ah yeah okay I misread what was happening here. I thought it was pulling a single value out but it's really getting all the context data. My mistake.

**Comment by ryanmitchell** [comment]
Yeah. Your way would be better if I could figure out how to do it.

**Comment by ryanmitchell** [comment]
So simple. Thank you.

**Pull request merged**
