### PR TITLE
Fix save hidden code field

### LINKED ISSUE #5555: Trying to access array offset on value of type null Error on save with empty hidden code field.
### Bug description

I just started getting this error after upgrading to 3.3 on my local.  It happens when I try to save a page that has a specific blueprint attached to it and it won't let me save the edits to the page. I have a toggle field that conditionally shows a code_field. But if the code_field is empty even though the toggle field is disabled it throws this error. 

Screen Shot 2022-03-17 at 2 34 51 PM

### How to reproduce

I try to save a page with the code_field and it throws an error if it's empty even though the toggle to show it is off, after commenting out the code_field I can save properly.

Here's my code field and toggle blueprint snippet:

      -
        handle: code_block
        field:
          default: false
          display: 'Code Block'
          type: toggle
          icon: toggle
          instructions: 'Toggle on to enter a block of raw HTML.'
          listable: hidden
          instructions_position: above
      -
        handle: the_code_block
        field:
          theme: material
          mode: htmlmixed
          mode_selectable: false
          indent_type: tabs
          indent_size: 2
          key_map: default
          line_numbers: true
          line_wrapping: true
          display: 'The Code Block'
          type: code
          icon: code
          listable: hidden
          instructions_position: above
          if:
            code_block: 'equals true'

### Logs

```shell
[2022-03-17 21:41:25] local.ERROR: Trying to access array offset on value of type null {"userId":"6820e525-b792-4c0a-a452-9594efeabdeb","exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Fieldtypes/Code.php:129)
[stacktrace]
#0 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Fieldtypes/Code.php(129): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Trying to acces...', '/Users/josephl/...', 129)
#1 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Fields/Field.php(299): Statamic\\Fieldtypes\\Code->process(NULL)
#2 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): Statamic\\Fields\\Field->process()
#3 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(Statamic\\Fields\\Field), 'the_code_block')
#4 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(695): array_map(Object(Closure), Array, Array)
#5 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->map(Object(Closure))
#6 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Fields/Fields.php(147): Illuminate\\Support\\HigherOrderCollectionProxy->__call('process', Array)
#7 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Http/Controllers/CP/Collections/EntriesController.php(185): Statamic\\Fields\\Fields->process()
#8 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Collections\\EntriesController->update(Object(Illuminate\\Http\\Request), Object(Statamic\\Entries\\Collection), Object(Statamic\\Entries\\Entry))
#9 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('update', Array)
#10 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Collections\\EntriesController), 'update')
#11 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#12 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#13 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AddToasts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#34 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#43 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#44 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#45 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#46 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#47 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#74 /Users/josephl/Sites/CRISTA/worldconcern-statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#75 /Users/josephl/Sites/CRISTA/worldconcern-statamic/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#76 /Users/josephl/.composer/vendor/laravel/valet/server.php(234): require('/Users/josephl/...')
#77 {main}
"}
```

### Versions

Statamic 3.3.1 Pro
Laravel 8.83.5
PHP 8.1.1
doublethreedigital/duplicator 2.1.1
mitydigital/statamic-rss-feed 1.4.4
rias/statamic-redirect 2.1.0
spatie/statamic-responsive-images 2.10.0
statamic/seo-pro 3.1.0
visuellverstehen/statamic-classify 2.3.2

### Installation

Starter Kit using via CLI

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by htulibacki**
This should fix #5555.

### CODE REVIEW

**Comment by jackmcdade** [comment]
Thanks! @jesseleite wanna give this a look?

**Comment by jasonvarga** [comment]
Thanks. Closing in favor of #5923.

**Comment by jasonvarga** [comment]
Thanks. Closing in favor of #5923.

**Comment by jasonvarga** [comment]
Thanks. Closing in favor of #5923.

**Pull request closed without merging**
