### PR TITLE
Make Stache invalidate at a given time

### PR DESCRIPTION
**Pull request by aerni**
This PR aims to resolve issue https://github.com/statamic/cms/issues/2217. It's a draft with two commits, each taking a different approach. Both approaches work. But I'm not sure if either approach is the right way to go about this. 

It feels dirty to check for an index name of `status` in the `Index` class. But I honestly couldn't think of another way to solve this.

If anything, I hope that this PR at least gets the ball rolling in finding a good solution.

### CODE REVIEW

**Comment by edalzell** [comment]
@aerni does this address this: https://github.com/statamic/ideas/issues/588?

**Comment by aerni** [comment]
@edalzell I'm pretty sure you're talking about this PR: https://github.com/statamic/cms/pull/4665

**Comment by jasonvarga** [comment]
Closing this for now as it's been sitting as a draft for months. Feel free to reopen in the future if/when it's ready.

**Comment by aerni** [comment]
It's only a "draft" because it's showing two different approaches. I'm waiting for your to decide if either is a good way to go.

**Comment by jasonvarga** [comment]
We have dedicated index classes for special fields. I guess instead of checking `status`, you could check `$this->expirable()` or something and use that to know whether it needs to save/expire using timestamps. Then make a `Status` index that is `expirable`.

**Comment by aerni** [comment]
I created a new PR #5089 with the suggested changes. Hope it's going into the right direction now.

**Pull request closed without merging**
