### PR TITLE
[4.x] Use Blink Cache for flattened pages in Collection Structure

### PR DESCRIPTION
**Pull request by o1y**
This PR reduces memory overhead for collections with structure/tree, as described in #7424 (see [comment](https://github.com/statamic/cms/issues/7424#issuecomment-1410652690)).

By utilizing Blink Cache to retrieve already fetched pages, the frequency of calling the underlying [flattenedPages()](https://github.com/statamic/cms/blob/3.4/src/Structures/Pages.php#L89-L99) method is reduced, especially for projects that use a lot of structured collections. This increases the generation time of Stache Indexes by around ~30%, especially when the project is using lot of collections with enabled structure/tree.

No issues with incorrect Stache data were found in my tests, but feedback and more testing is welcome. I have used a few test projects for testing, including multi-sites.

## Results Before / After
Here are my performance results for the repo in the linked [issue](https://github.com/statamic/cms/issues/7424): 

### Before
* ~5000 entries
* ssg:generate: ~300ms per file.

```
[34] Generate /7cace6b9-f8de-4caf-af51-60ae59054d2e    (320ms)
[35] Generate /04580b2a-3bc1-4464-b83a-97c0eacf9146    (315ms)
[36] Generate /fdf0e4fe-bead-4b9e-baf7-cd4e19a006bc    (316ms)
[37] Generate /a7725ceb-a0af-4d2b-b280-12b3db55fa64    (338ms)
[38] Generate /4d0283d8-082c-4e77-a2fa-18b80df6d957    (324ms)
```

### After
* ~5000 entries
* ssg:generate: ~50ms per file.

```
[988] Generate /e5e59a92-1d2b-48ed-8617-87a23fda610a    (51ms)
[989] Generate /052ac173-a944-40b3-8881-f2ef40da81e9    (51ms)
[990] Generate /effd600d-c9ff-4147-a14d-54f12ce66fbf    (51ms)
[991] Generate /8c255acb-7c7c-44de-b1f7-82c705af213d    (51ms)
```

## Profiler (Before)
I was using a profiler to find out that the method `flattenedPages()` was called quite often. In this case, the structured collection contained around 200 entries.

Bildschirm­foto 2023-02-05 um 21 47 11

### CODE REVIEW

**Comment by jasonvarga** [comment]
kirby lol

**Comment by jasonvarga** [comment]
Since this is a bit out of date, I got it updated to 4.x and tried some benchmarks again.

On 4.0:
- `stache:warm` takes ~3:20
- `ssg:generate` I cancelled it after 20 minutes, and it had only generated 2.5k files. Each page takes ~350ms

After the PR:
- `stache:warm` takes ~1:57
- `ssg:generate` takes ~5:50, each page takes ~60ms

**Comment by jasonvarga** [comment]
I'm not sure what you meant about this line though:

> This increases the generation time of Stache Indexes by around ~30%,

Did you mean decreases? Because stache:warm is faster now.

**Comment by o1y** [comment]
> Did you mean decreases? Because stache:warm is faster now.

ah, lol, yes! xD 

Thanks for the update to v4! 🏎️ 💨

**Pull request merged**
