### PR TITLE
Show published status in tree view

### LINKED ISSUE #3344: Unpublished pages appear Published in Tree View
## Bug Description
No way to tell if pages are hidden or visible in the tree view of an orderable collection

## How to Reproduce
View an orderable collection in tree view

## Extra Detail
Two of these pages are un-published; but its impossible to tell which:
Screen Shot 2021-03-08 at 5 50 38 pm
Unless you switch to list view:
Screen Shot 2021-03-08 at 5 56 28 pm

## Suggested fix - fade opacity; or give some sort of visual feedback on unpublished content:
Screen Shot 2021-03-08 at 5 51 26 pm
(I believe this is similar to how v2 displayed?)

## Environment
Statamic 3.0.45 Pro
Laravel 8.29.0
PHP 7.4.12
doublethreedigital/duplicator 1.2.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### PR DESCRIPTION
**Pull request by arthurperton**
Fixes #3344.

### CODE REVIEW

**Review by jasonvarga — APPROVED** [review]
I like it.

For easier reviewing, here's a screenshot.

image

@jackmcdade ?

**Comment by arthurperton** [comment]
That was quick 😄

**Comment by duncanmcclean** [comment]
👀  This is really nice, I often find myself forgetting what is published and what is not.

**Comment by jackmcdade** [comment]
Approved!

**Pull request merged**
