### PR TITLE
[5.x] Allow make:addon to work for any minimum-stability

### PR DESCRIPTION
**Pull request by duncanmcclean**
This pull request fixes an issue with the `php please make:addon` command where Composer will throw an error when requiring a new addon when an app's `minimum-stability` setting is anything other than `dev`.

### CODE REVIEW

**Comment by jasonvarga** [comment]
Ideally we should avoid that.

If you don't have `mininum-stability`, you're still able to do `composer require my/addon dev-master` and it'll work.

It's just a matter of figuring out what branch it needs. `dev-master` or `dev-main`. Composer figures it out under the hood somehow. Maybe we can lift the logic from there. 🤔

**Comment by duncanmcclean** [comment]
Going to mark this as a draft for now, until I have time to dig into this some more.

**Comment by jasonvarga** [comment]
I think this does it. Wanna check?

**Comment by duncanmcclean** [comment]
Yep, that does it! Thanks for taking a look.

**Pull request merged**
