### PR TITLE
Add `@collection` directive

### PR DESCRIPTION
**Pull request by edalzell**
Implements https://github.com/statamic/ideas/issues/212

### CODE REVIEW

**Comment by jasonvarga** [comment]
This is a nice start 🎉 but what about parameters?

**Comment by edalzell** [comment]
What about ‘em?

**Comment by jasonvarga** [comment]
As it stands you can just get all the entries. What about limiting, filtering, pagination?

**Comment by edalzell** [comment]
Oh you want FAAAANCY stuff.

**Comment by edalzell** [comment]
@jasonvarga any ideas how you parse parameters passed into custom directives? They come in as a string.

**Comment by jasonvarga** [comment]
No but I imagine you can look at some of the native Laravel Blade directives, like `@include` that allow arguments.

**Comment by edalzell** [comment]
done @jasonvarga. Didn't do pagination as it returns something different and I didn't want to deal with it now.

**Comment by jasonvarga** [comment]
This is great Erin, thank you for the PR. However I don't think this is quite what we'd want in the core in it's current state. You should be able to plop all of this in an addon very easily though.

**Pull request closed without merging**
