### PR TITLE
Ability to bypass localization confirmation modal

### PR DESCRIPTION
**Pull request by jasonvarga**
In #6943 we added a modal confirmation prompt where you can pick which site the origin of the new entry should be.

However this breaks the workflow of some clever workarounds that were used to force the origin as per #4287.

This PR allows you to choose whether you get the prompt, whether the root should be the origin, or whether the actively edited entry's site should be the origin (which was the behavior before the prompt was added).

This will allow the workaround in #4287 to be scrapped in favor of setting a config option.

### CODE REVIEW

**Comment by jasonvarga** [comment]
The new config options feels a bit out of place.

This should probably be a setting in each collection's yaml file. I can see people potentially wanting different behavior per collection.

**Comment by jasonvarga** [comment]
Naming is hard, but we're calling this the "origin behavior".

```yml
# content/collections/blog.yaml

origin_behavior: select  # the default - the modal will ask which site
origin_behavior: root    # no modal, immediately use the root localization (where the entry was first created)
origin_behavior: active  # no modal, immediately use the site of the entry currently being edited. this is behavior before the modal was introduced
```

**Comment by jasonvarga** [comment]
@tao Let me know how this goes for you.

**Comment by tao** [comment]
Thanks @jasonvarga this works well for me and I can remove the custom event listener I had before... 👍🏻 🚀 🌟

**Pull request merged**
