### PR TITLE
Update Dutch translation

### PR DESCRIPTION
**Pull request by oakeddev**
Update Dutch translation & reorder the strings so it's the same for the English base files

### CODE REVIEW

**Comment by jasonvarga** [comment]
The order is determined by the `php translator generate` command. Next time someone uses that command, it'll just put it back how it was. Please resubmit with just translation changes, and not reordering the files.

**Comment by oakeddev** [comment]
Ah didn´t know that. Will do!

**Comment by jasonvarga** [comment]
I appreciate the intention though 😄

**Comment by oakeddev** [comment]
I know, no hard feelings. [New PR](https://github.com/statamic/cms/pull/7053) is waiting...

**Pull request closed without merging**
