### PR TITLE
Add item totals to CP listings/pagination

### PR DESCRIPTION
**Pull request by jacksleight**
This PR adds item totals to the CP listings/pagination. This is otherwise unused space so I though it might be a nice touch:

Screenshot 2022-06-23 at 17 01 05

Useful when you're searching and want to see how many entries match the filter.

### CODE REVIEW

**Review by jasonvarga — CHANGES_REQUESTED** [review]
Looks great! Small thing.

It doesn't quite work when there are no results.

CleanShot 2022-06-23 at 15 24 23

**Comment by edalzell** [comment]
I'd prefer if there is nothing to show nothing, instead of the `0 of 0`, but maybe that's just me?

**Comment by jasonvarga** [comment]
> I'd prefer if there is nothing to show nothing, instead of the 0 of 0, but maybe that's just me?

Nope, me too. Good suggestion.

---

I've pushed up a few small changes.

- Got rid of the "items" in the string. This will prevent the need to handle pluralization in the translation (e.g. 1-1 of 1 items)
- Changed the variables so there's no camelCase vars in the translation
- Center aligned with the numbers and dropdown.

CleanShot 2022-06-27 at 16 47 13

---

I'll leave this to @jackmcdade to push the button.

**Review by jasonvarga — APPROVED** [review]

**Review by jackmcdade — APPROVED** [review]

**Comment by jackmcdade** [comment]
Looks great, thanks!

**Comment by robdekort** [comment]
Noticed some layout issues on CP widgets and the asset picker.
Screenshot 2022-07-05 at 09 13 26
Screenshot 2022-07-05 at 09 13 59

**Comment by jacksleight** [comment]
All sorted in https://github.com/statamic/cms/pull/6279 🙂

**Comment by robdekort** [comment]
Ohhh nice!

**Pull request closed without merging**
