### PR TITLE
Multiple modifier parameters must go back as an array

### PR DESCRIPTION
**Pull request by edalzell**
The second (or more) parameter on a modifier was not being used.

I couldn't find the parsing tests to add one, if you point me at them, I'll add one for this issue.

### CODE REVIEW

**Comment by edalzell** [comment]
Fixes https://github.com/statamic/cms/issues/1146

**Comment by jasonvarga** [comment]
Not sure what happened here but there's nothing to review or merge.

**Comment by jackmcdade** [comment]
@edalzell is there a commit to look at?

**Comment by edalzell** [comment]
ya because I did it on master when the pullbot force pulled it lost the diff

image

**Comment by jasonvarga** [comment]
Of what file

**Comment by edalzell** [comment]
https://github.com/statamic/cms/blob/master/src/View/Antlers/Parser.php#L1255

**Pull request closed without merging**
