### PR TITLE
Improve Nova integration

### PR DESCRIPTION
**Pull request by jasonvarga**
It's possible to use Nova with Statamic already - you can see how here: https://statamic.dev/knowledge-base/laravel-nova

This PR makes the integration just a little nicer, reducing those steps from 5 to 3.

https://github.com/statamic/ideas/issues/238

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Does this change mean it would no longer be required to turn off Statamic's default routing? You'd just be able to leave it turned on? 

If so, major thanks! 🤝

**Comment by jasonvarga** [comment]
Yeah exactly.

**Comment by duncanmcclean** [comment]
> Yeah exactly.

Sweet! That'll save pain on new projects.

**Comment by jasonvarga** [comment]
With this regex, if you have a page like `/nova-scotia` and Nova installed, it won't work.

I can add a `/` to the end of the regex, which fixes it, but then `/nova` doesn't work. (`/nova/*` would though)

**Pull request merged**
