### PR TITLE
Querybuilder:  add whereDate(), whereMonth(), whereDay(), whereYear() and whereTime()

### PR DESCRIPTION
**Pull request by ryanmitchell**
This change allows you to do queries on date fields. This assumes that the date field is held in a format Carbon can parse (I couldn't see a way of getting the saveFormat() from the stache indexes, if anyone knows how that would be a much better solution).

```
Entry::query()
    ->whereDate('test_date', 1637000264)
    ->get();
```

and

```
Entry::query()
    ->whereDate('test_date', '>', '2021-11-15')
    ->get();
```

along with the equivalents for whereMonth(), whereDay(), whereYear() and whereTime() 

Closes https://github.com/statamic/ideas/issues/510

### CODE REVIEW

**Comment by duncanmcclean** [comment]
You're smashing it with these query builder PRs!! 🔥

**Comment by ryanmitchell** [comment]
> You're smashing it with these query builder PRs!! 🔥

I feel bad opening so many 😆 But Jason said he wanted compatibility with eloquent so he asked for it...

**Comment by ryanmitchell** [comment]
> I didn't mean we had to have parity just for parity's sake. Just when people need it 🤣 But hey no complaints.

Don't back down now @jasonvarga 😆  ... I need them, they are very useful in add-ons and event listeners.

**Comment by ryanmitchell** [comment]
I've added the asset tests and iteratorbuilder coverage to this one

**Comment by jasonvarga** [comment]
Gotta merge the 3.2 branch into this to resolve the conflicts. (Same with the other PRs)

**Comment by ryanmitchell** [comment]
Yeah the downside of separate PRs. 
Can we agree an order and then I can merge into the next one after each hits the main branch ?

**Comment by ryanmitchell** [comment]
I've resolved the merge conflicts on this one

**Comment by jasonvarga** [comment]
I'll sort out the merge when I review this.

**Comment by ryanmitchell** [comment]
Its ok I've resolved the merge on it - less for you to do.

Just a heads up that this one is the one I'm least sure about due to the need for the date to be stored in the entry YAML in a Carbon::parse()-able format. It feels clunky to me - would be better if there was a way to get the date format from the blueprint and parse that format.

**Comment by jasonvarga** [comment]
Good question. I think the solution - on the query builder side, at least - is simple:

Just expect the value to be a Carbon instance. Don't do any parsing.

I'm going to work on something today that'll put Carbon instances in the Stache if they use date fieldtypes.
The `date` field (literally the entry's publish date) is already in the Stache as a Carbon instance.

Related issues:
- https://github.com/statamic/cms/pull/2624
- https://github.com/statamic/cms/issues/1759
- https://github.com/statamic/ideas/issues/321

**Comment by jasonvarga** [comment]
To clarify:

The value you're passing into the query can be a `Carbon` instance, **or** a Carbon-parseable string. You're already doing that. Great!

The value that'll be in the index that you're querying _against_ - you can assume that'll be a `Carbon` instance. Don't try to parse it. You're doing that now, but you can rip that out.

**Comment by ryanmitchell** [comment]
Yep I'm with you. All done. Obviously tests will fail until your change with the stache indexes

**Comment by jasonvarga** [comment]
I've changed the #5156 to target `master`. I'll do the same with this branch and do all the necessary merges.

**Comment by jasonvarga** [comment]
Also all the tests need to have Carbon values. I'll tweak that too.

**Comment by ryanmitchell** [comment]
> Also all the tests need to have Carbon values. I'll tweak that too.

Thanks, I'm not sure how to get the tests to reference a blueprint so that it knows to treat the `test_date` field as a date field. Interested to see how its done.

**Pull request merged**
