### PR TITLE
[4.x] Filter out any nulls from front end form checkboxes

### PR DESCRIPTION
**Pull request by ryanmitchell**
Filter out any null values in checkboxes on front end form requests.

The hidden input cant be removed as it was [added to solve an issue on user profile forms](https://github.com/statamic/cms/pull/7180/files).

Closes https://github.com/statamic/cms/issues/9194

### CODE REVIEW

**Review by duncanmcclean — COMMENTED** [review]
While this *is* now filtering out `null` values, it's also filtering out checked values which we don't want to be filtering out.

**Comment by ryanmitchell** [comment]
What do you mean by a checked value?

**Comment by duncanmcclean** [comment]
> What do you mean by a checked value?

If I 'check' a checkbox, that doesn't get saved.

**Comment by ryanmitchell** [comment]
Yeah but what is the value on the checkbox input? It would need to have a value=“something” for it not to be filtered.

**Comment by duncanmcclean** [comment]
Nevermind, I didn't add any options to the checkbox field. Working now!

**Review by duncanmcclean — APPROVED** [review]

**Pull request merged**
