### PR TITLE
Fix date column on form submissions table

### LINKED ISSUE #2948: Form submissions columns: date preference being ignored
## Bug Description
Form submissions columns: datestamp preference being ignored

## How to Reproduce

1) Go to form submissions
2) Amend columns (include date)
3) Refresh 

## Extra Detail

No console errors logged.

**User config file after saving column preferences**

```yaml
preferences:
  forms:
    contact:
      columns:
        - datestamp
        - name
        - email
```

**Form blueprint**
```yaml
title: Contact
fields:
  -
    handle: name
    field:
      type: text
      display: Name
      validate: ''
  -
    handle: email
    field:
      type: text
      display: 'Email Address'
      validate: required|email
  -
    handle: message
    field:
      type: text
      display: Message
      validate: required

```

## Environment
Statamic 3.0.31 Pro
Laravel 8.14.0
PHP 7.3.7
aryehraber/statamic-captcha 1.0.3
edalzell/variable 1.0.1
statamic/migrator dev-master
statamic/seo-pro 2.0.14

**Install method (choose one):**
- Existing statamic v3 site

### PR DESCRIPTION
**Pull request by duncanmcclean**
Fixes #2948 (#3966 originally but closed now as it was a duplicate)

### CODE REVIEW

**Comment by RafaelKr** [comment]
@duncanmcclean Thanks for the fast fix!

I'm not sure by just looking at the code, but can the column be hidden now? Or is it always visible?

**Comment by RafaelKr** [comment]
Ah I see, it's just used for the initial-columns, So probably it's included in the columns GET parameter now and should be hidden if the user said so.

**Comment by duncanmcclean** [comment]
Yeah, it'll still be hidden if that's what you choose to do. 👍

**Review by jasonvarga — APPROVED** [review]
I've tweaked this so the date becomes the first column.

Otherwise, 👍 

Something to note though, if you hide the date column, nothing is clickable and you'll have to choose View from the twirldown. This is covered by #1494 though.

**Pull request merged**
