### PR TITLE
[5.x] Update and fix strings translation for Italian language

### PR DESCRIPTION
**Pull request by gioppy**
Update and fix all strings translated with Google Translate in Italian.

### CODE REVIEW

**Comment by vitalijalbu** [comment]
@gioppy @jasonvarga wanted to say that "PRO" is also translated in italian with "Professional", that in my opinion PRO should be equal for all languages..

**Comment by jasonvarga** [comment]
This PR changes it to just `Pro` which I think is good. I didn't notice Professionale when I ran Google Translate on everything. 👌

**Comment by vitali-bc** [comment]
> This PR changes it to just `Pro` which I think is good. I didn't notice Professionale when I ran Google Translate on everything. 👌

heah, basically i think **PRO** can stay as non-translated string... for all languages.. 👀

**Comment by jasonvarga** [comment]
I initially thought so too, but we made it translatable for languages that don't use English characters, like Persian or Arabic. They would still use "Pro" (and even "Statamic") but it would be written phonetically using their alphabet.

**Pull request merged**
