### PR TITLE
[5.x] Add `push` modifier for arrays

### PR DESCRIPTION
**Pull request by ryanmitchell**
This just came up on discord (https://discord.com/channels/489818810157891584/1153390699161587823/1277561682406805576) - might be handy to have a `push` modifier.

`{{ my_array | push('value') }}`

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Nice. I actually thought this already existed! 😄

**Comment by jackmcdade** [comment]
I love it!

**Comment by jasonvarga** [comment]
This doesn't work in loops due to how variables are scoped in Antlers. Yes this would push a value to the array like the tests show, but the use case linked to was a loop, and it wouldn't work there.

You can use native Antlers though.

```antlers
{{ ids = [] }}

{{ articles }}
  {{ ids += id }}
{{ /articles }}

{{ ids | to_json }}
```

**Comment by ryanmitchell** [comment]
Ah. Probably worth reverting then to avoid any confusion it will cause?

**Pull request merged**
