### PR TITLE
Fix array fieldtype always being dirty

### PR DESCRIPTION
**Pull request by jackmcdade**

### CODE REVIEW

**Review by arthurperton — COMMENTED** [review]
Couldn’t the data be assigned in line 84 instead of in `created()`? I think that will prevent the unwanted triggering of the watch method. And you won’t need the `mounted` property then.

**Comment by jasonvarga** [comment]
What does `this.$watch('')` do?

**Comment by jackmcdade** [comment]
@jasonvarga It binds a watcher. I found it in some of your older commits: https://github.com/statamic/cms/commit/90977f444eb8b460cbd4f9c36dac4a1beffb8b2c

**Comment by jackmcdade** [comment]
@jasonvarga Oh i see what you mean, I left an unfinished thing in there. Might have committed an undo state.

**Comment by jackmcdade** [comment]
Give that a second glance and see what you think.

**Comment by arthurperton** [comment]
I’m not sure who you’re asking, but I’m answering 😀 

This is exactly what I meant. Just lose the `mounted: false,` in line 86 too and you’re golden I think.

**Comment by jackmcdade** [comment]
@arthurperton Any second opinion. Good catch, thank you!

**Pull request merged**
