### PR TITLE
[4.x] Reduce computed value callback calls

### PR DESCRIPTION
**Pull request by jacksleight**
I’ve noticed that when using computed values the same callbacks are being called 17 times during a single page load, which is unexpected and seems unnecessary. I know the docs recommend caching computed values when using external APIs or performing other expensive tasks, but even when doing something simple calling the same function that many times isn’t ideal.

This is happening because:

* `AugmentedEntry::keys()` calls `$this->data->values()` which results in all computed callbacks being called
* `AbstractAugmented::get()` calls `$this->keys()` every time a [data method value is fetched](https://github.com/statamic/cms/blob/4.x/src/Data/AbstractAugmented.php#L59)

This results in all computed callbacks being called every time any data method value is fetched.

This PR aims to fix this by making the following changes:

* Adds a new `ContainsComputedData::computedFields()` method that just returns the field names
* Adds a new `HasOrigin::keys()` method that uses the new `computedFields()` method and only returns keys
* Uses the new `keys()` method in `AugmentedEntry::keys()`

In my testing this reduces the callback calls from 17 down to 2 (once for the URI check and once for the view rendering).

I’ve updated two tests to match the new behaviour, hopefully the changes I’ve made to those are correct.

Closes https://github.com/statamic/cms/issues/7931

### CODE REVIEW

**Comment by duncanmcclean** [comment]
This probably closes https://github.com/statamic/cms/issues/7931?

**Comment by jacksleight** [comment]
@duncanmcclean Ha, yup. Wish I'd seen that before I started, would have saved me some time. Oh well! 😅

**Comment by jasonvarga** [comment]
Brilliant.

**Comment by o1y** [comment]
Can confim, this PR is working. Thanks! 🚀

**Review by jasonvarga — APPROVED** [review]
Lovely again, thank you.

I renamed `computedFields` to `computedKeys` as we felt that was more consistent with the other `keys` methods. And added some tests.

**Comment by jesseleite** [comment]
Great PR! 🚀

**Pull request merged**
