### PR TITLE
Add collection/taxonomy names to stack selector

### PR DESCRIPTION
**Pull request by jacksleight**
This PR adds the collection or taxonomy names to the stack selector, to make it easier to distinguish entries in different collections that have identical or similar names:

Screenshot 2022-08-18 at 12 24 23

The property name "type" might be a bit generic, I'm not sure if there's a better term that would work for both collections and taxonomies?

Closes https://github.com/statamic/ideas/issues/819

### CODE REVIEW

**Comment by jackmcdade** [comment]
I love this btw – what if you showed "Collection" when it's a collection an "Taxonomy" when it's a taxonomy? I don't think it can ever be both, right?

**Comment by jacksleight** [comment]
Yeah good idea, added!

**Review by jackmcdade — APPROVED** [review]
This works great and I'm happy with the UI. I'll leave it to @jasonvarga to approve the code – namely the `ListedEntry` and `ListedTerm` classes.

**Comment by jacksleight** [comment]
Cool. I've definitely stopped fiddling with it now.

**Comment by jackmcdade** [comment]
Much more simplified. I like it 🤘  Thank you!

**Pull request merged**
