### PR TITLE
[4.x] UI improvements

### PR DESCRIPTION
**Pull request by jackmcdade**

### CODE REVIEW

**Comment by jacksleight** [comment]
Tiny thing, there's an extra border at the top of the sidebar when the preview/visit buttons aren't visible.

Screenshot 2023-02-22 at 10 35 51

**Comment by jackmcdade** [comment]
Yep I know — it isn’t all perfect and I haven’t messed with cards and tabs much because we’re redoing them all with the blueprint/tab update. Thanks though! On Feb 22, 2023, at 5:40 AM, Jack Sleight ***@***.***> wrote:﻿
Tiny thing, there's an extra border at the top of the sidebar when the preview/visit buttons aren't visible.

**Comment by jonassiewertsen** [comment]
Will this PR add UI improvements for lists with a lot of fields as described in this issue https://github.com/statamic/cms/issues/5034 ?

**Comment by jackmcdade** [comment]
Not this PR but maybe this one https://github.com/statamic/cms/pull/7589

**Pull request merged**
