### PR TITLE
Add grab cursor to sortable tags/select items

### PR DESCRIPTION
**Pull request by jacksleight**
As discussed in https://github.com/statamic/ideas/issues/844#issuecomment-1206465034

### CODE REVIEW

**Review by jasonvarga — CHANGES_REQUESTED** [review]
Can you change it the "grab" cursor? We use that everywhere else throughout the CP.

**Comment by jacksleight** [comment]
Oh whoops, done.

However, it doesn't actually work anymore, and I'm not really sure how best to fix it.

The `cursor-move` class has `!important` on it. The `cursor-grab` class doesn't. Because of that the `.v-select:not(.vs--single) .vs__selected` selector takes priority and that sets the cursor to `pointer`.  Adding `!important` to `cursor-grab` would fix it, but I dont want to break something else by doing that.

**Comment by jasonvarga** [comment]
I pushed up some changes. This whole PR is just one added class. Can you try it?

**Comment by jacksleight** [comment]
Looks good, only thing is that also applies to the `SelectFieldtype` component, which isn't sortable. But maybe it should be?

**Comment by jasonvarga** [comment]
Good catch, I made the selector more specific.

**Review by jasonvarga — APPROVED** [review]

**Comment by jacksleight** [comment]
Awesome.

I added `sortable-tag` and `sortable-rule` as the `TagsFieldtype` and validation `Builder` use those.

**Comment by jasonvarga** [comment]
That's weird. I think those components can just use sortable-item instead of sortable-tag/sortable-rule. I'll look into it and adjust.

**Review by jasonvarga — APPROVED** [review]
Yeah works fine. Maybe it was a misunderstanding what those class names did when those components were made.

**Pull request merged**
