### PR TITLE
Show delte action in a none multisite context correctly

### LINKED ISSUE #3174: Collection delete button is missing
## Bug Description
It's not possible to delete collection entries, the delete Button is missing.

## How to Reproduce
Selected entry in the overview, Button is not shown anymore.

## Extra Detail

image

## Environment

**Statamic version:** 3.0.40

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### PR DESCRIPTION
**Pull request by jonassiewertsen**
This closes #3174

### CODE REVIEW

**Review by jasonvarga — CHANGES_REQUESTED** [review]
Just change the original condition to `=== 1`

**Comment by jonassiewertsen** [comment]
This feels better @jasonvarga

**Review by jasonvarga — APPROVED** [review]

**Comment by jasonvarga** [comment]
Actually, this doesn't fix it. It makes the delete action not visible to anything else.

I can't recreate the original issue anyway. Let's continue there.

**Comment by jonassiewertsen** [comment]
To avoid any confusion, I did create a new issue for the problem in addon context https://github.com/statamic/cms/issues/3350 with a belonging PR to fix it.

**Pull request closed without merging**
