### PR TITLE
Fix users tag role and group parameters

### PR DESCRIPTION
**Pull request by jacksleight**
Fixes https://github.com/statamic/cms/issues/5584

The `{{ users }}` tag accepts `role` and `group` parameters that are supposed to filter the users, however if you use them you get an empty result. This PR fixes that and adds some tests.

To make this work I had to make a couple of tweaks to the role/group and builder classes:

1. `Role` and `UserGroup` now have a `__toString()` method that returns the handle
2. The `Builder::whereJson...` methods will now accept a `Collection` object

### CODE REVIEW

**Comment by jacksleight** [comment]
@duncanmcclean 

Looks like this and https://github.com/statamic/cms/pull/6817 both depend on the same thing, ability to query users by role/group.

I’m going to leave this draft for now, as although `JsonContains` can work I think there’s probably a better solution using the indexes, but querying those is different for files and Eloquent which complicates things a little.

https://github.com/statamic/cms/blob/ab89ea58e47d08301199618e202f5dfe85e46530/src/Auth/File/UserGroup.php#L12
https://github.com/statamic/cms/blob/ab89ea58e47d08301199618e202f5dfe85e46530/src/Auth/Eloquent/UserGroup.php#L12

For reference I had to do a similar thing in Memberbox and came up with [this](https://github.com/jacksleight/statamic-memberbox/blob/c4fa15fae822b703081d9d26cba1588fb560d636/src/Member.php#L17), but a cleaner solution would be nice.

I'm away next week but will pick this back up when I'm back.

**Comment by ryanmitchell** [comment]
This might help: https://github.com/statamic/cms/pull/6131

**Comment by jacksleight** [comment]
> I also think it overlaps and does some of what you’re doing.

Yeah I think it already solves it! 😄

**Comment by ryanmitchell** [comment]
Oh great. Maybe Jason will look back round to it soon, it’s been sitting a while.

**Pull request closed without merging**
