### PR TITLE
[5.x] Replicator "add set" button label option

### PR DESCRIPTION
**Pull request by godismyjudge95**
Closes:
- https://github.com/statamic/ideas/issues/1032
- https://github.com/statamic/ideas/issues/28

This PR adds a simple text config option to the replicator field.  The option is defaulted to empty so nothing about the default behavior changes.

It allows one to customize the labels like so:

image

image

### CODE REVIEW

**Comment by godismyjudge95** [comment]
Alternatively, I could change this so that it replaces the + icon entirely with the label.  Similar to how the grid "add row" button works

**Review by jackmcdade — APPROVED** [review]

**Comment by toxsick** [comment]
Somehow the small "plus" buttons that are shown on hover between replicator fields are gone in the latest release (v5.6.0):

Monosnap @Robert Stehr - Discord 2024-05-29 16-01-39

Could this be related to these changes somehow? I don't see any other replicator related changes in the release.

regards

**Comment by jasonvarga** [comment]
@toxsick Do you have any javascript errors?

**Comment by duncanmcclean** [comment]
@toxsick Can you try updating to v5.6.1? It included #10217, which should have fixed it.

**Comment by toxsick** [comment]
Hey guys, jeah as @jasonvarga suggested I was seeing js errors. Everything works again in v5.6.1 now. Thanks a lot!

**Pull request merged**
