### PR TITLE
Improve display of Grid and Replicator replicator preview

### PR DESCRIPTION
**Pull request by jacksleight**
The replicator preview for grid and replicator fields isn't very useful/user friendly:

Screenshot 2022-09-16 at 14 16 33

This PR implements a very simple alternative, just showing the count and field display name:

Screenshot 2022-09-16 at 14 16 44
Screenshot 2022-09-16 at 14 28 08

Not as fancy as maybe displaying values from a field in each row/set, which would be really nice, but I'm not sure if there's a simple way to do that.

## SIdenote

When working on this I noticed that there are `getReplicatorPreviewText()` methods in the List, Assets and Grid fieldtypes. The one in grid was empty. I implemented this with a `replicatorPreview` computed property as per the docs. I'm not really sure what `getReplicatorPreviewText()` is for or even where it's called from?

### CODE REVIEW

**Comment by jasonvarga** [comment]
> When working on this I noticed that there are getReplicatorPreviewText() methods in the List, Assets and Grid fieldtypes. 

This the method used in v2 that must have been never been removed/updated when we ported them.

**Comment by jasonvarga** [comment]
I tweaked this so it'll say `Field Name: 2 rows` or `Field Name: 2 sets`.

What do you think of that? @jacksleight @jackmcdade 

Just the count and field name looked a bit weird to me `2 Field Name`.

**Comment by jacksleight** [comment]
Yeah that's probably a bit more flexible. Just the field name works when it's a plural noun like `5 Images`, but would be weird for something like `3 Builder`. Whereas `Builder: 3 sets` works fine.

> Not from v2, but I guess from an early version of v3.

Shall I remove those?

**Comment by jasonvarga** [comment]
I got you. I'll merge this once the tests are done. 👍

**Review by jasonvarga — APPROVED** [review]

**Pull request merged**
