### PR TITLE
Fix Saving Dated Entry With Seconds

### PR DESCRIPTION
**Pull request by Buffalom**
I noticed that an entry in a dated collection with seconds enabled on the date field in the blueprint is saved without the seconds. The file's path will be formatted `Y-m-d-Hi` instead of `Y-m-d-His`

With these changes, an entry with time/seconds not enabled with be stored with the format `Y-m-d` and with time enabled it will be stored with the format `Y-m-d-His`, no matter whether seconds are enabled or not.

### CODE REVIEW

**Comment by Buffalom** [comment]
Apologies. I was too quick opening the PR. Some things are not yet working. I'll try fixing them and reopen/undraft the PR afterwards.

**Comment by jasonvarga** [comment]
If you merge 3.3 back into your branch it should be fixed. I'd do it myself but I don't have permission.

**Comment by jasonvarga** [comment]
My hand slipped and I clicked decline on your invitation instead of accept. 🤣 😭

**Comment by Buffalom** [comment]
😂 you should have another one in your inbox.

**Comment by Buffalom** [comment]
There still seems to be an issue where the slug becomes the date string, resulting in a file name like this: `2022-11-08-165435.2022-11-08-155435.md`

@reviewer Do you happen to have an idea on where this could be coming from? Mainly, I've noticed it in relation with clearing the cache.

**Comment by Buffalom** [comment]
> There still seems to be an issue where the slug becomes the date string, resulting in a file name like this: `2022-11-08-165435.2022-11-08-155435.md`

I dare say this issue is now fixed.

**Comment by jasonvarga** [comment]
Thanks for this. Sorry for the delay. Closing in favor of #7955 

- I don't have permission to push to this branch.
- I'm adjusting some date behavior which are breaking changes, so I'm targeting master/4.0.

**Comment by Buffalom** [comment]
Strange. You should be able to push.

image

But that's alright. Thank you for addressing it.

**Pull request closed without merging**
