### PR TITLE
Fix Asset validation when using S3

### LINKED ISSUE #4097: All files using `image` validation rule error with 'file does not exist' since v3.1.27 when using S3
## Bug Description

Since Statamic v3.1.27, all asset fields using the `image` validation rule and pointing to an S3 filesystem disk fail validation and can't be saved, the control panel shows a 'File does not exist' error for all files. The error originates from the `passes` method in the new `AssetRule`, because it tries to instantiate a Symfony file using a filesystem path that doesn't include the remote asset URL (e.g. `/profile-pic-2.jpeg`), but when using an S3 disk the file is of course not present locally.

https://github.com/statamic/cms/blob/e2b4fd90b50348464ad0b8576bffb76a9e27015a/src/Fieldtypes/Assets/AssetRule.php#L44-L50

## How to Reproduce

Verified in a fresh site locally:

1. Set up a new Statamic site.
1. Install `league/flysystem-aws-s3-v3` v1, may require downgrading guzzle.
1. Create a DigitalOcean 'Space' and a new filesystem disk in the Statamic app using the S3 driver and the Spaces credentials.
1. Edit the default Page blueprint to include an asset field using the `image` validation rule.
1. Go to Assets and upload anything.
1. Edit the homepage to choose an image.
1. Save the page, see a 'file does not exist' error for the file you just uploaded.

## Environment

**Statamic version:** 3.1.27 Pro

**Laravel version:** 8.53.1

**PHP version:** 8.0.9

**Install method (choose one):** Fresh install from `statamic/statamic`

### PR DESCRIPTION
**Pull request by arthurperton**
Fixes #4097 using custom validation rules again (reverting #3922) and adding a rule for `dimensions`, so #3820 stays fixed.

The logic for the new `dimensions` rule is heavily inspired by the code in `Illuminate\Validation\Concerns\ValidatesAttributes`, in fact the last three methods in `DimensionsRule` are copied from there.

### CODE REVIEW

**Review by jasonvarga — CHANGES_REQUESTED** [review]
Can you also please add support for the `min` and `max` rules?

**Comment by arthurperton** [comment]
I don’t understand which rules you are referring to.

**Comment by jasonvarga** [comment]
https://laravel.com/docs/8.x/validation#rule-min
https://laravel.com/docs/8.x/validation#rule-max

**Comment by bakerkretzmar** [comment]
@jasonvarga since this PR fixes a bug, can it be merged and the `min` and `max` rules added in another later PR? Happy to work on adding that, but it's not related to the issue this PR addresses.

**Comment by falko189** [comment]
What's preventing this from being merged? 😄

**Comment by TromPeter15** [comment]
still not working for me, unfortunately. getting the same error after setting "mimes:jpg,png" for image validation.

Screenshot 2021-11-10 at 15 46 10
ly

**Comment by jasonvarga** [comment]
Are you definitely on 3.2.21?

**Comment by TromPeter15** [comment]
Looks like this was my fault. After resetting the installation it works now.

Thanks!

**Pull request merged**
