### PR TITLE
[5.x] Feature/phone and mail link

### PR DESCRIPTION
**Pull request by j3ll3yfi5h**
Closes https://github.com/statamic/ideas/issues/1174

### CODE REVIEW

**Review by jasonvarga — CHANGES_REQUESTED** [review]
You've added handling for mailto links, but nothing for tel links.

When you pick phone in the option dropdown, there's no way for you to enter a value.

CleanShot 2024-06-21 at 11 37 20

When you choose the mail option, with every keystroke it adds mailto: to the start.

CleanShot 2024-06-21 at 11 34 38

Also, please disable your code formatter while you work on this so you don't end up committing unrelated changes. Thanks!

**Comment by jasonvarga** [comment]
I'm going to close this for now to keep things organized. If/when you're ready to continue just let us know and we can reopen this.

**Comment by j3ll3yfi5h** [comment]
FYI: I've been working with Erin on this at Flat Camp and just wanted to know if you generally welcome this PR or if it will be rejected anyway. That's why it was not fully finished.

Thanks for the feedback. As soon as I get time for it again, I'll let you know.

**Comment by jasonvarga** [comment]
This PR would be welcomed!

**Pull request closed without merging**
