### PR TITLE
Add markdown option to render form emails

### PR DESCRIPTION
**Pull request by caseydwyer**
Currently, if you set up a form submission email to use a markdown template, there's no way to indicate that you're using markdown. Through [the mailable's `build` method](https://github.com/statamic/cms/blob/fc4d56dfd426e0d4be42a243743b23450862cc08/src/Forms/Email.php#L30) (and then the `addViews` method), `view` is called instead of `markdown`, which throws an error:

`InvalidArgumentException
No hint path defined for [mail]. (View: C:\xampp\htdocs\statamic-site\resources\views\emails\form-submission.blade.php)`

This PR adds a toggle field in the CP, allowing a user to indicate the HTML template should be rendered using markdown. If the toggle is on, `addViews` will call the `markdown` method. Otherwise, it falls back to the standard `view` method.

This is (very loosely) related to [a small bug I stumbled onto with markdown mail failing to inline styles](https://github.com/statamic/cms/issues/2747#issuecomment-770422141), when there's a naming conflict on the `default.antlers.html` view file.

I realize this PR is 100% unsolicited, so no worries if you decide to scrap this. Seemed to be pretty low-hanging fruit, however, and I thought other folks might want to use markdown for their email notifications. Let me know if you'd like to see any changes, and thanks for your work on a great CMS! 👍

### CODE REVIEW

**Comment by caseydwyer** [comment]
@jasonvarga Sorry to bother you, I know you guys are busy! Is this something you would consider merging? Zero pressure—again, I realize this was completely unsolicited. We're ready to buy a master license & launch a handful of client sites that currently rely on this functionality...so just trying to figure out chances of merging vs. reworking emails to non-markdown. Thanks!

**Comment by jasonvarga** [comment]
Sorry for the delay here. I have no problem with this being in there. Just haven't had a chance to try it out.

**Comment by caseydwyer** [comment]
No worries at all—I know you guys are busy! Thanks for the quick response. 👍 We'll stay tuned; let me know if you need to see any changes!

**Comment by edalzell** [comment]
@caseydwyer you can always use the [patch](https://www.rias.be/blog/using-composer-patches) method to pull in not-yet-merged PRs.

I do this on a few sites w/ various PRs that are awaiting merging.

**Comment by caseydwyer** [comment]
@edalzell Thanks Erin, I'll give that a look! 👍

**Comment by jasonvarga** [comment]
Are you able to give me permission to edit your fork? Normally I'm able to push changes to people's PRs, but not yours.

**Comment by caseydwyer** [comment]
@jasonvarga Sorry about that! Took a bit of digging, but looks like it's [a known issue when forking to/from an org](https://github.com/isaacs/github/issues/1681) (as opposed to an individual account). Cleaned this up and resubmitted as #3414 .

**Comment by jasonvarga** [comment]
Nice detective work!

**Pull request closed without merging**
