### PR TITLE
Avoid 'illegal' store state mutations in Grid and AssetFieldtype

### LINKED ISSUE #4245: Unsetting an asset in a duplicated grid row unsets both the original and duplicated fields
## Bug Description

If you have a grid field with a child asset field, and you duplicate a row where the asset is set, and then unset the asset field by clicking on the trash can, both the original and duplicated fields are unset.

## How to Reproduce

1. Create a grid field with a child asset field
2. Add a row and set the asset
2. Duplicate the row
3. Unset the asset by clicking on the trash icon
4. Both rows's assets are unset

## Environment

Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 7.4.21

### PR DESCRIPTION
**Pull request by arthurperton**
Fixes #4245

See also dev notes in #4997 for some background info.

### CODE REVIEW

**Comment by jasonvarga** [comment]
This appears to also fix #4996

**Comment by jasonvarga** [comment]
#4774 appears to remain fixed too.

**Comment by jasonvarga** [comment]
Sorry, false alarm. #4996 still happens.

**Comment by arthurperton** [comment]
Yeah #4996 involves different components. A separate fix is coming up.

**Comment by jasonvarga** [comment]
Okay thanks, wasn't sure. In that case, this is good to merge. 👌

**Pull request merged**
