### PR TITLE
[5.x] Allow 'Statamic/Pro/Free' to be written using locale-specific characters

### PR DESCRIPTION
**Pull request by peimn**
In certain locales, it may be necessary to rewrite everything using local-specific characters.

### CODE REVIEW

**Comment by jasonvarga** [comment]
How would you write Statamic in Persian?

**Comment by peimn** [comment]
استتمیک

**Comment by jasonvarga** [comment]
What's the reaction about, @ebeauchamps ?

**Comment by ebeauchamps** [comment]
Well...I cannot see any character in Peimm's answer that he posted 3 days ago, that's all. Either in Safari or Chrome.

**Comment by jasonvarga** [comment]
They are on the right hand side of the comment because Persian is RTL.

CleanShot 2024-05-13 at 11 23 45

**Pull request merged**
