### PR TITLE
[5.x] Static warm: recheck whether page is cached for queued requests

### PR DESCRIPTION
**Pull request by arthurperton**
When using both the `--queue` and `--uncached` parameters:

By the time a queued job gets executed, the page was possibly already cached in the meantime. The dedicated `StaticWarmUncachedJob` checks again if the page is cached, and if so, it won't send the request.

### CODE REVIEW

**Review by jasonvarga — APPROVED** [review]

**Comment by jasonvarga** [comment]
Weird test failures. I thought it was one of those random failures and rerunning would solve it. 🤔

**Comment by arthurperton** [comment]
I was thinking the same thing. Weird. FWIW I ran the tests locally and they all succeeded.

**Comment by jasonvarga** [comment]
I'll check them out. The PR looks good though.

**Comment by jasonvarga** [comment]
It's not you. 😄 #11275

**Pull request merged**
