### PR TITLE
[4.x] Uniform image validation

### PR DESCRIPTION
**Pull request by royduin**
Follow-up on https://github.com/statamic/cms/pull/9284 to have 1 source of truth.

### CODE REVIEW

**Comment by duncanmcclean** [comment]
There seems to be some failing tests after your change. Would you be able to fix them?

**Review by duncanmcclean — CHANGES_REQUESTED** [review]
The changes seem to be causing some of the tests to fail. Would you be able to address the failures?

**Comment by royduin** [comment]
I'll look into it soon, will be continued.

**Comment by royduin** [comment]
Thanks! 🚀

**Comment by jasonvarga** [comment]
This is being reverted as it doesn't appear to have any effect after all.

Once 4.46.0 is released, please see if you are still running into your issue (pretty sure you will) and feel free to open a new PR.

**Pull request merged**
