### PR TITLE
[4.x] Use real Facade for Cascade

### PR DESCRIPTION
**Pull request by edalzell**
On Discord, someone needed to override something in Cascade, but because it was using a real-time facade that wasn't possible.

### CODE REVIEW

**Comment by edalzell** [comment]
Jason, I didn't add type hints to the Cascade methods cuz I didn't want to make this PR bigger, but I could if you'd like.

**Comment by jasonvarga** [comment]
What typehints where?

**Comment by edalzell** [comment]
> What typehints where?

In `View\Cascade`.

**Comment by edalzell** [comment]
It doesn't really.  I didn't understand you could do that when using real-time facades. So this PR is only to stop IDE squiggles then I guess.

Feel free to close.

**Pull request merged**
