### PR TITLE
Use the cp.date_format to format the date field.

### LINKED ISSUE #1310: date_format ignored on cp listings
The date fields are not rendered in the collection table correctly. 
```
    'date_format' => 'd.n.Y',
```
"Beginn" is the default date field from the filename. "Ende" is an added field.
image

I know, there is a format setting inside the date field. But if I change this, I'm getting an error.
So I don't know, if this field is for backend or frontend.

### PR DESCRIPTION
**Pull request by jackmcdade**
This fixes #1310.

### CODE REVIEW

**Comment by jasonvarga** [comment]
Is this fixing #3265 ?

**Comment by jackmcdade** [comment]
Ah yes, that one too 👍

**Review by jasonvarga — CHANGES_REQUESTED** [review]
The `format` config option controls how the data is saved in v3. (e.g. if people want to put timestamps in their yaml)

In v2 it controlled how it was displayed in the cp.

I think we need to pass the date format in `cp.php` (converted from php to moment) into the fieldtype, instead of the `format` of the date field.

I'm happy to pick this up.

Do you know what the `formats` prop does? I can't see any reference to it in the vue-calendar code. Can't work out what it does or what removing `'L'` did.

**Comment by jasonvarga** [comment]
Closing in favor of #3730

**Pull request closed without merging**
