### PR TITLE
Update route bindings checks to handle empty cp route config

### PR DESCRIPTION
**Pull request by ryanmitchell**
Update checker functions to handle empty cp route config

Fixes: #6148

### CODE REVIEW

**Comment by jasonvarga** [comment]
Good find 🕵️

**Comment by jasonvarga** [comment]
Although this doesn't seem to make a difference. 🤔

**Comment by ryanmitchell** [comment]
Hmm leave it with me and I’ll figure it out

**Comment by jasonvarga** [comment]
I've got it. I'll push it up.

**Comment by ryanmitchell** [comment]
Thank you.

**Pull request merged**
