### PR TITLE
'Add Set' button at the top of the Replicator-Fieldtype

### PR DESCRIPTION
**Pull request by wiebkevogel**
We would also like to avoid drag and drop when we want to add a set at the first position.

Closes https://github.com/statamic/ideas/issues/720

### CODE REVIEW

**Comment by jackmcdade** [comment]
Works great, thank you!

**Comment by robdekort** [comment]
There's a little bit of a spacing issue when your replicator has instructions set. 
Screenshot 2022-09-09 at 13 10 19

**Comment by jasonvarga** [comment]
Please open a new issue. Commenting on closed PRs will often get missed.

(Yes, I see the irony in this comment 😄)

**Comment by robdekort** [comment]
🤣

**Pull request merged**
