### PR TITLE
Check for orphaned tree files in stache:doctor command

### PR DESCRIPTION
**Pull request by arthurperton**
Helps with detecting the cause of #3478.

PR's #3889 and #3901 help to prevent that issue, this PR is for when the damage is already done.

### CODE REVIEW

**Comment by jasonvarga** [comment]
Unless I'm mistaken, having a tree file without a corresponding collection doesn't hurt anything.

It looks more like you get an error when there is a tree file for a collection that exists, when the tree probably shouldn't exist.

Your other PR addresses this. 👍

**Comment by arthurperton** [comment]
Yeah definitely a mistake here, a ghost tree file gets you quite stuck. You won't be able to [warm or refresh the stache](https://github.com/statamic/cms/issues/3478#issuecomment-827458839) again until you find the problem and remove the file. Which is hard when you don't know what you're looking for. Speaking from experience here 😅 

Just drop a `.yaml` file with an empty structure `{ }` in `/content/tree/collections` for a collection that is not orderable. Then try to warm the stache.

**Comment by arthurperton** [comment]
PS It was actually a bit of a challenge to write this code in a way that wouldn’t trigger the error.

**Comment by jasonvarga** [comment]
I still get an error the first time I run the command.

If this is just to track down the cause of an error because there's a file that exists when it shouldn't... I don't think this is really necessary. The other PR where you fix the orphan files is the fix. The problem will just go away after that.

Or, we could additionally make the store ignore any trees that don't have corresponding collections.

**Comment by edalzell** [comment]
> Or, we could additionally make the store ignore any trees that don't have corresponding collections.

I've run into this error as well. It's tricky to see the issue...this would be great!

**Comment by jasonvarga** [comment]
I don't think this command is needed. Once #3889 is done, the problem will eventually die out.

**Comment by arthurperton** [comment]
> Or, we could additionally make the store ignore any trees that don't have corresponding collections.

That would be great. Working on a PR for it. No need for the doctor to check then, I agree.

**Pull request closed without merging**
