### PR TITLE
Entries fieldtype: filter out unpublished entries when augmenting

### LINKED ISSUE #2721: Entries field shows unpublished items in frontend
## Bug Description
When you use an entries field to select content and loop over it in Antlers it renders unpublished entries. I feel unpublished entries should never show unless someone explicitly asks for drafts. 

## How to Reproduce

1. Add entries to a collection. Make sure one of them is unpublished
2. Add an entries field and selected those entries.
3. Loop through the entries in Antlers.
4. Both will show up.

## Extra Detail
Download an [example project](https://www.icloud.com/iclouddrive/0KnXt00zTJ2bQydgHPbbTkKCw#statamic-issue-2721) here and visit the front page. A workaround is to manually test the published status using `{{ if published }}`.
Screenshot 2020-10-23 at 14 51 38
Screenshot 2020-10-23 at 14 51 44
Screenshot 2020-10-23 at 14 51 46

## Environment
Statamic 3.0.20 Pro
Laravel 8.11.2
PHP 7.4.10
No addons installed

**Install method (choose one):**
- Starter kit install from `studio1902/statamic-peak`

### PR DESCRIPTION
**Pull request by arthurperton**
Fixes #2721.

### CODE REVIEW

**Comment by duncanmcclean** [comment]
I wonder if this change could introduce a breaking change for users who expect unpublished entries to be in there?

**Comment by duncanmcclean** [comment]
@arthurperton Do you know if this also fixes #3539?

**Comment by arthurperton** [comment]
> @arthurperton Do you know if this also fixes #3539?

No! I totally didn’t expect that after seeing the code. Did you try it out?

**Comment by arthurperton** [comment]
Ah sorry I read your comment the wrong way. No this won’t solve #3539, that is a different and slightly more difficult one.
I’ll have a go at it if this one gets accepted, as I agree it is quite a change in behavior.

**Comment by arthurperton** [comment]
@jasonvarga Do you consider this a breaking change or just a bug fix?

**Review by jasonvarga — APPROVED** [review]
Sorry for the delay.

I'd consider this a bug fix. We shouldn't be showing the published entries. I doubt many, if any, would _want_ to see drafts on the front-end.

I think ideally, instead of augmenting to a collection of actual entries, maybe it could augment to a query builder instance. Then on the front-end you could add where clauses to it.

```
{{ my_entries_field status:is="draft" }}
 ...
{{ /my_entries_field }}
``` 

But that's getting complicated. We can work that out later. Could be a similar solution for #3539

**Comment by arthurperton** [comment]
Good! I'll look into #3539 again now that I know your stand on this 👍🏻

**Comment by mikemartin** [comment]
Hey guys,
This seems to have been a breaking change. 

I have an entries fieldtype with published and unpublished entries, and augmentation now removes the unpublished entries. There seems to be no possible way to include them at the moment. I've rolled back to 3.1.14 in the meantime but hoping the above "status" solution gets implemented soon.

**Comment by helloDanuk** [comment]
I do have a similar case as @mikemartin described. On one page I loop through all entries and only the published should be showed. So far so good.

On an another page I have an entries fieldtype (published and unpublished entries), and I would like to show the name/title of the entries, but only the published ones should have a link. 

The way I see it, I can currently only create this with an additional toggle field or similar?
This also seems logical to me, but introduces an additional complexity. Two toggle fields: Published/Unpublished and shown/unshowed.

**Comment by helloDanuk** [comment]
Bildschirmfoto 2021-06-23 um 10 47 08

In addition, the collection overview does not show whether an unpublished entry is attached in the entry field type. In this example "Test 2" also have an entry attached, but it is an unpublished one.

I probably tried this solution, because on the entry field type there is no hint, if the entry is published or not. Therefore, I thought that I could use the data under all conditions.

Bildschirmfoto 2021-06-23 um 10 57 52

**Pull request merged**
