### PR TITLE
Brand new `de-CH` translation

### PR DESCRIPTION
**Pull request by helloDanuk**
What started as an project to reflect some minor differences in `de-CH` ended in a complete overhaul of the `de` translation itself. We had a discussion in the german Discord channel. We agree that `de` and `de-CH` should be the same, besides the differences in grammar. The feedback in general was positive, no opposition, so here we are:

This PR contains the `de-CH` version only with all additions to the translation files Jack made in the last couple of days. Great work! I propose to finish it first, before we duplicate it back to a `de` version and change the grammar (mostly add the ß character). We then do not need to make all changes twice. On the other hand it would be great to get a overhauled `de` version out to the wild soon. So that everybody can notice the changes.

There are a few toughts about the translation [here](https://github.com/helloDanuk/v3-translation) (in german): 

As for issue #1640 (Update 18.4.2020: I cleaned up `messages.php`, see comment below.): ~~I copied all these lines manually to the new `de-CH` translation in this PR. The messages.php contains a match of both (all english textfragments and the three additions in the generated file). This needs to be sorted out in one of the next beta-versions.~~

### CODE REVIEW

**Comment by helloDanuk** [comment]
I have improved the translation in several places and updated it to beta.26. Further I cleaned up `messages.php` and deleted some leftovers from an earlier beta version. As far as I tested, they are not used anymore. Although I couldn't test multisite. Further I have add some keys manually ('Create a…'-titles in *.json file and the last two lines in fieldtypes.php).

Some missing translations are marked in #1697 and there is a bug(?) with plural form #1695. Apart from that the translated CP looks really good now! This should help non-native English-speaking editors to feel more comfortable in the CP.

I am not sure, if I should copy the new translation to the `de` version now? Some feedback from german users would be great.

**Comment by Konafets** [comment]
@helloDanuk I noticed that the german labels are sometimes a bit cumbersome. I will copy your swiss-german translations to german and will adjust where I think it makes sense.

Additionally I startet adding support for some untranslatable strings in the VueJS files from #1697

**Comment by helloDanuk** [comment]
I just checked with beta.32: there are no new or changed translation strings. The PR should still be up to date.

**Comment by jasonvarga** [comment]
Thank you! I will be reviewing all the translation PRs soon.

**Comment by helloDanuk** [comment]
Could test multi-site in the CP and then unified some wordings.

**Comment by jasonvarga** [comment]
Does this still need to be merged if #1904 is merged?

**Comment by helloDanuk** [comment]
I agree with the comments made in #1904. Thanks for merging!

**Pull request merged**
