### PR TITLE
Glide tag: handle missing files gracefully

### LINKED ISSUE #2791: Glide Tag Pair causes page to crash if image is missing from disk
## Bug Description
I like to use the [Glide Tag Pair](https://statamic.dev/tags/glide#tag-pair) to access variables like `{{ height}}`. If an image is missing from the disk, the glide tag will log an error like:
`League\\Glide\\Filesystem\\FileNotFoundException(code: 0): Could not find the image`.

This causes the entire page to show a 500 error. It would be better to let the page load and just log an error.

## How to Reproduce
1. Use the glide tag pair
2. Delete an image from the disk (outside of Statamic)
3. Load the page.

## Extra Detail

Here's the full error

```
[previous exception] [object] (League\\Glide\\Filesystem\\FileNotFoundException(code: 0): Could not find the image `member-projects/img_20200308_225722_526.jpg`. at /home/vagrant/code/mysite/vendor/league/glide/src/Server.php:499)
[stacktrace]
#0 /home/vagrant/code/mysite/vendor/statamic/cms/src/Imaging/ImageGenerator.php(146): League\\Glide\\Server->makeImage()
#1 /home/vagrant/code/mysite/vendor/statamic/cms/src/Imaging/ImageGenerator.php(91): Statamic\\Imaging\\ImageGenerator->generate()
#2 /home/vagrant/code/mysite/vendor/statamic/cms/src/Tags/Glide.php(129): Statamic\\Imaging\\ImageGenerator->generateByUrl()
#3 /home/vagrant/code/mysite/vendor/statamic/cms/src/Tags/Glide.php(102): Statamic\\Tags\\Glide->generateImage()
#4 [internal function]: Statamic\\Tags\\Glide->Statamic\\Tags\\{closure}()
#5 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map()
#6 /home/vagrant/code/mysite/vendor/statamic/cms/src/Tags/Glide.php(113): Illuminate\\Support\\Collection->map()
#7 /home/vagrant/code/mysite/vendor/statamic/cms/src/Tags/Glide.php(33): Statamic\\Tags\\Glide->generate()
#8 [internal function]: Statamic\\Tags\\Glide->__call()
#9 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Engine.php(152): call_user_func()
#10 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag()
#11 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(575): call_user_func_array()
#12 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(340): Statamic\\View\\Antlers\\Parser->parseCallbackTags()
#13 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(287): Statamic\\View\\Antlers\\Parser->parseLoopInstance()
#14 [internal function]: Statamic\\View\\Antlers\\Parser->Statamic\\View\\Antlers\\{closure}()
#15 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map()
#16 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(288): Illuminate\\Support\\Collection->map()
#17 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(222): Statamic\\View\\Antlers\\Parser->parseLoopVariables()
#18 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(174): Statamic\\View\\Antlers\\Parser->parseVariables()
#19 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(131): Statamic\\View\\Antlers\\Parser->parse()
#20 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Engine.php(89): Statamic\\View\\Antlers\\Parser->parseView()
#21 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get()
#22 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#23 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#24 /home/vagrant/code/mysite/vendor/statamic/cms/src/Tags/Partial.php(20): Illuminate\\View\\View->render()
#25 /home/vagrant/code/mysite/vendor/statamic/cms/src/Tags/Tags.php(132): Statamic\\Tags\\Partial->wildcard()
#26 [internal function]: Statamic\\Tags\\Tags->__call()
#27 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Engine.php(152): call_user_func()
#28 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag()
#29 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(575): call_user_func_array()
#30 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(340): Statamic\\View\\Antlers\\Parser->parseCallbackTags()
#31 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(287): Statamic\\View\\Antlers\\Parser->parseLoopInstance()
#32 [internal function]: Statamic\\View\\Antlers\\Parser->Statamic\\View\\Antlers\\{closure}()
#33 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map()
#34 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(288): Illuminate\\Support\\Collection->map()
#35 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(222): Statamic\\View\\Antlers\\Parser->parseLoopVariables()
#36 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(174): Statamic\\View\\Antlers\\Parser->parseVariables()
#37 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Parser.php(131): Statamic\\View\\Antlers\\Parser->parse()
#38 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/Antlers/Engine.php(89): Statamic\\View\\Antlers\\Parser->parseView()
#39 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get()
#40 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#41 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#42 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/View.php(74): Illuminate\\View\\View->render()
#43 /home/vagrant/code/mysite/vendor/statamic/cms/src/View/View.php(104): Statamic\\View\\View->render()
#44 /home/vagrant/code/mysite/vendor/symfony/http-foundation/Response.php(412): Statamic\\View\\View->__toString()
#45 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Http/Response.php(65): Symfony\\Component\\HttpFoundation\\Response->setContent()
#46 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Http/Response.php(34): Illuminate\\Http\\Response->setContent()
#47 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Routing/Router.php(759): Illuminate\\Http\\Response->__construct()
#48 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Routing/Router.php(731): Illuminate\\Routing\\Router::toResponse()
#49 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Router->prepareResponse()
#50 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#51 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#53 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#55 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#57 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#59 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#60 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#62 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#64 /home/vagrant/code/mysite/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\StaticCaching\\Middleware\\Retrieve->handle()
#66 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#68 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#69 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#70 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#71 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#72 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#73 /home/vagrant/code/mysite/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#75 /home/vagrant/code/mysite/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#77 /home/vagrant/code/mysite/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#79 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#81 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#82 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#83 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#84 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#85 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#86 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#87 /home/vagrant/code/mysite/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#88 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#89 /home/vagrant/code/mysite/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#90 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#91 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#92 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#93 /home/vagrant/code/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#94 /home/vagrant/code/mysite/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#95 {main}
"} 
```

## Environment

**Statamic version:** 3.0.23

**PHP version:** 7.4

**Disk location:** S3 bucket

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### PR DESCRIPTION
**Pull request by arthurperton**
Fixes #2791.

### CODE REVIEW

**Review by jasonvarga — CHANGES_REQUESTED** [review]
This doesn't seem to prevent any errors.

Before this PR, it would fail inside `ImageGenerator@validateImage` when it reads the mime type. It does the same thing after.

I thought maybe you intended for #3450 to be required, so I merged it.
That throws a Flysystem exception, but you're catching a Glide one.

Even if it was caught correctly and `null` was returned, it would fail on line 106 where it tries to getimagesize of an invalid path.

Maybe I'm missing something?

**Comment by arthurperton** [comment]
I'll have to look into that.

**Comment by jasonvarga** [comment]
Closing this. Feel free to open a new one. Thanks!

**Comment by jtomek** [comment]
getimagesize is problematic if I'd like to store the cached images on s3



```php
<?php 

namespace App\GlideS3Server

// ...

public function create()
{
    return ServerFactory::create([
        'source'   => base_path(), // this gets overriden on the fly by the image generator
        'cache'    => Storage::disk('s3_cache')->getDriver(),
        'response' => new LaravelResponseFactory(app('request')),
        'driver'   => Config::get('statamic.assets.image_manipulation.driver'),
        'cache_with_file_extensions' => true,
        'presets' => Image::manipulationPresets(),
    ]);
}

// ...
```

**Pull request closed without merging**
