### PR TITLE
Fix asset thumbnails/file-icons in entry listings and assets field

### PR DESCRIPTION
**Pull request by jacksleight**
Fixes https://github.com/statamic/cms/issues/7192
Fixes https://github.com/statamic/cms/issues/7024

This PR fixes a couple of issues with asset thumbnails/file-icons.

## Thumbnail size in entry listings (https://github.com/statamic/cms/issues/7192)

The size has been changed from `thumbnail` to `small`, as `thumbnail` seems to return the full-size image.

## Asset thumbnails not showing in entry listings in Safari (https://github.com/statamic/cms/issues/7024)

I've found various mentions of Safari bugs around flexbox and children with percentage based max-height values, and that certainly seems to be what's causing this. Since both of the places where `<asset-thumbnail>` is used set `h-8` on the parent, changing the `max-h-full` to `max-h-8` doesn't affect the layout but does avoid the Safari bug(s).

I also removed the duplicate `rounded` class.

## Asset thumbnail file icon widths in entry listings

Icons were set to `w-full`, but that's `3xs` in an entry listing, leaving empty space either side:

Screenshot 2022-12-10 at 15 34 21

Giving them `w-8` instead fixes it:

Screenshot 2022-12-10 at 15 34 12

## File icons in asset list fields in Safari

Stumbled on another Safari-only bug, the file icons are missing in asset list fields:

Screenshot 2022-12-10 at 15 38 46

Giving them dimensions just like the thumbnails have fixed it:

Screenshot 2022-12-10 at 15 39 03

### CODE REVIEW

**Comment by robdekort** [comment]
Oh Wow! I only just now noticed it. Seems you don't get a notification when someone links a PR. Thanks in advance for this Jack. ❤️

**Comment by jacksleight** [comment]
> Oh Wow! I only just now noticed it. Seems you don't get a notification when someone links a PR. Thanks in advance for this Jack. ❤️

No worries, I'd run into a couple of these as well, had been thinking of taking a look. 👍

**Comment by jackmcdade** [comment]
Looks great! Thank you!

**Comment by robdekort** [comment]
Oh my. I just installed the latest update containing this PR and it works brilliantly. Images everywhere and the CP is a lot snappier as well. I'm very grateful!

**Comment by Sybrenb** [comment]
Is it possible to customize the display size of the thumbnails?

**Pull request merged**
