### PR TITLE
Updating French and Italian after commit d697084

### PR DESCRIPTION
**Pull request by ebeauchamps**
updating messages.php

### CODE REVIEW

**Comment by jackmcdade** [comment]
Hey there, would love to merge this but there are a few keys that changed and a couple of other small string changes. If you're up to catching it up to date we'll get it merged on it!

**Comment by ebeauchamps** [comment]
I'll check ASAP

**Comment by ebeauchamps** [comment]
This is OK prior to the beta9 release. I now have to check for additional strings and I guess It would be better to wait for it, wouldn't it?

**Comment by ebeauchamps** [comment]
Still WIP. More stuff to check after commit 87dbc87e

**Comment by ebeauchamps** [comment]
All set!

**Pull request merged**
