### PR TITLE
Multisite: fix (re)syncing fields in localized entries

### LINKED ISSUE #6874: Multisite: syncing a desynced field does not work
### Bug description

**What happened**
When you sync a field via the control panel, the broken link icon shortly flashes to a whole link icon, then back to the broken link icon. So the field still appears desynced. The value of the field has been replaced by the origin value. This value is saved to the content file for the localization. So effectively it is still desynced.

https://user-images.githubusercontent.com/4067531/195560483-e7282da4-9b17-4e63-8613-cbc19acdb2bd.mov

**Expectation**
When you press the sync button, it should
1. Show the origin value in the field
2. Show a whole (i.e. not broken) link icon.
3. In the content file for the localization, no value should be present for the synced field.

### How to reproduce

1. Setup multisite
2. Have a localizable field
3. Desync the field and save it.
4. Sync the field again

### Logs

_No response_

### Environment

```yaml
Statamic 3.3.43 Pro
Laravel 8.83.25
PHP 8.1.8
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

_No response_

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by arthurperton**
Fixes #6874.

### CODE REVIEW

**Comment by arthurperton** [comment]
I made this a draft after reading [your comment on the issue](https://github.com/statamic/cms/issues/6874#issuecomment-1277994499), I want to make sure this fix works well with fields like text and textarea (that don't have the issue).

**Comment by jasonvarga** [comment]
Your fix still seems to work.

**Comment by arthurperton** [comment]
Yes. For these fields like text and texarea, `desyncField` is not called though and `this.desyncField` is never set to `false`. That's a bug.

**Comment by arthurperton** [comment]
I am closing this PR now; this fix will be incorporated in a combined PR to fix several related issues regarding multisite entries.

**Pull request closed without merging**
