### PR TITLE
[5.x] Fix login issues

### PR DESCRIPTION
**Pull request by peimn**
Forgot password card missed to be wrapped, and dark colors were applied to the texts

image

### CODE REVIEW

**Comment by jackmcdade** [comment]
@peimn Already pushed up the change – from here on out you can just open Issues for the Dark Mode instead of sending in PRs, we're super on top of Dark Mode stuff right now, thanks!

**Comment by peimn** [comment]
@jackmcdade I'm wondering why you closed this PR without merging it, even though it addresses some of the issues that I believe you will handle in the same way. However, that's alright. Please proceed as you see fit.

**Comment by jackmcdade** [comment]
I closed it because I already made all the same changes on other branches. I really do appreciate it though!

**Comment by peimn** [comment]
I understand. You're welcome.

**Comment by jasonvarga** [comment]
See #10151

**Comment by peimn** [comment]
Yeah I saw it. 
I will open issues for all the dark mode-related styles.

**Comment by peimn** [comment]
@jackmcdade What about the addons?

**Comment by jackmcdade** [comment]
Working on SEO Pro now.

**Comment by peimn** [comment]
Exactly, I've done some work on it and plan to send it later. :D

**Pull request closed without merging**
