### PR TITLE
[4.x] Set icon additions

### PR DESCRIPTION
**Pull request by mikemartin**
All icons from Streamline Plump Solid using currentColor and passed through SVGOMG.
Screenshot 2023-08-25 at 11 54 07 pm

### CODE REVIEW

**Comment by jackmcdade** [comment]
Unfortunately we're not allowed to use all the licenses, we have a rough 150-200 icon cap as per our license agreement with them. I wish I could accept the PR, but I can't.

**Comment by mikemartin** [comment]
@jackmcdade Thanks Jack. I was thinking that might be an issue. Any plans to add a config to specify the icon folder for replicator sets?

**Comment by jackmcdade** [comment]
Don't we have that already?

**Comment by mikemartin** [comment]
Added a FR here https://github.com/statamic/ideas/issues/1039

**Pull request closed without merging**
