### PR TITLE
Small human updates to French

### PR DESCRIPTION
**Pull request by ebeauchamps**

### CODE REVIEW

**Comment by studio1902** [comment]
Hey @ebeauchamps how did you fetch those new strings. The translator doesn't bring in any new ones in my case (beta 34).

**Comment by ebeauchamps** [comment]
I had to check my file against the one provided in vendor/statamic/resources/lang/

**Comment by studio1902** [comment]
Manual labour! Great job. Sorry for bothering you. Jason just explained he already ran Google Translate so that's why the CLI didn't gave me any new strings. Checked them by hand and PR'd them a moment ago. I think we're there now with Dutch.

**Comment by ebeauchamps** [comment]
Indeed, I think I had a problem with my workflow this time. What I did first was:
a) download the zipped statamic/cms repo fresh after Beta34 was tagged
b) unzip it and replace all files in a repo with the translator php file
c) run php translator generate fr
And as the translator has already be ruined, I did not detect the new strings that were not-so-well translated by Google Translate. 
The I had to check all my files against a fresh install a Beta34. Still checking.

**Comment by studio1902** [comment]
Jason provided me with this link to help me out spot the differences. Hope it's helpful for you too! https://github.com/statamic/cms/compare/v3.0.0-beta.33...v3.0.0-beta.34

**Comment by ebeauchamps** [comment]
ah yes...just the way we are doing it in another cms...clever!

**Pull request merged**
