### PR TITLE
use `createFromTimestamp()` instead when `$date` is timestamp.

### PR DESCRIPTION
**Pull request by riseno**

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Hey! Does this fix any open issues or is it just something you've noticed?

**Comment by riseno** [comment]
@duncanmcclean  i just discovered when working multi site.

**Comment by duncanmcclean** [comment]
> @duncanmcclean i just discovered when working multi site.

Would you be able to provide a bit more information about the issue you were having? Just so whoever reviews this pull request knows what the issue was. 😄

**Comment by riseno** [comment]
> > @duncanmcclean i just discovered when working multi site.
> 
> Would you be able to provide a bit more information about the issue you were running into? Just so whoever reviews this pull request knows what the issue was. 😄

it seems that it isn't a good time to open this PR, those tests are failing. 😢 nvm, i reopen it later with detail info.

**Pull request closed without merging**
