### PR TITLE
[4.x] Improve collection Stache watcher performance

### PR DESCRIPTION
**Pull request by JohnathonKoster**
This PR optimizes the Stache watcher by limiting the scope of the Collection Stache watcher to just the immediate files within the `content/collections` directory. The changes allow for any store to disable recursive file retrieval (currently only enabled on the collection store).

From testing, the existing behavior will load *all* file paths within the `content/` directory when checking for Collection changes, and then load them all again for each individual collection that is checked.

The following #'s are not super rigorous, and are just general observations from viewing a single article page in the browser (site based on Cool Writings). All numbers are after warming the Stache separately before running the site.

Baseline numbers without any extra collection entries: bounce between 750ms to 1.3s

| Additional Entries | Before TTFB | After TTFB |
|---|---|---|
| 15,109 | ~4.1s | ~1.9s |

These numbers remain fairly consistent event when increasing the number of file based entries to 20K+. Site is running on Windows via. WSL without any environment optimizations and using `php artisan serve`.

**Note 1**: While working through this, I had the thought that it would be possible to disable the Stache watcher for certain collections, and can look into that if there is interest (i.e., disable it on very large collections with infrequent updates, but keep it enabled for smaller ones, etc.)

**Note 2**: The back/forth changes related to removing the string operations inside the collection store were to preserve any existing behavior that relies purely on the store's `getFilterItem` method. Removing these would improve things very, *very* slightly, but would definitely break behavior at this time (hooray existing test coverage).

### CODE REVIEW

**Comment by jasonvarga** [comment]
I'm also testing on the Cool Writings /articles listing. It paginates to the first 10 items.
I have 20k entries. The page with the Stache watcher enabled loads at about ~1.7s. With this PR it's about ~1.2s.

With the Stache watcher disabled there's no difference - which is expected.

I think the drastic difference is due to you using Windows. (I'm sorry!)

Still, small code change results in a not-nothing performance increase. 👍

**Review by jasonvarga — APPROVED** [review]

**Comment by aerni** [comment]
This PR broke the custom stache store in my [Advanced SEO](https://github.com/aerni/statamic-advanced-seo) addon. I get unlimited duplicate ID's. Regenerating just adds another duplicate. Do I have to change something on my side or is this a bug or breaking change?

CleanShot 2024-02-01 at 12 11 22@2x

**Comment by jasonvarga** [comment]
I'll revert it. Shouldn't have been a breaking change. Sorry about that.

**Comment by aerni** [comment]
Weirdly enough, this PR completely crashes my staging site but works locally.

**Error:**
CleanShot 2024-02-02 at 16 53 07@2x

**Stack Trace:**
```log
[2024-02-02 22:53:45] local.ERROR: Too few arguments to function Illuminate\Foundation\Application::make(), 0 passed in /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/Data/SeoDefaultSet.php on line 213 and at least 1 expected {"userId":"fd0a1608-d863-46dd-91c4-40e82e2dac65","exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function Illuminate\\Foundation\\Application::make(), 0 passed in /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/Data/SeoDefaultSet.php on line 213 and at least 1 expected at /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:938)
[stacktrace]
#0 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/Data/SeoDefaultSet.php(213): Illuminate\\Foundation\\Application->make()
#1 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/Data/SeoVariables.php(200): Aerni\\AdvancedSeo\\Data\\SeoDefaultSet->blueprint()
#2 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/Data/SeoVariables.php(133): Aerni\\AdvancedSeo\\Data\\SeoVariables->blueprint()
#3 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/Data/SeoVariables.php(142): Aerni\\AdvancedSeo\\Data\\SeoVariables->defaultData()
#4 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/Data/SeoDefaultSet.php(152): Aerni\\AdvancedSeo\\Data\\SeoVariables->withDefaultData()
#5 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): Aerni\\AdvancedSeo\\Data\\SeoDefaultSet->Aerni\\AdvancedSeo\\Data\\{closure}()
#6 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/Data/SeoDefaultSet.php(152): Illuminate\\Support\\Collection->each()
#7 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/Actions/GetAugmentedDefaults.php(14): Aerni\\AdvancedSeo\\Data\\SeoDefaultSet->ensureLocalizations()
#8 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/Actions/GetSiteDefaults.php(26): Aerni\\AdvancedSeo\\Actions\\GetAugmentedDefaults::handle()
#9 [internal function]: Aerni\\AdvancedSeo\\Actions\\GetSiteDefaults::Aerni\\AdvancedSeo\\Actions\\{closure}()
#10 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map()
#11 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\\Support\\Arr::map()
#12 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(404): Illuminate\\Support\\Collection->map()
#13 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/Actions/GetSiteDefaults.php(26): Illuminate\\Support\\Collection->flatMap()
#14 /home/ploi/go-unity.org/vendor/spatie/blink/src/Blink.php(306): Aerni\\AdvancedSeo\\Actions\\GetSiteDefaults::Aerni\\AdvancedSeo\\Actions\\{closure}()
#15 /home/ploi/go-unity.org/vendor/statamic/cms/src/Support/Blink.php(18): Spatie\\Blink\\Blink->once()
#16 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Statamic\\Support\\Blink->__call()
#17 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/Actions/GetSiteDefaults.php(24): Illuminate\\Support\\Facades\\Facade::__callStatic()
#18 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/View/BaseCascade.php(38): Aerni\\AdvancedSeo\\Actions\\GetSiteDefaults::handle()
#19 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/View/ViewCascade.php(33): Aerni\\AdvancedSeo\\View\\BaseCascade->withSiteDefaults()
#20 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/View/BaseCascade.php(31): Aerni\\AdvancedSeo\\View\\ViewCascade->process()
#21 /home/ploi/go-unity.org/vendor/aerni/advanced-seo/src/ServiceProvider.php(214): Aerni\\AdvancedSeo\\View\\BaseCascade::from()
#22 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesEvents.php(162): Aerni\\AdvancedSeo\\ServiceProvider->Aerni\\AdvancedSeo\\{closure}()
#23 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(455): Illuminate\\View\\Factory->Illuminate\\View\\Concerns\\{closure}()
#24 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#25 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners()
#26 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesEvents.php(177): Illuminate\\Events\\Dispatcher->dispatch()
#27 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/View/View.php(188): Illuminate\\View\\Factory->callComposer()
#28 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\\View\\View->renderContents()
#29 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#30 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#31 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(58): Illuminate\\Http\\Response->__construct()
#32 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(88): Illuminate\\Routing\\ResponseFactory->make()
#33 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(723): Illuminate\\Routing\\ResponseFactory->view()
#34 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(650): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()
#35 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(556): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#36 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(473): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()
#37 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): Illuminate\\Foundation\\Exceptions\\Handler->render()
#38 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(146): Illuminate\\Routing\\Pipeline->handleException()
#39 /home/ploi/go-unity.org/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\StaticCaching\\Middleware\\Cache->handle()
#41 /home/ploi/go-unity.org/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\AuthGuard->handle()
#43 /home/ploi/go-unity.org/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\AddViewPaths->handle()
#45 /home/ploi/go-unity.org/vendor/statamic/cms/src/Http/Middleware/Localize.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\Localize->handle()
#47 /home/ploi/go-unity.org/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\HandleToken->handle()
#49 /home/ploi/go-unity.org/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StacheLock->handle()
#51 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#53 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#55 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#57 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#59 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#60 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#62 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#64 /home/ploi/go-unity.org/vendor/rias/statamic-redirect/src/Http/Middleware/HandleNotFound.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Rias\\StatamicRedirect\\Http\\Middleware\\HandleNotFound->handle()
#66 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#68 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#69 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#70 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#71 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#72 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#73 /home/ploi/go-unity.org/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StopImpersonating->handle()
#75 /home/ploi/go-unity.org/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DisableFloc->handle()
#77 /home/ploi/go-unity.org/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#79 /home/ploi/go-unity.org/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#81 /home/ploi/go-unity.org/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#82 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#83 /home/ploi/go-unity.org/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#84 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\DisableBrowserCache->handle()
#85 /home/ploi/go-unity.org/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#86 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#87 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#88 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#89 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#90 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#91 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#92 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#93 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#94 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#95 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#96 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#97 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#98 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#99 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#100 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#101 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#102 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#103 /home/ploi/go-unity.org/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#104 /home/ploi/go-unity.org/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#105 {main}
"} 
```

**Comment by jasonvarga** [comment]
Would you be able to manually apply [the revert](https://github.com/statamic/cms/pull/9448) on your staging site just to see if that causes the error to go away? You can probably use a composer patch.

**Comment by aerni** [comment]
Yeah, I tried that already. The issue didn't go away. I wasn't sure if the composer patch didn't apply correctly or what else was going on. Because I can't reproduce this locally. So it makes it a little hard to debug.

**Comment by aerni** [comment]
Correcting myself. I re-deployed with the composer patch and the site works now. So it's for sure this PR that causes the error. Just weird that it doesn't cause the site to go havoc locally to this extend.

**Pull request merged**
