### PR TITLE
Feature/video field placeholder option

### PR DESCRIPTION
**Pull request by el-schneider**
as much as I like Rick Astley I'd like to set the placeholder myself sometimes

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Heads up: you probably want to change the branch on this PR to `master` instead of `3.1`

**Comment by el-schneider** [comment]
@duncanmcclean thanks. I'm a total noob to contributing 😅

**Comment by jasonvarga** [comment]
3.1 was fine

**Comment by jasonvarga** [comment]
Replaced by #4162 - thanks!

**Pull request closed without merging**
