### PR TITLE
Add placeholder and character_limit support to Bard

### PR DESCRIPTION
**Pull request by jacksleight**
This PR adds placeholder and character_limit support to Bard by implementing the official Tiptap 2 Placeholder and  CharacterCount extensions:

https://tiptap.dev/api/extensions/placeholder
https://tiptap.dev/api/extensions/character-count

The placeholder CSS is taken from the Tiptap docs.

This PR is for Bard 2 / TipTap 2 and targets the master branch.

Closes https://github.com/statamic/ideas/issues/826

### CODE REVIEW

**Comment by jasonvarga** [comment]
Nice ones. I've added the character count to the field like you'd see in the text fieldtype.

CleanShot 2022-08-09 at 15 24 19

**Review by jasonvarga — APPROVED** [review]

**Comment by jacksleight** [comment]
Oh nice!

**Comment by j3ll3yfi5h** [comment]
Hi @jacksleight! Thanks for your PR to make this feature available🙏🏻

How can I enable the character counter? Am I right, that this is not possible with e.g. `character_limit: '1000'` like on the textarea field?

**Comment by jacksleight** [comment]
Hey, this is only on the main branch at the moment, it hasn't been released yet. It requires Bard 2/TipTap 2 so will be part of Statamic 3.4.

**Comment by j3ll3yfi5h** [comment]
Oh, ok!  Thanks for the clarification!

**Pull request merged**
