### PR TITLE
[4.x] Use default slug to get taxonomy entries count

### PR DESCRIPTION
**Pull request by ryanmitchell**
This may be too simplistic a fix, but to get the correct entry count raised in https://github.com/statamic/cms/issues/4493 we could just make sure we query by the default locale.

Fixes https://github.com/statamic/cms/issues/4493

### CODE REVIEW

**Comment by ryanmitchell** [comment]
Yeah same test failures as on 5686. Something is definitely broken upstream.

**Comment by ryanmitchell** [comment]
Cool. Want to close this in favour of yours?

**Comment by jasonvarga** [comment]
Nope leave this, I'll push to yours.

I'll sort out the unrelated test failures too.

**Comment by ryanmitchell** [comment]
Seems like the tests aren't ever checking for a count on a localised slug? Only ever a slug in the primary language.

**Comment by jasonvarga** [comment]
Yeah that's reason people are reporting #4493, and your PR fixes that. 

But the tests were passing because the slug it looks like we're setting on the localizations don't ever actually make it to the term. If the localized term doesn't have a different slug, the bug never happens. No worries, I'll sort it out. Thanks!

**Pull request merged**
