### PR TITLE
Add password reset and password activation tables.

### PR DESCRIPTION
**Pull request by michaelr0**
Ensures that the potentially missing tables noted in https://github.com/statamic/cms/issues/2650 are added

### CODE REVIEW

**Comment by michaelr0** [comment]
I have now moved the password_resets table, into its own stub. Which matches the name and contents of https://github.com/laravel/laravel/blob/8.x/database/migrations/2014_10_12_100000_create_password_resets_table.php

And it'll only place a copy of that file in the applications migrations folder, if it doesn't already exist in that location.
This way, the rollback can work as expected, without concern of removing password_resets for an existing application or where laravel was installed prior to Statamic.

**Review by jasonvarga — CHANGES_REQUESTED** [review]
I'm surprised to see `statamic/statamic` doesn't already have a `password_resets` migration.
We should just add it, like `laravel/laravel` does. https://github.com/laravel/laravel/tree/8.x/database/migrations

Then our `auth:migration` command can just have the password_activations migration in it.

So, can you please remove the `password_resets` migration from this? We can do a separate PR in `statamic/statamic` to add it there.

**Comment by michaelr0** [comment]
Hi Jason, 

I'll submit a PR to statamic/statamic, given the conditional ! File::exists check, I think it might be worth leaving it in this PR as well, or atleast. So that existing installations of Statamic, that have not yet changed to using the database for their users, but may do so in the future will be covered when they run the `php please` command to generate the needed authentication tables.

But yeah, if you do still want it gone.
Then I'll remove it, no worries.

**Comment by jasonvarga** [comment]
I'd rather just have it removed. One less thing to maintain. Once statamic/statamic is updated, the initial installation flow will be fine. For existing users it's not difficult to copy a migration.

**Comment by michaelr0** [comment]
> I'd rather just have it removed. One less thing to maintain. Once statamic/statamic is updated, the initial installation flow will be fine. For existing users it's not difficult to copy a migration.

Not a problem, I have removed that now.

**Review by jasonvarga — APPROVED** [review]

**Pull request merged**
