### PR TITLE
Feature/extend view class (Add First/Exists, adjust Make/With)

### PR DESCRIPTION
**Pull request by michaelr0**
This aims to bring some additional functionality from Laravel's View class into Statamic's

```php
Statamic\View\View::exists($dynamicViewName);

Statamic\View\View::first([$dynamicViewName, 'fallbackView'])
```

It also updates the Make and With functions to behave more like Laravel's
```php
$view = Statamic\View\View::make('contact', ['address' => '42 Wallaby Way, Sydney'], ['name' => 'E Blurman']);
$view->data();
// Address: 42 Wallaby Way, Sydney
// Name: E Blurman


$view->with(['name' => 'P Sherman']); // Or $view->with('name', 'P Sherman');
$view->data();
// Address: 42 Wallaby Way, Sydney
// Name: P Sherman
```

### CODE REVIEW

**Comment by michaelr0** [comment]
The tests appear to be failing, unsure if this is because of a change that I have made?
Anyone able to confirm?

**Comment by jasonvarga** [comment]
Please merge 3.1 back into your branch. It looks like you may have undone a bunch of recent changes to the View class.

**Comment by michaelr0** [comment]
Hi Jason,

Sorry about that, that has been merged back in.

**Comment by jasonvarga** [comment]
Do we really need the `mergeData` argument? Is that helpful to you?

**Comment by michaelr0** [comment]
> Do we really need the `mergeData` argument? Is that helpful to you?

Can't say that I've ever actually used it, I just added it because that's what Laravel does with make and first.

**Review by jasonvarga — APPROVED** [review]
I made a few changes here:

Removed the `mergeData` arguments. Unless someone needs it, I'd rather not add stuff just because.

Removed the `exists` method for the same reason. It's still simple to just call `view()->exists()` anyway.

Adjusted the "template" in the exception message. We do call them templates, but they're still views, and if you did `View::make('invalid')` it would already say `View [invalid] not found` anyway.

Reverted the `with()` behavior. It's minor, but it's technically a breaking change. If you called `with($data)` before, it would override all of the data instead of merging it. Now it would merge. Probably a small chance it affects anyone, but still.

Thanks for the PR!

**Comment by michaelr0** [comment]
Great, Thanks Jason.

My initial and really only thing that sparked this was wanting to use ::first() and automatically have the cascade data etc.
So not really too fussed about ->with or mergeData.

Thanks for accepting it :)

**Comment by jasonvarga** [comment]
I figured those were what you really wanted. 👍 

Also @edalzell just pointed out this lovely bit of irony.

image

**Comment by michaelr0** [comment]
> I figured those were what you really wanted. 
> 
> Also @edalzell just pointed out this lovely bit of irony.
> 
> image

Hmm, does that mean I should restrain myself from submitting PR's like this? or are you happy for me to still submit them and you'll just reject the unneeded PR's?

**Comment by jasonvarga** [comment]
There was nothing wrong with what you did!

**Comment by michaelr0** [comment]
Sweet thanks :)

**Pull request merged**
