### PR TITLE
Stop iframe from killing Vue in Safari

### LINKED ISSUE #3744: Video field prevents asset browser in Safari
## Bug Description
Editing an entry in the CP that has a video in a `video` stops the asset browser of an `asset` field from loading.

## How to Reproduce
- Set up a fieldset with a video field and an asset field
- Add a video to the video field from YouTube or Vimeo
- Save and leave the entry
- Edit the entry again
- Click "Browse" on the asset field
- It doesn't open

## Environment

**Statamic version:** 3.1.14

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

### PR DESCRIPTION
**Pull request by arthurperton**
Fixes #3744 in the most peculiar way.

The iframe with the video caused Vue / Javascript to completely stop working in Safari. Now it doesn't anymore.

### CODE REVIEW

**Comment by jasonvarga** [comment]
lol wtf

**Comment by jackmcdade** [comment]
Is this effectively a “next tick” workaround?

**Comment by duncanmcclean** [comment]
Haha. I had to do pretty much the same thing for Stripe Elements once. No idea why it works but 🤷‍♂️

**Comment by arthurperton** [comment]
Yeah I know. I forgot to add "don't ask why" to the comment 😬 😜 

@jackmcdade I think it is somewhat next-tick like. 

I searched and couldn't really find this exact problem, but I somehow gathered that it might help to sort of postpone the iframe loading. So I added the iframe to the DOM in `mounted()` using a `ref` and `documentCreateElement`. That worked! Then I tried this more simple solution with the boolean, using a `setTimeout` in `mounted()` for setting it to true. That worked too. Removed the timeout, still working 😮

Judging from your comment @duncanmcclean it is a thing apparently 🤷🏻‍♂️

**Comment by arthurperton** [comment]
By the way the `allow="fullscreen"` is just for preventing an unrelated error in Safari.

**Comment by jasonvarga** [comment]
I can't recreate the problem to begin with. It seems fine even before checking out this PR.
Any tips? I believe I followed the instructions in the issue correctly. Have an entry with video and asset fieldtypes. Add a video, save. Come back and browse assets... the browser opens just fine. 🤔

**Comment by arthurperton** [comment]
I'm still getting it. I'm on the latest MacOS and latest Safari (version 14.1.1) and Statamic v3.1.28. I have updated the `pages` blueprint by adding a `video` and an `assets` field:

```
title: Pages
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: video
        field:
          display: Video
          type: video
          icon: video
          listable: hidden
      -
        handle: assets
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          display: Assets
          type: assets
          icon: assets
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
            - 'unique_entry_value:{collection},{id},{site}'
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true

```

I found out that the order of the added fields don't matter. For the video-URL I used the Rick Roll in the video field placheolder: https://www.youtube.com/watch?v=dQw4w9WgXcQ
Then save, reload, try and open the asset browser.

**Comment by arthurperton** [comment]
Weird. Glad you could reproduce. You're welcome!

**Pull request merged**
