### PR TITLE
[3.1] Show entries with published status only in content API

### LINKED ISSUE #2910: API should respect Future Date Behavior setting, not show drafts by default
## Bug Description
- When using the API, items with future dates are returned by default, ignoring the Future Date Behavior setting on the collection
- This seems like unexpected behavior
- I’d rather pull the list and have to explicitly override that setting.
- This would allow my code to not already expose the necessary toggle to anybody who decides to look at the underlying code to see what they can find.
- Related to this, I feel that the API shouldn’t expose draft content at all until such a point as it has authentication available
- Perhaps also overriding the future date behavior should also require authentication

## Environment
Statamic 3.0.30 Pro
Laravel 7.25.0
PHP 7.3.17
statamic/seo-pro 2.0.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`, migrated from v2

### PR DESCRIPTION
**Pull request by arthurperton**
Fixes #2910

Hides drafts and respects the collection's past and future date behaviours.

### CODE REVIEW

**Comment by jelleroorda** [comment]
Does this still allow to query on drafts like this? Right now you can add extra filters like [I mentioned here](https://github.com/statamic/cms/issues/2910#issuecomment-743785702).

**Comment by jelleroorda** [comment]
Awesome to see you on a triage by the way 😄 . I just noticed #2910 also mentions the 'future date behavior' on the API, should we create a new separate issue for that?

**Comment by arthurperton** [comment]
Haha 😄 on a triage 🚑 💉 nicely put. Thanks for the appreciation.

This pull request already takes care of the future date behavior. When set to private, entries with a date in the future will have a status of 'scheduled' instead of 'published' (see the code snippet below) and will therefore not be returned by the API.

https://github.com/statamic/cms/blob/21da308840674cc61c40b1e8630832ba4e11a49e/src/Entries/Entry.php#L491-L512

And to be able to opt-in on seeing drafts... That would require some additional code. Is this something users would want? I have no real opinion on it myself to be honest.

**Comment by jelleroorda** [comment]
Currently I don't have a need for drafts only, but maybe someone would want to use it to show 'upcoming articles' or something? Since right now you're already able to query statuses, I think we just want to add "a more sensible default" (so not showing drafts)?

So I was thinking that maybe we can set a default 'status' filter to 'published', but that it get's overriden if someone passes a status filter to the API filters. Right now with this solution I don't think that's possible.

**Comment by jesseleite** [comment]
Hey @arthurperton thank you for the PR! In this case, I'm closing in favour of https://github.com/statamic/cms/pull/3317, as we also need to handle manual filtering of `status` or `published` field. Appreciate the PR work you've done though!

**Pull request closed without merging**
