### PR TITLE
Asset Browser thumbnail style now matches the Fieldtype's

### PR DESCRIPTION
**Pull request by jackmcdade**
CleanShot 2022-09-13 at 15 17 29@2x

### CODE REVIEW

**Review by jesseleite — APPROVED** [review]

**Comment by jasonvarga** [comment]
Looks great. Just a couple of small things.

The "up" folder doesn't have a border like the others.

CleanShot 2022-09-13 at 15 40 48

This may be intentional, but SVGs now appear small and centered.

CleanShot 2022-09-13 at 15 41 41

This is what it looked like before:

CleanShot 2022-09-13 at 15 44 05

But some svgs still display larger:

CleanShot 2022-09-13 at 15 46 51

**Comment by jasonvarga** [comment]
Also I noticed that slashes have been added to the folder names. Was that intentional?

CleanShot 2022-09-21 at 16 17 08

**Comment by jackmcdade** [comment]
> Also I noticed that slashes have been added to the folder names. Was that intentional?

It was. Not a fan?

**Comment by jasonvarga** [comment]
The "ensure svgs are full sized" commit broke regular image ratios.

It went from this:

CleanShot 2022-09-21 at 16 57 07

to this:

CleanShot 2022-09-21 at 16 57 44

**Review by jasonvarga — CHANGES_REQUESTED** [review]
☝️

**Review by jasonvarga — APPROVED** [review]
No worries, I fixed that, it was simple.

**Comment by jackmcdade** [comment]
Ahh smort!

**Pull request merged**
