### PR TITLE
[4.x] Add ability to configure form mailer

### PR DESCRIPTION
**Pull request by aerni**
This PR adds the ability to configure the form mailer for each form. 

This is useful if you've got forms that should be sent from different servers. I ran into this a couple of times and wished it was possible. It's especially useful in a multisite setup with different domains.

You can select the mailer from a list of all available mailers in the form configuration in the CP. If no mailer was selected, Laravel automatically falls back to using the default mailer.

CleanShot 2023-12-06 at 15 12 24@2x

### CODE REVIEW

**Comment by aerni** [comment]
It seems like GitHub is having issues with running the tests. Test runs fine locally.

**Review by jasonvarga — DISMISSED** [review]
My gut reaction is that if you're in a situation where you want different forms to send from different mailers, then you may also want the individual emails to be from different mailers.

I'd suggest making the mailer defined per-email rather than per-form.

**Comment by aerni** [comment]
Good call. Will make that change.

**Comment by aerni** [comment]
The mailer can now be configured for each email.

CleanShot 2023-12-06 at 16 26 11@2x

**Comment by aerni** [comment]
Had to remove that tiny test again haha. And didn't find a way to assert a mailer. Laravel doesn't seem to be able to test this.

**Comment by jasonvarga** [comment]
No worries

**Pull request merged**
