### PR TITLE
Grid table view: vertical align cell content

### LINKED ISSUE #2518: Vertical alignment for stack selector in grid table
## Bug Description
The vertical alignment for a stack selector in a grid mode table is a little off.

## How to Reproduce
```yaml
-
    handle: pins
    field:
      fields:
        -
          handle: title
          field:
            input_type: text
            type: text
            localizable: true
            listable: hidden
            display: Title
            instructions: 'Leave blank to use the entry title'
        -
          handle: pins
          field:
            type: entries
            localizable: true
            display: Pins
            instructions: 'The pins you want to place.'
            listable: hidden
            mode: default
            collections:
              - pages
            max_items: 1
      mode: table
      min_rows: 1
      add_row: 'Add pin'
      reorderable: true
      type: grid
      instructions: 'Add one or more pins.'
      listable: hidden
      validate: required
      display: Pins
      replicator_preview: false
```

## Extra Detail
Screenshot 2020-09-23 at 14 51 24

### PR DESCRIPTION
**Pull request by robdekort**
Closes #2518 and #2770

### CODE REVIEW

**Comment by jasonvarga** [comment]
Aligning to the middle is unfortunately not the right solution either (just my opinion - this is something for @jackmcdade to chime in on).

Imagine in #2518 you were using a taller textarea instead of a regular text field. The entries field would be much lower.

But maybe that's just fine. 🤷

**Comment by robdekort** [comment]
Fair enough. Happy to improve on it. Let me know.

**Comment by robdekort** [comment]
Increasing the vertical padding on the bottom line of `toggle.scss` fixes this for the toggle use case. It seems this is just being used for when toggles are in a grid-fieldtype but might have nasty side effects in a stacked grid. Didn't test that yet.

For the stack selector however I can't find a specific rules when in a grid. 

I'll leave it to mr Jack for now!

I agree: it's not the prettiest with vertical middle align.

**Comment by robdekort** [comment]
Maybe a wrapper with a min height and flex items-center around fields is better.

**Comment by jasonvarga** [comment]
Holding off on this for now. We can solve it in another way. I think the other way would be to have per-fieldtype css when it's in a grid.

**Pull request closed without merging**
