### PR TITLE
[5.x] filter modifier

### PR DESCRIPTION
**Pull request by marcorieser**
It adds a `filter` modifier that removes `null` values from an array. It accepts a param on whether to keep or discard the array's keys (default: true/keep).

### CODE REVIEW

**Comment by jasonvarga** [comment]
Competing with #10961 @godismyjudge95  🥊

**Comment by jasonvarga** [comment]
Calling this `filter_empty` to keep `filter` available if we ever want to support the full scope of `filter`.

Also, removed the option to remove keys. If you want to do that you can use the `values` modifier already.

**Comment by daun** [comment]
This probably closed statamic/ideas#1222.

**Comment by duncanmcclean** [comment]
> This probably closed [statamic/ideas#1222](https://github.com/statamic/ideas/issues/1222).

Thanks, closed!

**Pull request merged**
