### PR TITLE
[4.x] Update URIs for mounted collection entries only if slug on mounted entry changed

### PR DESCRIPTION
**Pull request by marcorieser**
When saving the mounted entry for a collection the URIs for the entries in that collection get only updated if the slug of the mounted entry has changed.

Fixes: https://github.com/statamic/cms/issues/9848

### CODE REVIEW

**Comment by marcorieser** [comment]
I would love to add a test case for that but I have no idea where to even start.

**Comment by duncanmcclean** [comment]
> I would love to add a test case for that but I have no idea where to even start.

No worries - I can get it 👍

**Comment by marcorieser** [comment]
> > I would love to add a test case for that but I have no idea where to even start.
> 
> No worries - I can get it 👍

I'm on it but the behaviour of the current test seems a bit odd.

**Comment by marcorieser** [comment]
@duncanmcclean I would be grateful if you could take a look. Weirdly the current automated test fails but my manual testing in a real project was successful.

**Pull request merged**
