### PR TITLE
Datepicker debounce change

### PR DESCRIPTION
**Pull request by zsoltjanes**
Hi, I felt the 500ms little bit few when I used the datepicker, so I changed it to 1000ms and now its more user friendly I think.

### CODE REVIEW

**Comment by jackmcdade** [comment]
I'm sorry I don't quite follow – what makes 1000ms more friendly than 500ms?

**Comment by zsoltjanes** [comment]
You will have 2x time to enter your numbers. When you little bit tired or just thinking what date you wna to enter because of the debouce too short time its automatically jump out of the input box and its annoying.

**Comment by jackmcdade** [comment]
Huh, I still don't follow. You shouldn't _ever_ be jumped out of the input bo. What browser are you using? Can you share a video? You can use https://zipmessage.com/statamic to make one real quick.

**Comment by zsoltjanes** [comment]
I sent the video did you receive it?

**Comment by jackmcdade** [comment]
Unfortunately not – do you have the link?

**Comment by jackmcdade** [comment]
Ahh I finally figured out what you're talking about – when you completely clear the input and type the full date. This makes sense to me – merging!

**Pull request merged**
