### PR TITLE
Optionally include unpublished entries

### LINKED ISSUE #3918: Entries fieldtype: status filter to include unpublished entries
Since 3.1.15, it looks like we're now [filtering unpublished entries out](https://github.com/statamic/cms/pull/3544) when outputting entries from the Entries fieldtype. Unfortunately this has been a nasty breaking change for me as I'd expect that any Entries selected (published or unpublished) would be outputted and there seems to be no way to include unpublished entries at the moment. 

Can we implement [Jason's solution](https://github.com/statamic/cms/pull/3544#pullrequestreview-663661152):

```
{{ features status:in="draft|published" }}
...
{{ /features }}
```

Screen Shot 2021-06-01 at 2 31 02 pm

### LINKED ISSUE #4251: Entries columns in CP listing dont display unpublished entires
## Bug Description

I think this might be related to https://github.com/statamic/cms/issues/3918. It is technically a different problem, but may be due to the same underlying issue. Apologies if this counts as a duplicate.

When you have a collection with an Entries field, and you've linked an entry to another entry that's unpublished, the column in collection listing in the CP is blank even when a value is set.

## How to Reproduce

1. Create a collection with an Entries field
2. Create an entry in that collection and link the field to an unpublished entry
3. The Entries column in the CP will be blank

## Extra Detail

132825388-3e36e024-9d39-4380-831a-dfc668b52123
132825341-badec5c1-fdc2-4262-8349-88e56af0bdd4

## Environment

Statamic 3.2.4 Solo
Laravel 8.60.0
PHP 7.4.21

### PR DESCRIPTION
**Pull request by arthurperton**
This PR applies the policy to exclude unpublished entries by default, and leave the option to include them by using a filter explicitly.

- fix #3918
- fix #4251
- apply the same policy to Terms, as I mentioned in #7322

### CODE REVIEW

**Comment by arthurperton** [comment]
It all seems to work well now. 

In `StatusQueryBuilder@queriesStatus()` you can see that reflection is used to drill down through the decorators and get the protected `wheres` property from the actual `Builder`. Again it all works well, but it is also a bit hacky. 

It would be nice to access the `wheres` property by adding a getter to the abstract `Builder` class. The decorators automatically forward the call to the `Builder` and no funky reflection is needed.

**Comment by arthurperton** [comment]
I decided to add the `wheres()` getter. Ready for review now.

**Review by jasonvarga — CHANGES_REQUESTED** [review]
This looks good but I don't think it will work when using the eloquent driver, or any other entry driver.

They won't have a `wheres` method in it.

It might be tedious but I think we need to override all the `where` methods.

```php
public function where($column, $operator = null, $value = null, $boolean = 'and')
{
    if ($column === 'status') {
       $this->hasQueriedStatus = true;
    }

    $this->builder->where($column, $operator, $value, $boolean);

    return $this;
}

public function whereIn($column, $values, $boolean = 'and') { ... }
public function orWhereIn($column, $values) { ... }

// etc
```

**Comment by arthurperton** [comment]
Thank you for that feedback. The `where..` methods are being intercepted now to check if the status is being queried.

**Comment by jasonvarga** [comment]
Nice solution.

**Comment by stoffelio** [comment]
Any chance this will find its way into core with 4.0?

**Review by jasonvarga — APPROVED** [review]

**Comment by jasonvarga** [comment]
Made some small tweaks and adjusted tests.

Also, I added the ability to pass in the `$status` to the `StatusQueryBuilder`. We don't actually use it, but I like keeping the class called `StatusQueryBuilder`. If we left the `status` hardcoded to `published`, it's really more of a `PublishedQueryBuilder`, which just sounds weird. 😂

**Comment by arthurperton** [comment]
😀 very nice! I am glad that this is integrated.

**Pull request merged**
