### PR TITLE
Ability to hide display field

### PR DESCRIPTION
**Pull request by edalzell**
Closes https://github.com/statamic/ideas/issues/555

### CODE REVIEW

**Comment by jasonvarga** [comment]
Something just feels odd about seeing a "display" field and then a separate "hide display" toggle.

Not to mention all the `hide_display: false`s you'd start getting in your blueprint files.

Can we come up with any better ideas? What if you just emptied the `display` value?

**Comment by edalzell** [comment]
> What if you just emptied the display value?

You have to use `' '` to do that, then you get an extra line in the CP.

**Comment by edalzell** [comment]
> Not to mention all the hide_display: falses you'd start getting in your blueprint files.

Don't falsely things get stripped out before saving?

**Comment by jasonvarga** [comment]
Yeah that happens now, but we can change how things work.

**Comment by edalzell** [comment]
> Yeah that happens now, but we can change how things work.

ok, I can re-work to check the title

**Comment by edalzell** [comment]
> Yeah that happens now, but we can change how things work.

How about this way @jasonvarga? There are several broken tests that I can fix, if you feel this is a good way to do this.

**Comment by jasonvarga** [comment]
How about if you have `display: false` it hides the label.
A completely missing `display` key will use the fallback behavior we currently have.

In the YAML that would be simple enough.

In the CP controller, we could adjust it so that if you submit an empty field, it saves `false`.

**Comment by edalzell** [comment]
> How about if you have `display: false` it hides the label. A completely missing `display` key will use the fallback behavior we currently have.
> 
> In the YAML that would be simple enough.
> 
> In the CP controller, we could adjust it so that if you submit an empty field, it saves `false`.

Isn't that what I had at first? https://github.com/statamic/cms/pull/6301#issuecomment-1215268246

**Comment by jasonvarga** [comment]
Just a cosmetic toggle. I don't want a completely different key in the yaml.

**Comment by jasonvarga** [comment]
I don't want a toggle though. I just want it to work that if you empty the field, it saves `false`.

**Comment by edalzell** [comment]
> A completely missing display key will use the fallback behavior we currently have.

What would they put in the field to have it use the fallback?

**Comment by edalzell** [comment]
I need help with this one, but it's low priority for sure, so I'll close this for now and revisit later if it becomes more of a priority.

**Pull request closed without merging**
