### PR TITLE
Allow assets to trigger URL invalidation

### PR DESCRIPTION
**Pull request by FrittenKeeZ**
If focal point or metadata is updated, this provide a way to invalidate cached URLs.

@jasonvarga this is part of a bigger custom cache invalidator, where I'm tracking references to assets, entries and terms, and if any of them are updated, I can trigger cache invalidation for any pages they're referenced.

### CODE REVIEW

**Comment by FrittenKeeZ** [comment]
@jasonvarga thoughts on this?

**Comment by FrittenKeeZ** [comment]
@jasonvarga any chance this could be moved along?

**Comment by jasonvarga** [comment]
Can you target 3.3 and merge 3.3 into it?

**Review by jasonvarga — APPROVED** [review]

**Comment by FrittenKeeZ** [comment]
@jasonvarga Github had unverified my email for notifications, so I didn't see you respond to this one - nice to see it get merged :)

**Pull request merged**
