### PR TITLE
UI fixes and improvements

### PR DESCRIPTION
**Pull request by j3ll3yfi5h**
Fixes https://github.com/statamic/cms/issues/3030
Fixes https://github.com/statamic/cms/issues/5034

- [x] introduce four main sections with z-indexes
- [x] position mainsections sticky instead absolute/fixed
- [x] prevent duplicate nav markup
- [x] improve table overflowing
   - [x] Collections
   - [x] Entries
   - [x] Terms
   - [x] Assets
   - [x] Fieldsets
   - [x] Forms
   - [x] Form Submissions
   - [x] Users
   - [x] User Groups
- [x] prevent popover overflows
- [x] change `<header>` children margins to flex gaps and fix overflowing headings

Bildschirmfoto 2022-07-25 um 18 28 36

### CODE REVIEW

**Review by jasonvarga — DISMISSED** [review]
Is the update to `package-lock.json` necessary? If not, please revert it.

**Comment by jasonvarga** [comment]
To make this easier to review, I'd stop adding items to the scope of this PR.

Additional UI issues can be fixed in separate PRs.

If/when you're done with the items you've outlined in the description, go ahead and mark this as ready for review.

**Comment by j3ll3yfi5h** [comment]
Alright. I'm currently using the changes on a client project to see, how it behaves and I'll make it ready for review by the end of the day. 👍

**Comment by jackmcdade** [comment]
All the table overflow stuff looks great!

Unfortunately the nav, section, and z-index stuff breaks all the fullscreen modes of Bard, Markdown, etc.

CleanShot 2022-08-04 at 09 36 35@2x

**Review by jackmcdade — CHANGES_REQUESTED** [review]
All the table overflow stuff looks great!

Unfortunately the nav, section, and z-index stuff breaks all the fullscreen modes of Bard, Markdown, etc

182860826-5a2de712-8d34-49ea-a933-833f83c55fe6
.

**Comment by j3ll3yfi5h** [comment]
Oh, I did totally miss those fullscreen views, sorry!

I'll look into it, maybe there ist something we can do with the PortalVue.

**Comment by jackmcdade** [comment]
Or maybe it's mostly z-index? Previously each of those numbers had a purpose too (997, 998, etc) to account for the Bard Nav, main nav, etc etc.

**Comment by jackmcdade** [comment]
I also found that the table view gets way too tall 
CleanShot 2022-09-07 at 09 54 36@2x

**Comment by j3ll3yfi5h** [comment]
> I also found that the table view gets way too tall CleanShot 2022-09-07 at 09 54 36@2x

This was in my opinion the nicest way to fix those popovers, which are causing scrollbars:
https://user-images.githubusercontent.com/6337411/189731678-91540675-7005-478f-b7d8-ee1b3a7d2bd5.mov

At least ten fields in the filter should work in my opinion - what is your opinion on this?

**Comment by jackmcdade** [comment]
Will be using this as inspiration for my work in #7559 — as it is right here I won't be able to merge it, but thank you for the hard work! It is most appreciated and valued.

**Pull request closed without merging**
