### PR TITLE
[4.x] Fix data loss when reordering sets with revealer fields

### PR DESCRIPTION
**Pull request by jacksleight**
I _think_ this fixes https://github.com/statamic/cms/issues/8615. Be great if anyone who's run into that can test.

The issue seems to be caused by a race condition when unsetting/setting the revealer fields in the store. When you move a set it will affect the field paths of multiple sets, so there will be multiple unset/set calls which could get mixed up. This defers the set calls to the next tick to ensure they run after everything has been unset (hopefully).

### CODE REVIEW

**Comment by jacksleight** [comment]
Yep that's what's happening and this does correct the call order. Log output before:

```
unset replicator_field.0.revealer_field
set replicator_field.1.revealer_field
unset replicator_field.1.revealer_field
set replicator_field.0.revealer_field
```

And after:

```
unset replicator_field.0.revealer_field
unset replicator_field.1.revealer_field
set replicator_field.1.revealer_field
set replicator_field.0.revealer_field
```

I also tested it with lots of sets (20), moving the last one to the start so everything gets a new index, and all the unsets run first.

It may not cause an issue but I'm wondering if this should also be changed:

https://github.com/statamic/cms/blob/9482cf1812f92855162aceea9a59771a671cafcb/resources/js/components/fieldtypes/bard/BardFieldtype.vue#L408C10-L408C10

Seems like it would have the same problem.

**Comment by jasonvarga** [comment]
Can't hurt.

**Comment by jacksleight** [comment]
> Can't hurt. (Famous last words)

🤞

**Comment by jasonvarga** [comment]
To be honest I can't reproduce it, but the fix seems to be pretty simple and risk free. Hopefully it solves the issue for those that are running into it.

**Comment by robdekort** [comment]
I appreciate the work on this, reporting it and diving into it. Thank you all!

**Pull request merged**
