### PR TITLE
Use Localize middleware in frontend user and nocache controllers

### PR DESCRIPTION
**Pull request by jacksleight**
Fixes https://github.com/statamic/cms/issues/7890
Fixes https://github.com/statamic/cms/issues/7893

Only implements the Localize middlewear rather than the full `statamic.web` group. Could be done in the routes file but I just copied the approach from the `FrontendController` class.

### CODE REVIEW

**Comment by robdekort** [comment]
Just pulled this in and it works like a charm. Thanks Jack!

**Comment by jasonvarga** [comment]
Nice one, @jacksleight

**Comment by robdekort** [comment]
Great stuff!

**Comment by jasonvarga** [comment]
This unfortunately only "appears" to work because your default site is the one with the translation.

If you were to have multiple sites configured, and you used either feature (login form or nocache tag) from the second site, it'll show the language from the first site.

This is because the Localize middleware determines the site by the current URL.

So when you submit the form, you end up on something like `/!/form-endpoint` and the middleware works out the site from there.

The middleware should somehow figure out the referring URL's site, not the current one.

And that should be done without breaking it for the other places where the Localize middleware is already being used.

I'm going to close this for now, but we can reopen if this gets sorted. Either on this PR or a fresh one.

**Comment by jasonvarga** [comment]
The Localize middleware (either the existing one, or a new one) would need to be able to look at the referring url to determine the site, instead of the current url.

**Comment by robdekort** [comment]
Gotcha. Will open an issue for this.

**Comment by robdekort** [comment]
Oh not needed. My previous issues reopened due to GH magic.

**Pull request closed without merging**
