### PR TITLE
Improve german translations and add some missing strings

### PR DESCRIPTION
**Pull request by Konafets**
This PR takes the translations from https://github.com/statamic/cms/pull/1655 and accounts for the differences between high-german and swiss-german (e.g. ß -> ss).

Additionally it adds support for so far hardwired strings in Blade and VueJs.

It addresses the following issues from https://github.com/statamic/cms/issues/1697:

1. Link Existing Field or Fieldset
	- [X] Sorry, no matching options
	- [X] Button text 'Link'
	- [X] or
	- [X] Placeholder text 'eg. _hero'

2. Password Reset Mail\
   I could not test this because could not convince Statamic to show me the german version of the Forgot Password page and send the german version of the email. I added the translations as described here: https://github.com/laravel/docs/pull/4239/files    
	- [X] Hello
	- [X] Regards
	- [ ] If you're having trouble -> **Was not able to translate this.**

3. Reset password error message
	- [ ] The password must be at least 8 characters.

4. Getting started widget
	- [x] Please remember ...

5. Permissions
	- [x] Title 'Create a Role'
	- [x] 'role' in Learn more about… (But actually there should be only one 'Learn more about…' button?)
	- [ ] No message helper text in the section 'Updates' (also in the en version) -> **String should be added by a maintainer**
	- [ ] No message helper text in the section 'User' (also in the en version) -> **String should be added by a maintainer**

6. Groups
	- [x] Title 'Create a User Group'
	- [x] 'User group updated' message

7. Forms (Blocked by https://github.com/statamic/cms/issues/1896)
	- [ ] Title 'Create a Form'
	- [x] Button 'Add Email'
	- [ ] Recipient (To)
	- [ ] Sender (From)
	- [ ] Subject
	- [ ] Template

8. Choose a blueprint (Blocked by https://github.com/statamic/cms/issues/1896)
	- [ ] 0/1 selected

9. Error message (i.e. when leave required fields blank or use spaces when creating a folder)
	- [x] The given data was invalid

10. Globals
	- [x] Title 'Create a Global Set'

11. Configure global set
	- [x] Content Model

12. Taxonomy
	- [x] Title 'Create a Taxonomy'

13. Collections/Navigations
	- [x] 'Parent' field in the sidebar

14. Revisions
	- [x] Publish -> Placeholder "Choose..."
	- [ ] Is it possible somehow to localize the date in the revision history?\
			  **Question**: It is possible to pass a format string to MomentJS. The question is where should that format be stored? 
		- [ ] Site-wide in `.env` 
		- [ ] Per user in the user settings
	- [x] Flag 'Publish', 'Unpublish' and 'Revision' in the revision history

15. If entries can contain links ...
	- [x] First Child
	- [x] Entry

16. Dropdowns are often too narrow for german words
	- These are styling issues

17. Sidebar
	- [x] 'Sidebar' in live preview
	- [x] 'Sidebar' in tab-title (when the screen size is too narrow to place the sidebar on the right side)

18. Live Preview
	- [x] 'Choose…' in Responsive Dropdown

19. Edit Blueprint
	- [x] 'Main' Section
	- [x] 'linked fieldset'

20. Add fieldtype
	- [x] Text
	- [x] Media
	- [x] Relationship
	- [x] Structured
	- [x] Special
	- [x] Pickable
	- [x] All fieldtype names

21. Fieldtype: Conditions\
	Did not address these, because I did not got the consequences when translating these. Will investigate this and might add this to an own PR.
	- [ ] equals
	- [ ] not
	- [ ] contains
	- [ ] contains_any
	- [ ] custom

22. Fieldtype: Validation
	- [x] Add rule

23. Fieldtype: Array
	- [x] Label (Optional)

24. Fieldtype: Date
	- [x] Single
	- [x] Multiple
	- [x] Range

25. Fieldtype: Link
	- [x] First Child
	- [x] Entry

### CODE REVIEW

**Comment by jasonvarga** [comment]
Is this ready for review? I see it was marked ready but then more stuff was pushed up.

**Comment by Konafets** [comment]
@jasonvarga From my side this is ready for review.

**Comment by jasonvarga** [comment]
Is #1655 still necessary after I merge this?

**Comment by Konafets** [comment]
This one addresses high-german translations while #1655 addresses swiss-german translations. While in pronouncing there are quite some differences in written language they are not so much differences but those which exists are significant. Vor example high-german uses the letter _ß_ while swiss-german uses  _ss_, in high-german its _die E-Mail_ and in swiss-german "das E-Mail". Additionally this PR extracted some hidden hardcoded strings, which would be not be translateble. 

So I would vote for merge both.

**Comment by ebeauchamps** [comment]
I think you should merge both, given users will then have a choice between de-CH and de-DE. Back in statamic 1, we had 2 translations for Norwegian language and 2 for German (formal, informal).

**Comment by jasonvarga** [comment]
Thank you. Just confirming!

**Comment by Konafets** [comment]
Hi @jasonvarga, 

thanks for merging.

**Comment by studio1902** [comment]
Great work @jasonvarga. Thanks for merging this and my Dutch translation. Does this mean I can rerun the translator now and it will pick up the missing strings?

**Pull request merged**
