### PR TITLE
Fix LinkFieldType not updating when switching sites

### LINKED ISSUE #5185: URL in link-fieldtype is not updated at language-switch
### Bug description

I used the build in link fieldtype and noticed, that the url gets not updated in the UI interface at language switch. After I reloaded the page, the correct link url is showing.

### How to reproduce

Prerequisite: set individual link_url for 2 languages (e.g. de & en)
- change link url in "de" and save
- switch to "en" -> "de" link is shown
- reload page -> correct "en" link is shown

Maybe related to: https://github.com/statamic/cms/issues/4042

### Logs

_No response_

### Versions

Statamic: 3.2.32

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by EdFen**
wip..... (i will update this with a complete description and example soon)

This PR fixes an issue i found with the LinkFieldType in combination with a multisite.

When you have the following in the control panel

Fixes #5185

### CODE REVIEW

**Comment by afonic** [comment]
Hey guys, any news on getting this merged?

Luckily it doesn't save the wrong value but we have a couple of very concerned users.

**Comment by edalzell** [comment]
It's still marked a draft, likely because of `(i will update this with a complete description and example soon)`

**Comment by afonic** [comment]
Yeah but it has since been described in #5185 I think?

**Comment by jasonvarga** [comment]
Closing in favor of #5447

**Pull request closed without merging**
