### PR TITLE
[4.x] Cache Blueprint columns

### PR DESCRIPTION
**Pull request by jonassiewertsen**
This change helps us with performance, especially if you open large entries.

It caches the calculated columns for a single request.

### CODE REVIEW

**Comment by jasonvarga** [comment]
Are you planning on adding more to this PR? It's still a draft.

**Comment by jonassiewertsen** [comment]
This PR is complete.

It is a draft though, as I asked others if they can confirm the speed improvement to make 100% sure it's not tied to our custom setup.

**Comment by jeremyvienney** [comment]
I can confirm an improvement of around 15% in waiting server time response.
On an entry with ~20 sets from a replicator (so lot of content), average response time is cut from around 850ms to 700ms.
Thank you !

**Comment by jasonvarga** [comment]
I'm curious how this is helping you. We aren't calling `->columns()` in many places.

If you place `ray()->count('columns')` inside the `columns()` method on the 4.x branch, I can only really see it once per request in most places.

```diff
    public function columns()
    {
+       ray()->count('columns');

        $columns = $this->fields()
```

Do you have an addon or custom code where you are calling `columns()` more often?

**Comment by jeremyvienney** [comment]
> I'm curious how this is helping you. We aren't calling `->columns()` in many places.
> 
> If you place `ray()->count('columns')` inside the `columns()` method on the 4.x branch, I can only really see it once per request in most places.
> 
> ```diff
>     public function columns()
>     {
> +       ray()->count('columns');
> 
>         $columns = $this->fields()
> ```
> 
> Do you have an addon or custom code where you are calling `columns()` more often?

Hi Jason, it should be due indeed to some addons (Bard Texstyle for example seems to use it a lot), because it is called 9 times for me on a control panel entry edit page.

**Comment by jasonvarga** [comment]
Can you show what addons are installed in the output of `php please support:details` ?

**Review by jasonvarga — APPROVED** [review]

**Pull request merged**
