### PR TITLE
add required attribute

### PR DESCRIPTION
**Pull request by j3ll3yfi5h**
Closes statamic/ideas#524

### CODE REVIEW

**Comment by j3ll3yfi5h** [comment]
https://github.com/statamic/ideas/issues/524

**Comment by jasonvarga** [comment]
Can you fix the tests?

https://github.com/statamic/cms/blob/38cd482578ad0428998f319b8c6860fdc8c4752c/tests/Tags/Form/FormCreateTest.php#L90

and

https://github.com/statamic/cms/blob/674e1c16277ecc31b86a1805076bb963c5622518/tests/Tags/User/RegisterFormTest.php#L100

**Review by jasonvarga — CHANGES_REQUESTED** [review]
Can you fix the tests?

https://github.com/statamic/cms/blob/38cd482578ad0428998f319b8c6860fdc8c4752c/tests/Tags/Form/FormCreateTest.php#L90

and

https://github.com/statamic/cms/blob/674e1c16277ecc31b86a1805076bb963c5622518/tests/Tags/User/RegisterFormTest.php#L100

**Comment by j3ll3yfi5h** [comment]
how? No idea why it didn't pass your tests...

**Review by jasonvarga — APPROVED** [review]

**Pull request merged**
