### PR TITLE
[4.x] translate locale label

### PR DESCRIPTION
**Pull request by peimn**
Translate label in preferences' locale dropdown

### CODE REVIEW

**Comment by osbre** [comment]
In terms of user experience: If one accidentally switches the language to the wrong one, would they easily be able to switch it back?

**Comment by peimann** [comment]
Hmm! I agree that it may be difficult for user to turn back to previous
locale in case of mistake...
I will update this PR. Thank you.

**Comment by peimn** [comment]
Hmm! I agree that it may be difficult for user to turn back to previous locale in case of mistake... I will update this PR. Thank you.

**Comment by jasonvarga** [comment]
Thank you but this is resolved in #9739

**Pull request closed without merging**
