### PR TITLE
Querybuilder: add whereColumn()

### PR DESCRIPTION
**Pull request by ryanmitchell**
This change allows you to do queries for equivalence against 2 different columns such as:

```
Entry::query()
    ->whereColumn('field_1', 'field_2')
    ->get();
```

and

```
Entry::query()
    ->whereColumn('field_1', '!=', 'field_2')
    ->get();
```

Sorry for all the seperate PRs, thought it best to split them out to make it easier to merge rather than one big PR (hope you feel the same). 

These PRs combined with nested wheres would mean the only things still required for eloquent compatibility are:

->where and ->whereColumn where you pass an array... eg

```
Entry::query()->where([
    'title' => 'test',
    ['slug', '=', 'test2']
])
```

and querying json where clauses, which I have working code for.

### CODE REVIEW

**Comment by jasonvarga** [comment]
> thought it best to split them out to make it easier to merge rather than one big PR (hope you feel the same).
Absolutely 🎉

**Comment by ryanmitchell** [comment]
Merge conflicts resolved on this one

**Comment by jasonvarga** [comment]
I duplicated the tests into all the various classes, and noticed this isn't implemented for IteratorBuilder.

**Review by jasonvarga — CHANGES_REQUESTED** [review]
I duplicated the tests into all the various classes, and noticed this isn't implemented for IteratorBuilder.

**Comment by ryanmitchell** [comment]
Yeah sorry, I think when I opened this we weren't doing IteratorBuilder but since then we are 😄 
Its there now

**Review by jasonvarga — APPROVED** [review]

**Pull request merged**
