### PR TITLE
Addons can "register" fieldsets

### PR DESCRIPTION
**Pull request by edalzell**
Part of statamic/ideas#644

**Fieldsets**:
- [x] addons can register field sets
- [x] registered fieldsets show up in fieldset listing
- [x] non-editable fieldsets do not show up in fieldset listing
- [x] addon fieldsets can be imported into blueprints
- [x] fieldset listing shows overridden fieldsets
- [x] saved addon fieldsets go into 'override' folder
- [x] can't delete them in the listing page
- [x] group fieldsets in listing page

### CODE REVIEW

**Comment by edalzell** [comment]
Having a bit of a problem with the tests. Weird ones are failing and I can't figure out a nice way to test the "saving into vendor folder one". Happy to up with some guidance help.

I did test all of this in a site.

**Comment by edalzell** [comment]
@jasonvarga this is working but I'm having trouble with the tests, let me know if you'e like me to persevere or you can handle.

**Review by jasonvarga — CHANGES_REQUESTED** [review]
I'll edit this comment as I find more stuff.

General change requests:

- [ ] Rename `addDirectory` to `addNamespace` (and other references of directory to namespace)
- [x] Add spacing between fieldset sections in the listing.
- [x] Hide the "My Fieldsets" header if you only have one section.
- [x] Vendor override files are recognized as completely separate fieldsets. They appear within "my fieldsets", as well as in the fieldset/field pickers in the blueprint editor.

Changes to handle requests in #5803:

- [x] Ability to choose at a namespace level whether edits will go back to the original location, or to a vendor override file.

**Comment by instudentmedia** [comment]
> Changes to handle requests in #5803:
> 
> * [x]  Ability to choose at a namespace level whether edits will go back to the original location, or to a vendor override file.

Thank you very much for this @jasonvarga, very thoughtful and considered solution to our problem. It's very much appreciated.

If it's easier, a boolean config toggle would work for us, `config('statamic.system.override_addon_fieldsets', false)` or similar? 

I'll leave it with you.

**Comment by jasonvarga** [comment]
Closing in favor of #6588

**Pull request closed without merging**
