### PR TITLE
[4.x] Dark Mode for Control Panel

### PR DESCRIPTION
**Pull request by peimn**
Carefully curated hues designed to ease eye strain during nighttime work sessions, which often dominate our schedules. 🌚🌃

### CODE REVIEW

**Comment by jasonvarga** [comment]
Awesome

**Review by duncanmcclean — CHANGES_REQUESTED** [review]
When you're able, can you merge `5.x` into this branch and update the target branch for this PR?

There's a bunch of merge conflicts and I didn't want to mess anything up 🙂

**Comment by peimn** [comment]
I've completed the merge to version 5.x, improved the dark mode, and resolved several bugs. I'm now ready to push the updates.

**Comment by jasonvarga** [comment]
Ok, go for it!

**Comment by peimn** [comment]
Sorry! It took me some time to double-check everything to ensure it was tidy because I made other changes and didn't want them to be merged. I've pushed dark-mode merge for 5.x in another pull request #10073

**Comment by duncanmcclean** [comment]
Thanks! I'll close this in favour of https://github.com/statamic/cms/pull/10073.

**Pull request closed without merging**
