### PR TITLE
Easily customizable CP nav

### PR DESCRIPTION
**Pull request by jesseleite**
# Overview

### Access CP nav preferences...

CleanShot 2022-12-21 at 22 50 50

### Customize to your liking...

CleanShot 2022-12-21 at 22 52 39

### Or set global or role-based defaults...

CleanShot 2022-12-21 at 22 51 59

# Technical Approach

## The Problem

Though it's possible to [add and remove CP nav items](https://statamic.dev/extending/navigation) using the `Statamic\Facades\CP\Nav` facade for the purpose of addons, it's not easy for the end user to customize their side nav without diving into PHP, and it's certainly not possible to customize CP nav items from the control panel UI itself.

## The Solution

The goal of this PR is to make it super easy to customize/personalize... Ideally per user, role, etc. using our preferences API, and with a drag and drop GUI so that users can easily create / hide / modify / alias / move / reorder items.

Another goal is to be fully backwards compatible, as the current PHP implementation is really powerful for addons. It lets you do things like: 1) Dynamically loop over data to programatically create nav items, 2) Customize advanced settings like authorization/permissions on each nav item, etc., and we don't want to take any of that away.

This approach allows the user to apply their own modifications _on top of the currently built nav_ (after any addons have extended the nav). The user wouldn't be starting with a fresh/blank slate (though it could certainly be an option in the future), and their modifications could then be saved to the user's preferences, etc.

## Simple Example

For example, this would allow a user to pin/alias the 'Pages' collection to top of the sidebar (as mentioned in https://github.com/statamic/ideas/issues/74#issuecomment-580904383 and https://github.com/statamic/ideas/issues/100), so that the user could see and access it without having to click on 'Collections' first.

CleanShot 2022-09-08 at 16 33 40

This would store the following preferences to the user's data...

```yaml
name: 'Jesse Leite'
super: true
preferences:
  nav:
    top_level:
      content::collections::pages: '@alias'
```

## Advanced Example

As mentioned above, we want to give as much control as possible to the end user. This next example shows us:

- Pinning a 'Pages' alias to the top level
- Moving the 'Users' section above the 'Content' section
- Renaming the 'Content' section to 'Site'
- Removing the 'Globals' nav item
- Adding a custom external 'Flickr' nav item
- Moving both 'Blueprints' and 'Fieldsets' out of 'Fields' into our new 'Site' section

image

And the yaml for above customizations...

```yaml
name: 'Jesse Leite'
super: true
preferences:
  nav:
    reorder: true
    sections:
      top_level:
        content::collections::pages: '@alias'
      users: '@inherit'
      content:
        display: 'Site'
        items:
          content::globals: '@hide'
          flickr:
            action: '@create'
            icon: 'assets'
            display: 'Flickr'
            url: 'https://flickr.com'
          fields::blueprints: '@move'
          fields::fieldsets: '@move'
```

## Todo:

- [x] Create yaml preferences layer to make modifications to the CP nav, allowing users to:
    - [x] Create items
    - [x] Hide items
    - [x] Modify items
    - [x] Alias items
    - [x] Move items
    - [x] Reorder items
    - [x] Rename sections
    - [x] Reorder sections
- [x] Create JS builder, allowing users to:
    - [x] Create items
    - [x] Hide items
    - [x] Modify items
    - [x] Alias items
    - [x] Move items
    - [x] Reorder items
    - [x] Rename sections
    - [x] Reorder sections
- [x] Hook up saving of preferences
    - [x] To user preferences
    - [x] To role preferences
    - [x] To default preferences for all users (requires https://github.com/statamic/cms/pull/6642)
- [x] Add test coverage
    - [x] To ensure the nav builder properly applies the above modifications from yaml preferences
    - [x] For the yaml preferences config normalization pre-JS
    - [x] For the yaml preferences config minification post-JS
- [x] Add documentation https://github.com/statamic/docs/pull/979

---

Closes https://github.com/statamic/ideas/issues/512
Closes https://github.com/statamic/ideas/issues/499
Closes https://github.com/statamic/ideas/issues/153
Closes https://github.com/statamic/ideas/issues/100
Closes https://github.com/statamic/ideas/issues/74

References: https://github.com/statamic/ideas/issues/74#issuecomment-580904383

### CODE REVIEW

**Comment by jackmcdade** [comment]
Also closes https://github.com/statamic/ideas/issues/512

**Review by jasonvarga — APPROVED** [review]
Waiting on the docs PR, where I'll cross reference it and merge after that, but this looks good to me.

**Comment by Narretz** [comment]
What is this sorcery ... This lifts Statamic to a whole new level. That said, I don't see the docs on the statamic page. Not published yet?

**Comment by duncanmcclean** [comment]
> What is this sorcery ... This lifts Statamic to a whole new level. That said, I don't see the docs on the statamic page. Not published yet?

It's likely not being indexed yet by Algolia for it to show in search - here's a link to the documentation page: https://statamic.dev/customizing-the-cp-nav

**Pull request merged**
