### PR TITLE
[4.x] Use search index in entries fieldtype when possible

### PR DESCRIPTION
**Pull request by ryanmitchell**
If an entries field type is for 1 collection only we should use the search index where its available.

This could be extended to checking all search indexes to see if they match the count and contents of the collections in the entries field, but this smaller addition seems like a good enough start. 

Fixes: https://github.com/statamic/cms/issues/6376

### CODE REVIEW

**Review by jasonvarga — APPROVED** [review]
I edited it so that the method signature of `getIndexQuery` doesn't change, since that would be a breaking change.

But otherwise, thanks!

**Comment by kgirzadas** [comment]
"Entries" fieldtype is broken after these changes. 
Request to '/cp/fieldtypes/relationship' endpoint throws error:

```
local.ERROR: Method Statamic\Entries\EntryCollection::getCollection does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Statamic\\Entries\\EntryCollection::getCollection does not exist. at /var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:112)
[stacktrace]
#0 /var/www/html/vendor/statamic/cms/src/Fieldtypes/Entries.php(120): Illuminate\\Support\\Collection->__call()
#1 /var/www/html/vendor/statamic/cms/src/Http/Controllers/CP/Fieldtypes/RelationshipFieldtypeController.php(18): Statamic\\Fieldtypes\\Entries->getIndexItems()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Fieldtypes\\RelationshipFieldtypeController->index()
...
```

**Comment by jasonvarga** [comment]
@kgirzadas what page are you on when that request is happening?

**Comment by lukasleitsch** [comment]
Can confirm that the Entries fieldtype breaks after these changes.

In an `article.yml` blueprint, I have an author field:

```
          -
            handle: author
            field:
              max_items: 1
              mode: select
              create: false
              collections:
                - article_authors
              type: entries
              display: Author
              icon: entries
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
```

After opening the edit page, the request to the endpoint `/cp/fieldtypes/relationship` fails with:

```
Method Statamic\\Entries\\EntryCollection::getCollection does not exist.
```

Removing these three lines and the requests works again.

```
        if ($entries->getCollection()->first() instanceof Result) {
            $entries->setCollection($entries->getCollection()->map->getSearchable());
        }
```             
https://github.com/statamic/cms/blob/4.x/src/Fieldtypes/Entries.php#L120

**Comment by jasonvarga** [comment]
Thank you for the info. Fixed in #8414.

**Pull request merged**
