### PR TITLE
Fixed fatal path call when asset isn't found

### PR DESCRIPTION
**Pull request by FrittenKeeZ**
Related to #6431 and #7294

### CODE REVIEW

**Comment by FrittenKeeZ** [comment]
@jasonvarga seems like the Slack Notification thing is broken atm

**Comment by jasonvarga** [comment]
I reproduced the original issue by doing this:

- Have two different asset fields.
- Within both fields, select the same asset.
- In one field, edit the asset and rename it.
- The asset fieldtype you used will reflect the change. The other one will not.
- Hit save, the _other_ one submits the old filename.
- The change this PR proposes would filter out the incorrect filename.

This results in data loss because you filter out the filename. In the current situation, it doesn't save correctly, but at least you see an error, and you don't lose the existing saved data.

I think a proper solution should be for other asset fieldtypes to be aware of when an asset is renamed.

**Comment by FrittenKeeZ** [comment]
@jasonvarga I agree, but it was holding back content creation for our client as they just got a fatal error instead of being informed what asset caused the actual issue.

**Comment by FrittenKeeZ** [comment]
@jasonvarga would it be possible to have this merged in as a temporary fix until you've found and fixed the root cause?

**Comment by clementmas** [comment]
I'm currently copy/pasting this fix manually (into the vendor directory :/) so our users can upload more than 2 assets at the same time.

There's indeed data loss but it's better a server error on form submission. The issues linked above are very problematic for us.

**Comment by FrittenKeeZ** [comment]
@clementmas you can use this patch for now (`patches/statamic/cms/frittenkeez-asset-path-fatal.patch`):
```patch
diff --git a/src/Fieldtypes/Assets/Assets.php b/src/Fieldtypes/Assets/Assets.php
index d6a87e7388..d1f82fc08a 100644
--- a/src/Fieldtypes/Assets/Assets.php
+++ b/src/Fieldtypes/Assets/Assets.php
@@ -110,8 +110,8 @@ public function process($data)
         $max_files = (int) $this->config('max_files');
 
         $values = collect($data)->map(function ($id) {
-            return Asset::find($id)->path();
-        });
+            return Asset::find($id);
+        })->filter()->map->path();
 
         return $this->config('max_files') === 1 ? $values->first() : $values->all();
     }
```

**Pull request closed without merging**
