### PR TITLE
Add placeholder attr to form fields

### PR DESCRIPTION
**Pull request by kevnk**
The text and textarea fieldtypes have a placeholder field (when created in the cp), but the default templates to render those fields don't. This pull request would render them as expected.

### CODE REVIEW

**Comment by jasonvarga** [comment]
Could you make this a draft until it's ready?

**Comment by kevnk** [comment]
@jasonvarga This is ready now. Thanks!

**Comment by jackmcdade** [comment]
Thank you!

**Comment by kevnk** [comment]
Happy to help!

**Pull request merged**
