### PR TITLE
Hide replicator fields in preview

### PR DESCRIPTION
**Pull request by edalzell**
Closes https://github.com/statamic/ideas/issues/282

### CODE REVIEW

**Comment by edalzell** [comment]
@jackmcdade not sure about the naming of that field

**Comment by jackmcdade** [comment]
Gave it a little rename for clarity and to follow the verb-first pattern. Give it a test!

**Review by jackmcdade — APPROVED** [review]

**Comment by edalzell** [comment]
> If you can resolve the conflict @edalzell, we can merge this in.

@jackmcdade, done.

**Comment by jasonvarga** [comment]
I renamed it again, to be more in-line with other config options. Just simplified it to `previews: true`/`false`

Just like `collapse: true`/`false`.

Also, I think it could be cool to have this be a per-set option. I could see it being useful to disable the previews on some sets but leave the previews on other (e.g. text-heavy) sets.

I think this top level option can still be merged in, and we can add the per-set thing later. 👍

**Review by jasonvarga — APPROVED** [review]

**Pull request merged**
