### PR TITLE
Support taxonomy:term:not="something" syntax

### PR DESCRIPTION
**Pull request by jackmcdade**
Based on a conversation in Discord: https://discord.com/channels/489818810157891584/489819906540568593/939297442623549460

### CODE REVIEW

**Comment by ryanmitchell** [comment]
Would it be worth updating this to all add `orWhereTaxonomy`, `orWhereNotTaxonomy`, `orWhereTaxonomyIn()` and `ofWhereTaxonomyNotIn` at the same time?  The logic is already there from the query builder work - I can pull it together in a separate PR if you want?

**Comment by jackmcdade** [comment]
Sure! That would be awesome. Still waiting on a quick review from @jasonvarga to make sure I did this right because this isn't my usual area of responsibility :)

**Comment by ryanmitchell** [comment]
No problem - @jasonvarga let me know if you want it added to this PR or a different one.

**Comment by jasonvarga** [comment]
I'm going to merge this. I don't think we need to worry about the stuff @ryanmitchell brought up. At least not until someone asks for it.

**Pull request merged**
