### PR TITLE
Add a modify() helper for use in Blade

### PR DESCRIPTION
**Pull request by riasvdv**
This adds a nice helper function for people using Blade, which allows for `{{ modify($value)->nl2br() }}` for example

### CODE REVIEW

**Comment by jasonvarga** [comment]
With the trend being against global functions, I'm hesitant to add this. Especially with such a generic name. 🤔 It's a good idea though. I wonder if there's a better solution?

**Comment by riasvdv** [comment]
This feels to me like the `collect()` helper, a directive was my first idea, but you wouldn't be able to have chaining

**Comment by riasvdv** [comment]
It **is** only a one-liner though, so maybe it would be enough to just add it to the docs and people can add it to their projects if they need it

**Comment by jonassiewertsen** [comment]
I would like this helper a lot, but do see Jasons point. 

It may be possible or nice having more helper functions. So what about a statamic_FUNCTION naming. 

In this case:

statamic_modify()

Still global, but less generic.

**Comment by riasvdv** [comment]
I've added a PR to the docs: https://github.com/statamic/docs/pull/290

**Comment by jackmcdade** [comment]
I think this would be a nice add. Especially since it’s SO generic outside of the “modifier” namespace that any other global function would probably a noun attached. Eg “modifySomething”.

**Comment by jasonvarga** [comment]
@jackmcdade I agree with your reasoning here. But do you feel the same way about `tag()` in #2724? I could definitely see people using their own `tag()` for other things. If we have to come up with another convention for that one, we might want to apply it to this one.

**Comment by jasonvarga** [comment]
Gonna hold off on this for now and suggest devs plop it in their own helpers file. Thanks!

**Pull request closed without merging**
