### PR TITLE
Update the Entry Facade Doc blocks

### PR DESCRIPTION
**Pull request by jonassiewertsen**
The `find` method, which should be one of the most important ones, has not been included. 

I did as well point to the contact class only.

### CODE REVIEW

**Comment by jasonvarga** [comment]
Why has the return value changed to `EntryRepository` everywhere?

**Comment by jonassiewertsen** [comment]
That's the name of the interface we are using. This would be generic correct. 

Would it be better **not** to point to the interface itself?

**Comment by jasonvarga** [comment]
That's supposed to be the return value of that method. eg. when you run Entry::all(), you get an EntryCollection.

The original values all looked fine.

Also, find() was already in the docblock on line 12, but has an extra `mixed` that shouldn't be there, which is what's making it not work.

**Comment by jonassiewertsen** [comment]
That should be better now :-)

**Comment by jasonvarga** [comment]
Perfect, thanks.

**Pull request merged**
