### PR TITLE
[4.x] Allow relative urls as preview targets

### PR DESCRIPTION
**Pull request by helloiamlukas**
fixes https://github.com/statamic/cms/issues/8340

### CODE REVIEW

**Comment by jasonvarga** [comment]
Thank you but this breaks when you actually _want_ the preview target to be a different URL than the control panel.

I think the proper solution would be the ensure that the preview target URL is absolute in PHP before passing it to JS.

**Comment by helloiamlukas** [comment]
Hmm, I also tested it with absolute URLs and it works fine.

This pull request only changes 

```js
let iframeUrl = new URL(url);
```

to

```js
let iframeUrl = new URL(url, window.origin);
```

The `URL` constructor will ignore `window.origin` if `url` is already an absolute url ([see docs](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL)). Therefore absolute urls should not be affected by this change.

Am I missing something?

**Comment by jasonvarga** [comment]
Use a preview target on a domain different to the one you're accessing the control panel from.

**Comment by helloiamlukas** [comment]
Yes I did that – and it works. Can you explain why it shouldn't work after this commit? I feel like I'm missing something here 😕

**Comment by jasonvarga** [comment]
If you set the preview target to `{url}`, for example, when you try to preview the entry in the second site, it will visit `http://default-domain.com/entry` instead of `http://second-domain.com/entry`.

**Comment by helloiamlukas** [comment]
I am assuming you are talking about `{permalink}` and not `{url}`, right? 
Because `{url}` or even `{site:url}` will not work (at least in the current 4.x release).

I tested it with `{permalink}` on a multi-site and it works fine.

**Comment by jasonvarga** [comment]
`{permalink}` always worked fine. This PR is about making relative urls work, so I mean `{url}`.

**Comment by helloiamlukas** [comment]
Ok, I think I should have been more specific with the description of this pull request.

Since Statamic v4 it is not possible anymore to define **hardcoded** relative urls are preview targets.

E.g. this worked in v3, but not in v4 anymore:

```yaml
preview_targets:
  -
    label: Entry
    url: '/cp/custom-preview-target'
    refresh: true
```

This pull requests just fixes this incompatibility between v3 and v4. It does not introduce a new feature. Adding `{url}` will still not work, just like it did not in v3.

**Comment by jasonvarga** [comment]
Okay but I don't want to use what you've done because it doesn't solve the alternate domain issue. I've provided the suggested fix [in this comment](#issuecomment-1648493499).

**Pull request closed without merging**
